(define (problem menus)
    (:domain catering)
    (:objects Atun_al_horno Lubina_al_limon Calamares_a_la_romana Cazon Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscus Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz_blanco Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasanya - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Otro Pasta - tipo
)
    (:init
        (primero Atun_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazon)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscus)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz_blanco)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasanya)

        (segundo Bacalao_en_salsa_verde)(segundo Bacalao_con_tomate)(segundo Rabas_y_chocos)(segundo Boquerones_al_vinagre)(segundo Pulpo_a_la_feira)(segundo Langosta_a_la_salsa)(segundo Solomillo_de_cerdo)(segundo Pollo_a_la_brasa)(segundo Botifarra_del_pages)(segundo Costillitas_de_cordero)(segundo Callos)(segundo Pechuga_de_pollo)(segundo Ensalada_de_arroz)(segundo Paella)(segundo Arroz_con_setas)(segundo Arroz_frito_con_salsa_de_cebolla)(segundo Arroz_con_bogavantes)(segundo Risotto_con_gambas)(segundo Macarrones_a_la_carbonara)(segundo Spaghetti_al_pesto)(segundo Ramen)(segundo Fideos_con_verduras)(segundo Ravioli_a_la_genovesa)(segundo Tallarines_con_verduras)

            (NoCompatible Cazon Costillitas_de_cordero)
            (NoCompatible Pato_a_la_naranja Bacalao_en_salsa_verde)
            (NoCompatible Macarrones_a_la_bolognesa Bacalao_con_tomate)
            (NoCompatible Conejo_asado Arroz_con_bogavantes)
            (NoCompatible Hamburguesa_de_pollo Ravioli_a_la_genovesa)
            (NoCompatible Atun_al_horno Risotto_con_gambas)
            (NoCompatible Calamares_a_la_romana Rabas_y_chocos)
            (NoCompatible Sopa_de_fideos Solomillo_de_cerdo)
            (NoCompatible Spaghetti_a_la_bolognesa Botifarra_del_pages)
            (NoCompatible Arroz_salteado_con_verduras Costillitas_de_cordero)
            (NoCompatible Cazon Tallarines_con_verduras)
            (NoCompatible Fetuccini_a_la_putanesca Macarrones_a_la_carbonara)
            (NoCompatible Arroz_con_curry Boquerones_al_vinagre)
            (NoCompatible Cuscus Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Atun_al_horno Macarrones_a_la_carbonara)
            (NoCompatible Cuscus Tallarines_con_verduras)
            (NoCompatible Calamares_a_la_romana Botifarra_del_pages)
            (NoCompatible Spaghetti_a_la_carbonara Costillitas_de_cordero)
            (NoCompatible Galtas_de_cerdo Fideos_con_verduras)
            (NoCompatible Spaghetti_a_la_bolognesa Paella)
            (NoCompatible Pez_espada_y_cosas_pijas Paella)
            (NoCompatible Spaghetti_a_la_carbonara Bacalao_con_tomate)
            (NoCompatible Entrecot_al_roquefort Rabas_y_chocos)
            (NoCompatible Galtas_de_cerdo Spaghetti_al_pesto)
            (NoCompatible Conejo_asado Costillitas_de_cordero)
            (NoCompatible Cuscus Pechuga_de_pollo)
            (NoCompatible Cazon Arroz_con_bogavantes)
            (NoCompatible Lubina_al_limon Pollo_a_la_brasa)
            (NoCompatible Lasanya Macarrones_a_la_carbonara)
            (NoCompatible Cazon Callos)
            (NoCompatible Rabo_de_toro Pollo_a_la_brasa)
            (NoCompatible Fetuccini_a_la_putanesca Botifarra_del_pages)
            (NoCompatible Lubina_al_limon Tallarines_con_verduras)
            (NoCompatible Rabo_de_toro Bacalao_con_tomate)
            (NoCompatible Anchoas Bacalao_en_salsa_verde)
            (NoCompatible Arroz_blanco Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_a_la_cubana Pulpo_a_la_feira)
            (NoCompatible Atun_al_horno Callos)
            (NoCompatible Entrecot_al_roquefort Pulpo_a_la_feira)
            (NoCompatible Arroz_blanco Pechuga_de_pollo)
            (NoCompatible Spaghetti_a_la_bolognesa Fideos_con_verduras)
            (NoCompatible Lasanya Rabas_y_chocos)
            (NoCompatible Hamburguesa_de_pollo Bacalao_con_tomate)
            (NoCompatible Pez_espada_y_cosas_pijas Arroz_con_bogavantes)
            (NoCompatible Anchoas Fideos_con_verduras)
            (NoCompatible Cazon Pulpo_a_la_feira)
            (NoCompatible Macarrones_a_la_bolognesa Fideos_con_verduras)
            (NoCompatible Cuscus Bacalao_en_salsa_verde)

            (tipoP Atun_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazon Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Carne)
            (tipoS Solomillo_de_cerdo Carne)
            (tipoP Pato_a_la_naranja Carne)
            (tipoS Pollo_a_la_brasa Carne)
            (tipoP Rabo_de_toro Carne)
            (tipoS Botifarra_del_pages Carne)
            (tipoP Entrecot_al_roquefort Carne)
            (tipoS Costillitas_de_cordero Carne)
            (tipoP Galtas_de_cerdo Carne)
            (tipoS Callos Carne)
            (tipoP Hamburguesa_de_pollo Carne)
            (tipoS Pechuga_de_pollo Carne)

            (tipoP Arroz_a_la_cubana Otro)
            (tipoS Ensalada_de_arroz Otro)
            (tipoP Cuscus Otro)
            (tipoS Paella Otro)
            (tipoP Arroz_con_curry Otro)
            (tipoS Arroz_con_setas Otro)
            (tipoP Arroz_tres_delicias Otro)
            (tipoS Arroz_frito_con_salsa_de_cebolla Otro)
            (tipoP Arroz_salteado_con_verduras Otro)
            (tipoS Arroz_con_bogavantes Otro)
            (tipoP Arroz_blanco Otro)
            (tipoS Risotto_con_gambas Otro)

            (tipoP Macarrones_a_la_bolognesa Pasta)
            (tipoS Macarrones_a_la_carbonara Pasta)
            (tipoP Spaghetti_a_la_bolognesa Pasta)
            (tipoS Spaghetti_al_pesto Pasta)
            (tipoP Spaghetti_a_la_carbonara Pasta)
            (tipoS Ramen Pasta)
            (tipoP Sopa_de_fideos Pasta)
            (tipoS Fideos_con_verduras Pasta)
            (tipoP Fetuccini_a_la_putanesca Pasta)
            (tipoS Ravioli_a_la_genovesa Pasta)
            (tipoP Lasanya Pasta)
            (tipoS Tallarines_con_verduras Pasta)

            (mustUse Martes Galtas_de_cerdo)
            (RestrictedPrimero Martes)
            (mustUse Jueves Pato_a_la_naranja)
            (RestrictedPrimero Jueves)

            (mustUse Miercoles Bacalao_con_tomate)
            (RestrictedSegundo Miercoles)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atun_al_horno) 632)
            (= (Pcals Lubina_al_limon) 718)
            (= (Pcals Calamares_a_la_romana) 753)
            (= (Pcals Cazon) 764)
            (= (Pcals Anchoas) 660)
            (= (Pcals Pez_espada_y_cosas_pijas) 595)
            (= (Pcals Conejo_asado) 673)
            (= (Pcals Pato_a_la_naranja) 515)
            (= (Pcals Rabo_de_toro) 503)
            (= (Pcals Entrecot_al_roquefort) 548)
            (= (Pcals Galtas_de_cerdo) 786)
            (= (Pcals Hamburguesa_de_pollo) 778)
            (= (Pcals Arroz_a_la_cubana) 516)
            (= (Pcals Cuscus) 799)
            (= (Pcals Arroz_con_curry) 735)
            (= (Pcals Arroz_tres_delicias) 631)
            (= (Pcals Arroz_salteado_con_verduras) 554)
            (= (Pcals Arroz_blanco) 599)
            (= (Pcals Macarrones_a_la_bolognesa) 576)
            (= (Pcals Spaghetti_a_la_bolognesa) 676)
            (= (Pcals Spaghetti_a_la_carbonara) 799)
            (= (Pcals Sopa_de_fideos) 551)
            (= (Pcals Fetuccini_a_la_putanesca) 611)
            (= (Pcals Lasanya) 658)

            (= (Scals Bacalao_en_salsa_verde) 503)
            (= (Scals Bacalao_con_tomate) 613)
            (= (Scals Rabas_y_chocos) 675)
            (= (Scals Boquerones_al_vinagre) 757)
            (= (Scals Pulpo_a_la_feira) 799)
            (= (Scals Langosta_a_la_salsa) 722)
            (= (Scals Solomillo_de_cerdo) 602)
            (= (Scals Pollo_a_la_brasa) 637)
            (= (Scals Botifarra_del_pages) 745)
            (= (Scals Costillitas_de_cordero) 502)
            (= (Scals Callos) 789)
            (= (Scals Pechuga_de_pollo) 686)
            (= (Scals Ensalada_de_arroz) 568)
            (= (Scals Paella) 630)
            (= (Scals Arroz_con_setas) 714)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 603)
            (= (Scals Arroz_con_bogavantes) 674)
            (= (Scals Risotto_con_gambas) 620)
            (= (Scals Macarrones_a_la_carbonara) 600)
            (= (Scals Spaghetti_al_pesto) 657)
            (= (Scals Ramen) 576)
            (= (Scals Fideos_con_verduras) 648)
            (= (Scals Ravioli_a_la_genovesa) 681)
            (= (Scals Tallarines_con_verduras) 540)

            (= (Pprice Atun_al_horno) 7)
            (= (Pprice Lubina_al_limon) 8)
            (= (Pprice Calamares_a_la_romana) 14)
            (= (Pprice Cazon) 5)
            (= (Pprice Anchoas) 9)
            (= (Pprice Pez_espada_y_cosas_pijas) 12)
            (= (Pprice Conejo_asado) 12)
            (= (Pprice Pato_a_la_naranja) 12)
            (= (Pprice Rabo_de_toro) 9)
            (= (Pprice Entrecot_al_roquefort) 5)
            (= (Pprice Galtas_de_cerdo) 15)
            (= (Pprice Hamburguesa_de_pollo) 7)
            (= (Pprice Arroz_a_la_cubana) 13)
            (= (Pprice Cuscus) 7)
            (= (Pprice Arroz_con_curry) 5)
            (= (Pprice Arroz_tres_delicias) 15)
            (= (Pprice Arroz_salteado_con_verduras) 15)
            (= (Pprice Arroz_blanco) 7)
            (= (Pprice Macarrones_a_la_bolognesa) 8)
            (= (Pprice Spaghetti_a_la_bolognesa) 12)
            (= (Pprice Spaghetti_a_la_carbonara) 13)
            (= (Pprice Sopa_de_fideos) 5)
            (= (Pprice Fetuccini_a_la_putanesca) 9)
            (= (Pprice Lasanya) 7)

            (= (Sprice Bacalao_en_salsa_verde) 13)
            (= (Sprice Bacalao_con_tomate) 8)
            (= (Sprice Rabas_y_chocos) 9)
            (= (Sprice Boquerones_al_vinagre) 9)
            (= (Sprice Pulpo_a_la_feira) 8)
            (= (Sprice Langosta_a_la_salsa) 6)
            (= (Sprice Solomillo_de_cerdo) 10)
            (= (Sprice Pollo_a_la_brasa) 7)
            (= (Sprice Botifarra_del_pages) 15)
            (= (Sprice Costillitas_de_cordero) 14)
            (= (Sprice Callos) 9)
            (= (Sprice Pechuga_de_pollo) 8)
            (= (Sprice Ensalada_de_arroz) 11)
            (= (Sprice Paella) 14)
            (= (Sprice Arroz_con_setas) 11)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 10)
            (= (Sprice Arroz_con_bogavantes) 8)
            (= (Sprice Risotto_con_gambas) 6)
            (= (Sprice Macarrones_a_la_carbonara) 5)
            (= (Sprice Spaghetti_al_pesto) 5)
            (= (Sprice Ramen) 14)
            (= (Sprice Fideos_con_verduras) 12)
            (= (Sprice Ravioli_a_la_genovesa) 15)
            (= (Sprice Tallarines_con_verduras) 14)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)