(define (problem menus)
    (:domain catering)
    (:objects Atun_al_horno Lubina_al_limon Calamares_a_la_romana Cazon Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscus Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz_blanco Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasanya - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Otro Pasta - tipo
)
    (:init
        (primero Atun_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazon)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscus)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz_blanco)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasanya)

        (segundo Bacalao_en_salsa_verde)(segundo Bacalao_con_tomate)(segundo Rabas_y_chocos)(segundo Boquerones_al_vinagre)(segundo Pulpo_a_la_feira)(segundo Langosta_a_la_salsa)(segundo Solomillo_de_cerdo)(segundo Pollo_a_la_brasa)(segundo Botifarra_del_pages)(segundo Costillitas_de_cordero)(segundo Callos)(segundo Pechuga_de_pollo)(segundo Ensalada_de_arroz)(segundo Paella)(segundo Arroz_con_setas)(segundo Arroz_frito_con_salsa_de_cebolla)(segundo Arroz_con_bogavantes)(segundo Risotto_con_gambas)(segundo Macarrones_a_la_carbonara)(segundo Spaghetti_al_pesto)(segundo Ramen)(segundo Fideos_con_verduras)(segundo Ravioli_a_la_genovesa)(segundo Tallarines_con_verduras)

            (NoCompatible Rabo_de_toro Rabas_y_chocos)
            (NoCompatible Macarrones_a_la_bolognesa Paella)
            (NoCompatible Arroz_tres_delicias Ramen)
            (NoCompatible Rabo_de_toro Langosta_a_la_salsa)
            (NoCompatible Entrecot_al_roquefort Botifarra_del_pages)
            (NoCompatible Sopa_de_fideos Botifarra_del_pages)
            (NoCompatible Fetuccini_a_la_putanesca Callos)
            (NoCompatible Arroz_blanco Bacalao_con_tomate)
            (NoCompatible Arroz_a_la_cubana Rabas_y_chocos)
            (NoCompatible Spaghetti_a_la_carbonara Macarrones_a_la_carbonara)
            (NoCompatible Atun_al_horno Macarrones_a_la_carbonara)
            (NoCompatible Calamares_a_la_romana Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Calamares_a_la_romana Solomillo_de_cerdo)
            (NoCompatible Sopa_de_fideos Arroz_con_setas)
            (NoCompatible Macarrones_a_la_bolognesa Rabas_y_chocos)
            (NoCompatible Arroz_salteado_con_verduras Pulpo_a_la_feira)
            (NoCompatible Calamares_a_la_romana Arroz_con_setas)
            (NoCompatible Lasanya Risotto_con_gambas)
            (NoCompatible Cazon Langosta_a_la_salsa)
            (NoCompatible Spaghetti_a_la_bolognesa Langosta_a_la_salsa)
            (NoCompatible Pato_a_la_naranja Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Cuscus Botifarra_del_pages)
            (NoCompatible Cazon Bacalao_con_tomate)
            (NoCompatible Arroz_tres_delicias Callos)
            (NoCompatible Galtas_de_cerdo Langosta_a_la_salsa)
            (NoCompatible Cuscus Bacalao_con_tomate)
            (NoCompatible Hamburguesa_de_pollo Tallarines_con_verduras)
            (NoCompatible Arroz_a_la_cubana Spaghetti_al_pesto)
            (NoCompatible Lasanya Botifarra_del_pages)
            (NoCompatible Arroz_blanco Spaghetti_al_pesto)
            (NoCompatible Cazon Rabas_y_chocos)
            (NoCompatible Sopa_de_fideos Macarrones_a_la_carbonara)
            (NoCompatible Sopa_de_fideos Bacalao_en_salsa_verde)
            (NoCompatible Calamares_a_la_romana Ravioli_a_la_genovesa)
            (NoCompatible Calamares_a_la_romana Botifarra_del_pages)
            (NoCompatible Sopa_de_fideos Spaghetti_al_pesto)
            (NoCompatible Arroz_tres_delicias Costillitas_de_cordero)
            (NoCompatible Spaghetti_a_la_carbonara Fideos_con_verduras)
            (NoCompatible Galtas_de_cerdo Paella)
            (NoCompatible Lasanya Pulpo_a_la_feira)
            (NoCompatible Galtas_de_cerdo Ensalada_de_arroz)
            (NoCompatible Fetuccini_a_la_putanesca Tallarines_con_verduras)
            (NoCompatible Calamares_a_la_romana Callos)
            (NoCompatible Arroz_tres_delicias Pechuga_de_pollo)
            (NoCompatible Lubina_al_limon Solomillo_de_cerdo)
            (NoCompatible Entrecot_al_roquefort Costillitas_de_cordero)
            (NoCompatible Spaghetti_a_la_carbonara Boquerones_al_vinagre)
            (NoCompatible Entrecot_al_roquefort Pollo_a_la_brasa)

            (tipoP Atun_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazon Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Carne)
            (tipoS Solomillo_de_cerdo Carne)
            (tipoP Pato_a_la_naranja Carne)
            (tipoS Pollo_a_la_brasa Carne)
            (tipoP Rabo_de_toro Carne)
            (tipoS Botifarra_del_pages Carne)
            (tipoP Entrecot_al_roquefort Carne)
            (tipoS Costillitas_de_cordero Carne)
            (tipoP Galtas_de_cerdo Carne)
            (tipoS Callos Carne)
            (tipoP Hamburguesa_de_pollo Carne)
            (tipoS Pechuga_de_pollo Carne)

            (tipoP Arroz_a_la_cubana Otro)
            (tipoS Ensalada_de_arroz Otro)
            (tipoP Cuscus Otro)
            (tipoS Paella Otro)
            (tipoP Arroz_con_curry Otro)
            (tipoS Arroz_con_setas Otro)
            (tipoP Arroz_tres_delicias Otro)
            (tipoS Arroz_frito_con_salsa_de_cebolla Otro)
            (tipoP Arroz_salteado_con_verduras Otro)
            (tipoS Arroz_con_bogavantes Otro)
            (tipoP Arroz_blanco Otro)
            (tipoS Risotto_con_gambas Otro)

            (tipoP Macarrones_a_la_bolognesa Pasta)
            (tipoS Macarrones_a_la_carbonara Pasta)
            (tipoP Spaghetti_a_la_bolognesa Pasta)
            (tipoS Spaghetti_al_pesto Pasta)
            (tipoP Spaghetti_a_la_carbonara Pasta)
            (tipoS Ramen Pasta)
            (tipoP Sopa_de_fideos Pasta)
            (tipoS Fideos_con_verduras Pasta)
            (tipoP Fetuccini_a_la_putanesca Pasta)
            (tipoS Ravioli_a_la_genovesa Pasta)
            (tipoP Lasanya Pasta)
            (tipoS Tallarines_con_verduras Pasta)

            (mustUse Jueves Lubina_al_limon)
            (RestrictedPrimero Jueves)

            (mustUse Lunes Macarrones_a_la_carbonara)
            (RestrictedSegundo Lunes)
            (mustUse Miercoles Solomillo_de_cerdo)
            (RestrictedSegundo Miercoles)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atun_al_horno) 693)
            (= (Pcals Lubina_al_limon) 766)
            (= (Pcals Calamares_a_la_romana) 632)
            (= (Pcals Cazon) 551)
            (= (Pcals Anchoas) 647)
            (= (Pcals Pez_espada_y_cosas_pijas) 604)
            (= (Pcals Conejo_asado) 767)
            (= (Pcals Pato_a_la_naranja) 640)
            (= (Pcals Rabo_de_toro) 773)
            (= (Pcals Entrecot_al_roquefort) 629)
            (= (Pcals Galtas_de_cerdo) 705)
            (= (Pcals Hamburguesa_de_pollo) 540)
            (= (Pcals Arroz_a_la_cubana) 783)
            (= (Pcals Cuscus) 747)
            (= (Pcals Arroz_con_curry) 684)
            (= (Pcals Arroz_tres_delicias) 748)
            (= (Pcals Arroz_salteado_con_verduras) 707)
            (= (Pcals Arroz_blanco) 730)
            (= (Pcals Macarrones_a_la_bolognesa) 685)
            (= (Pcals Spaghetti_a_la_bolognesa) 563)
            (= (Pcals Spaghetti_a_la_carbonara) 686)
            (= (Pcals Sopa_de_fideos) 757)
            (= (Pcals Fetuccini_a_la_putanesca) 789)
            (= (Pcals Lasanya) 599)

            (= (Scals Bacalao_en_salsa_verde) 731)
            (= (Scals Bacalao_con_tomate) 782)
            (= (Scals Rabas_y_chocos) 610)
            (= (Scals Boquerones_al_vinagre) 720)
            (= (Scals Pulpo_a_la_feira) 522)
            (= (Scals Langosta_a_la_salsa) 655)
            (= (Scals Solomillo_de_cerdo) 596)
            (= (Scals Pollo_a_la_brasa) 664)
            (= (Scals Botifarra_del_pages) 527)
            (= (Scals Costillitas_de_cordero) 661)
            (= (Scals Callos) 573)
            (= (Scals Pechuga_de_pollo) 522)
            (= (Scals Ensalada_de_arroz) 514)
            (= (Scals Paella) 581)
            (= (Scals Arroz_con_setas) 723)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 587)
            (= (Scals Arroz_con_bogavantes) 636)
            (= (Scals Risotto_con_gambas) 716)
            (= (Scals Macarrones_a_la_carbonara) 713)
            (= (Scals Spaghetti_al_pesto) 577)
            (= (Scals Ramen) 550)
            (= (Scals Fideos_con_verduras) 514)
            (= (Scals Ravioli_a_la_genovesa) 691)
            (= (Scals Tallarines_con_verduras) 732)

            (= (Pprice Atun_al_horno) 9)
            (= (Pprice Lubina_al_limon) 14)
            (= (Pprice Calamares_a_la_romana) 13)
            (= (Pprice Cazon) 15)
            (= (Pprice Anchoas) 5)
            (= (Pprice Pez_espada_y_cosas_pijas) 12)
            (= (Pprice Conejo_asado) 10)
            (= (Pprice Pato_a_la_naranja) 14)
            (= (Pprice Rabo_de_toro) 7)
            (= (Pprice Entrecot_al_roquefort) 9)
            (= (Pprice Galtas_de_cerdo) 10)
            (= (Pprice Hamburguesa_de_pollo) 8)
            (= (Pprice Arroz_a_la_cubana) 6)
            (= (Pprice Cuscus) 15)
            (= (Pprice Arroz_con_curry) 12)
            (= (Pprice Arroz_tres_delicias) 9)
            (= (Pprice Arroz_salteado_con_verduras) 15)
            (= (Pprice Arroz_blanco) 11)
            (= (Pprice Macarrones_a_la_bolognesa) 12)
            (= (Pprice Spaghetti_a_la_bolognesa) 12)
            (= (Pprice Spaghetti_a_la_carbonara) 12)
            (= (Pprice Sopa_de_fideos) 10)
            (= (Pprice Fetuccini_a_la_putanesca) 10)
            (= (Pprice Lasanya) 9)

            (= (Sprice Bacalao_en_salsa_verde) 10)
            (= (Sprice Bacalao_con_tomate) 7)
            (= (Sprice Rabas_y_chocos) 11)
            (= (Sprice Boquerones_al_vinagre) 10)
            (= (Sprice Pulpo_a_la_feira) 15)
            (= (Sprice Langosta_a_la_salsa) 8)
            (= (Sprice Solomillo_de_cerdo) 15)
            (= (Sprice Pollo_a_la_brasa) 13)
            (= (Sprice Botifarra_del_pages) 10)
            (= (Sprice Costillitas_de_cordero) 11)
            (= (Sprice Callos) 7)
            (= (Sprice Pechuga_de_pollo) 5)
            (= (Sprice Ensalada_de_arroz) 8)
            (= (Sprice Paella) 11)
            (= (Sprice Arroz_con_setas) 7)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 6)
            (= (Sprice Arroz_con_bogavantes) 10)
            (= (Sprice Risotto_con_gambas) 5)
            (= (Sprice Macarrones_a_la_carbonara) 12)
            (= (Sprice Spaghetti_al_pesto) 7)
            (= (Sprice Ramen) 13)
            (= (Sprice Fideos_con_verduras) 5)
            (= (Sprice Ravioli_a_la_genovesa) 6)
            (= (Sprice Tallarines_con_verduras) 8)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)