(define (problem menus)
    (:domain catering)
    (:objects Atún_al_horno Lubina_al_limon Calamares_a_la_romana Cazón Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscús Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasaña - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Arroz Pasta - tipo
)
    (:init
        (primero Atún_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazón)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscús)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasaña)

        (Segundo Bacalao_en_salsa_verde)(Segundo Bacalao_con_tomate)(Segundo Rabas_y_chocos)(Segundo Boquerones_al_vinagre)(Segundo Pulpo_a_la_feira)(Segundo Langosta_a_la_salsa)(Segundo Solomillo_de_cerdo)(Segundo Pollo_a_la_brasa)(Segundo Botifarra_del_pages)(Segundo Costillitas_de_cordero)(Segundo Callos)(Segundo Pechuga_de_pollo)(Segundo Ensalada_de_arroz)(Segundo Paella)(Segundo Arroz_con_setas)(Segundo Arroz_frito_con_salsa_de_cebolla)(Segundo Arroz_con_bogavantes)(Segundo Risotto_con_gambas)(Segundo Macarrones_a_la_carbonara)(Segundo Spaghetti_al_pesto)(Segundo Ramen)(Segundo Fideos_con_verduras)(Segundo Ravioli_a_la_genovesa)(Segundo Tallarines_con_verduras)

            (NoCompatible Fetuccini_a_la_putanesca Spaghetti_al_pesto)
            (NoCompatible Macarrones_a_la_bolognesa Paella)
            (NoCompatible Hamburguesa_de_pollo Bacalao_con_tomate)
            (NoCompatible Atún_al_horno Ramen)
            (NoCompatible Lubina_al_limon Botifarra_del_pages)
            (NoCompatible Rabo_de_toro Pulpo_a_la_feira)
            (NoCompatible Arroz_tres_delicias Solomillo_de_cerdo)
            (NoCompatible Conejo_asado Pulpo_a_la_feira)
            (NoCompatible Arroz_tres_delicias Ravioli_a_la_genovesa)
            (NoCompatible Atún_al_horno Boquerones_al_vinagre)
            (NoCompatible Calamares_a_la_romana Solomillo_de_cerdo)
            (NoCompatible Galtas_de_cerdo Paella)
            (NoCompatible Arroz_a_la_cubana Risotto_con_gambas)
            (NoCompatible Hamburguesa_de_pollo Costillitas_de_cordero)
            (NoCompatible Galtas_de_cerdo Bacalao_con_tomate)
            (NoCompatible Rabo_de_toro Macarrones_a_la_carbonara)
            (NoCompatible Rabo_de_toro Langosta_a_la_salsa)
            (NoCompatible Pato_a_la_naranja Spaghetti_al_pesto)
            (NoCompatible Pez_espada_y_cosas_pijas Ravioli_a_la_genovesa)
            (NoCompatible Cuscús Pulpo_a_la_feira)
            (NoCompatible Rabo_de_toro Bacalao_con_tomate)
            (NoCompatible Cuscús Pollo_a_la_brasa)
            (NoCompatible Arroz_a_la_cubana Solomillo_de_cerdo)
            (NoCompatible Conejo_asado Costillitas_de_cordero)
            (NoCompatible Spaghetti_a_la_bolognesa Bacalao_en_salsa_verde)
            (NoCompatible Fetuccini_a_la_putanesca Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_a_la_cubana Macarrones_a_la_carbonara)
            (NoCompatible Calamares_a_la_romana Botifarra_del_pages)
            (NoCompatible Atún_al_horno Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Pez_espada_y_cosas_pijas Pechuga_de_pollo)
            (NoCompatible Pez_espada_y_cosas_pijas Paella)
            (NoCompatible Sopa_de_fideos Pulpo_a_la_feira)
            (NoCompatible Cazón Boquerones_al_vinagre)
            (NoCompatible Calamares_a_la_romana Costillitas_de_cordero)
            (NoCompatible Sopa_de_fideos Callos)
            (NoCompatible Rabo_de_toro Ensalada_de_arroz)
            (NoCompatible Rabo_de_toro Arroz_con_setas)
            (NoCompatible Cazón Callos)
            (NoCompatible Conejo_asado Bacalao_con_tomate)
            (NoCompatible Cazón Tallarines_con_verduras)
            (NoCompatible Spaghetti_a_la_carbonara Ravioli_a_la_genovesa)
            (NoCompatible Arroz_tres_delicias Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Lasaña Pollo_a_la_brasa)
            (NoCompatible Atún_al_horno Fideos_con_verduras)
            (NoCompatible Cuscús Ravioli_a_la_genovesa)
            (NoCompatible Arroz Arroz_con_bogavantes)
            (NoCompatible Macarrones_a_la_bolognesa Pollo_a_la_brasa)
            (NoCompatible Arroz_a_la_cubana Bacalao_en_salsa_verde)

            (tipoP Atún_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazón Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Pescado)
            (tipoS Solomillo_de_cerdo Pescado)
            (tipoP Pato_a_la_naranja Pescado)
            (tipoS Pollo_a_la_brasa Pescado)
            (tipoP Rabo_de_toro Pescado)
            (tipoS Botifarra_del_pages Pescado)
            (tipoP Entrecot_al_roquefort Pescado)
            (tipoS Costillitas_de_cordero Pescado)
            (tipoP Galtas_de_cerdo Pescado)
            (tipoS Callos Pescado)
            (tipoP Hamburguesa_de_pollo Pescado)
            (tipoS Pechuga_de_pollo Pescado)

            (tipoP Arroz_a_la_cubana Pescado)
            (tipoS Ensalada_de_arroz Pescado)
            (tipoP Cuscús Pescado)
            (tipoS Paella Pescado)
            (tipoP Arroz_con_curry Pescado)
            (tipoS Arroz_con_setas Pescado)
            (tipoP Arroz_tres_delicias Pescado)
            (tipoS Arroz_frito_con_salsa_de_cebolla Pescado)
            (tipoP Arroz_salteado_con_verduras Pescado)
            (tipoS Arroz_con_bogavantes Pescado)
            (tipoP Arroz Pescado)
            (tipoS Risotto_con_gambas Pescado)

            (tipoP Macarrones_a_la_bolognesa Pescado)
            (tipoS Macarrones_a_la_carbonara Pescado)
            (tipoP Spaghetti_a_la_bolognesa Pescado)
            (tipoS Spaghetti_al_pesto Pescado)
            (tipoP Spaghetti_a_la_carbonara Pescado)
            (tipoS Ramen Pescado)
            (tipoP Sopa_de_fideos Pescado)
            (tipoS Fideos_con_verduras Pescado)
            (tipoP Fetuccini_a_la_putanesca Pescado)
            (tipoS Ravioli_a_la_genovesa Pescado)
            (tipoP Lasaña Pescado)
            (tipoS Tallarines_con_verduras Pescado)

            (mustUse Miercoles Calamares_a_la_romana)
            (RestrictedPrimero Miercoles)
            (mustUse Jueves Spaghetti_a_la_bolognesa)
            (RestrictedPrimero Jueves)

            (mustUse Miercoles Fideos_con_verduras)
            (RestrictedSegundo Miercoles)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atún_al_horno) 500)
            (= (Pcals Lubina_al_limon) 695)
            (= (Pcals Calamares_a_la_romana) 606)
            (= (Pcals Cazón) 687)
            (= (Pcals Anchoas) 718)
            (= (Pcals Pez_espada_y_cosas_pijas) 726)
            (= (Pcals Conejo_asado) 730)
            (= (Pcals Pato_a_la_naranja) 724)
            (= (Pcals Rabo_de_toro) 629)
            (= (Pcals Entrecot_al_roquefort) 508)
            (= (Pcals Galtas_de_cerdo) 534)
            (= (Pcals Hamburguesa_de_pollo) 634)
            (= (Pcals Arroz_a_la_cubana) 569)
            (= (Pcals Cuscús) 619)
            (= (Pcals Arroz_con_curry) 704)
            (= (Pcals Arroz_tres_delicias) 727)
            (= (Pcals Arroz_salteado_con_verduras) 676)
            (= (Pcals Arroz) 800)
            (= (Pcals Macarrones_a_la_bolognesa) 697)
            (= (Pcals Spaghetti_a_la_bolognesa) 587)
            (= (Pcals Spaghetti_a_la_carbonara) 800)
            (= (Pcals Sopa_de_fideos) 532)
            (= (Pcals Fetuccini_a_la_putanesca) 574)
            (= (Pcals Lasaña) 694)

            (= (Scals Bacalao_en_salsa_verde) 666)
            (= (Scals Bacalao_con_tomate) 575)
            (= (Scals Rabas_y_chocos) 714)
            (= (Scals Boquerones_al_vinagre) 639)
            (= (Scals Pulpo_a_la_feira) 646)
            (= (Scals Langosta_a_la_salsa) 783)
            (= (Scals Solomillo_de_cerdo) 510)
            (= (Scals Pollo_a_la_brasa) 595)
            (= (Scals Botifarra_del_pages) 604)
            (= (Scals Costillitas_de_cordero) 663)
            (= (Scals Callos) 520)
            (= (Scals Pechuga_de_pollo) 539)
            (= (Scals Ensalada_de_arroz) 556)
            (= (Scals Paella) 505)
            (= (Scals Arroz_con_setas) 652)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 622)
            (= (Scals Arroz_con_bogavantes) 720)
            (= (Scals Risotto_con_gambas) 772)
            (= (Scals Macarrones_a_la_carbonara) 632)
            (= (Scals Spaghetti_al_pesto) 705)
            (= (Scals Ramen) 740)
            (= (Scals Fideos_con_verduras) 633)
            (= (Scals Ravioli_a_la_genovesa) 714)
            (= (Scals Tallarines_con_verduras) 675)

            (= (Pprice Atún_al_horno) 12)
            (= (Pprice Lubina_al_limon) 11)
            (= (Pprice Calamares_a_la_romana) 5)
            (= (Pprice Cazón) 6)
            (= (Pprice Anchoas) 7)
            (= (Pprice Pez_espada_y_cosas_pijas) 11)
            (= (Pprice Conejo_asado) 7)
            (= (Pprice Pato_a_la_naranja) 12)
            (= (Pprice Rabo_de_toro) 12)
            (= (Pprice Entrecot_al_roquefort) 5)
            (= (Pprice Galtas_de_cerdo) 15)
            (= (Pprice Hamburguesa_de_pollo) 8)
            (= (Pprice Arroz_a_la_cubana) 12)
            (= (Pprice Cuscús) 14)
            (= (Pprice Arroz_con_curry) 7)
            (= (Pprice Arroz_tres_delicias) 7)
            (= (Pprice Arroz_salteado_con_verduras) 11)
            (= (Pprice Arroz) 10)
            (= (Pprice Macarrones_a_la_bolognesa) 6)
            (= (Pprice Spaghetti_a_la_bolognesa) 13)
            (= (Pprice Spaghetti_a_la_carbonara) 11)
            (= (Pprice Sopa_de_fideos) 11)
            (= (Pprice Fetuccini_a_la_putanesca) 11)
            (= (Pprice Lasaña) 15)

            (= (Sprice Bacalao_en_salsa_verde) 9)
            (= (Sprice Bacalao_con_tomate) 12)
            (= (Sprice Rabas_y_chocos) 7)
            (= (Sprice Boquerones_al_vinagre) 10)
            (= (Sprice Pulpo_a_la_feira) 11)
            (= (Sprice Langosta_a_la_salsa) 8)
            (= (Sprice Solomillo_de_cerdo) 9)
            (= (Sprice Pollo_a_la_brasa) 14)
            (= (Sprice Botifarra_del_pages) 12)
            (= (Sprice Costillitas_de_cordero) 15)
            (= (Sprice Callos) 6)
            (= (Sprice Pechuga_de_pollo) 5)
            (= (Sprice Ensalada_de_arroz) 10)
            (= (Sprice Paella) 13)
            (= (Sprice Arroz_con_setas) 10)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 15)
            (= (Sprice Arroz_con_bogavantes) 11)
            (= (Sprice Risotto_con_gambas) 6)
            (= (Sprice Macarrones_a_la_carbonara) 11)
            (= (Sprice Spaghetti_al_pesto) 5)
            (= (Sprice Ramen) 8)
            (= (Sprice Fideos_con_verduras) 14)
            (= (Sprice Ravioli_a_la_genovesa) 9)
            (= (Sprice Tallarines_con_verduras) 13)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)