(define (problem menus)
    (:domain catering)
    (:objects Atún_al_horno Lubina_al_limon Calamares_a_la_romana Cazón Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscús Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasaña - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Arroz Pasta - tipo
)
    (:init
        (primero Atún_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazón)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscús)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasaña)

        (Segundo Bacalao_en_salsa_verde)(Segundo Bacalao_con_tomate)(Segundo Rabas_y_chocos)(Segundo Boquerones_al_vinagre)(Segundo Pulpo_a_la_feira)(Segundo Langosta_a_la_salsa)(Segundo Solomillo_de_cerdo)(Segundo Pollo_a_la_brasa)(Segundo Botifarra_del_pages)(Segundo Costillitas_de_cordero)(Segundo Callos)(Segundo Pechuga_de_pollo)(Segundo Ensalada_de_arroz)(Segundo Paella)(Segundo Arroz_con_setas)(Segundo Arroz_frito_con_salsa_de_cebolla)(Segundo Arroz_con_bogavantes)(Segundo Risotto_con_gambas)(Segundo Macarrones_a_la_carbonara)(Segundo Spaghetti_al_pesto)(Segundo Ramen)(Segundo Fideos_con_verduras)(Segundo Ravioli_a_la_genovesa)(Segundo Tallarines_con_verduras)

            (NoCompatible Anchoas Tallarines_con_verduras)
            (NoCompatible Conejo_asado Fideos_con_verduras)
            (NoCompatible Atún_al_horno Spaghetti_al_pesto)
            (NoCompatible Spaghetti_a_la_bolognesa Pulpo_a_la_feira)
            (NoCompatible Sopa_de_fideos Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_con_curry Pechuga_de_pollo)
            (NoCompatible Pez_espada_y_cosas_pijas Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Galtas_de_cerdo Ravioli_a_la_genovesa)
            (NoCompatible Lubina_al_limon Rabas_y_chocos)
            (NoCompatible Rabo_de_toro Pechuga_de_pollo)
            (NoCompatible Arroz_con_curry Pulpo_a_la_feira)
            (NoCompatible Calamares_a_la_romana Arroz_con_setas)
            (NoCompatible Arroz Botifarra_del_pages)
            (NoCompatible Arroz_tres_delicias Fideos_con_verduras)
            (NoCompatible Conejo_asado Risotto_con_gambas)
            (NoCompatible Atún_al_horno Rabas_y_chocos)
            (NoCompatible Galtas_de_cerdo Bacalao_en_salsa_verde)
            (NoCompatible Sopa_de_fideos Bacalao_con_tomate)
            (NoCompatible Macarrones_a_la_bolognesa Fideos_con_verduras)
            (NoCompatible Pez_espada_y_cosas_pijas Bacalao_en_salsa_verde)
            (NoCompatible Calamares_a_la_romana Ensalada_de_arroz)
            (NoCompatible Arroz_tres_delicias Ensalada_de_arroz)
            (NoCompatible Sopa_de_fideos Ravioli_a_la_genovesa)
            (NoCompatible Macarrones_a_la_bolognesa Arroz_con_setas)
            (NoCompatible Arroz_con_curry Langosta_a_la_salsa)
            (NoCompatible Arroz_con_curry Ensalada_de_arroz)
            (NoCompatible Spaghetti_a_la_bolognesa Pechuga_de_pollo)
            (NoCompatible Spaghetti_a_la_carbonara Macarrones_a_la_carbonara)
            (NoCompatible Conejo_asado Spaghetti_al_pesto)
            (NoCompatible Pato_a_la_naranja Risotto_con_gambas)
            (NoCompatible Spaghetti_a_la_bolognesa Ravioli_a_la_genovesa)
            (NoCompatible Anchoas Arroz_con_bogavantes)
            (NoCompatible Arroz_tres_delicias Costillitas_de_cordero)
            (NoCompatible Spaghetti_a_la_carbonara Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Hamburguesa_de_pollo Pulpo_a_la_feira)
            (NoCompatible Sopa_de_fideos Paella)
            (NoCompatible Rabo_de_toro Risotto_con_gambas)
            (NoCompatible Cazón Rabas_y_chocos)
            (NoCompatible Spaghetti_a_la_carbonara Spaghetti_al_pesto)
            (NoCompatible Atún_al_horno Bacalao_en_salsa_verde)
            (NoCompatible Fetuccini_a_la_putanesca Solomillo_de_cerdo)
            (NoCompatible Arroz_salteado_con_verduras Solomillo_de_cerdo)
            (NoCompatible Conejo_asado Paella)
            (NoCompatible Hamburguesa_de_pollo Pollo_a_la_brasa)
            (NoCompatible Fetuccini_a_la_putanesca Pollo_a_la_brasa)
            (NoCompatible Pato_a_la_naranja Rabas_y_chocos)
            (NoCompatible Lubina_al_limon Macarrones_a_la_carbonara)
            (NoCompatible Fetuccini_a_la_putanesca Ensalada_de_arroz)

            (tipoP Atún_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazón Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Pescado)
            (tipoS Solomillo_de_cerdo Pescado)
            (tipoP Pato_a_la_naranja Pescado)
            (tipoS Pollo_a_la_brasa Pescado)
            (tipoP Rabo_de_toro Pescado)
            (tipoS Botifarra_del_pages Pescado)
            (tipoP Entrecot_al_roquefort Pescado)
            (tipoS Costillitas_de_cordero Pescado)
            (tipoP Galtas_de_cerdo Pescado)
            (tipoS Callos Pescado)
            (tipoP Hamburguesa_de_pollo Pescado)
            (tipoS Pechuga_de_pollo Pescado)

            (tipoP Arroz_a_la_cubana Pescado)
            (tipoS Ensalada_de_arroz Pescado)
            (tipoP Cuscús Pescado)
            (tipoS Paella Pescado)
            (tipoP Arroz_con_curry Pescado)
            (tipoS Arroz_con_setas Pescado)
            (tipoP Arroz_tres_delicias Pescado)
            (tipoS Arroz_frito_con_salsa_de_cebolla Pescado)
            (tipoP Arroz_salteado_con_verduras Pescado)
            (tipoS Arroz_con_bogavantes Pescado)
            (tipoP Arroz Pescado)
            (tipoS Risotto_con_gambas Pescado)

            (tipoP Macarrones_a_la_bolognesa Pescado)
            (tipoS Macarrones_a_la_carbonara Pescado)
            (tipoP Spaghetti_a_la_bolognesa Pescado)
            (tipoS Spaghetti_al_pesto Pescado)
            (tipoP Spaghetti_a_la_carbonara Pescado)
            (tipoS Ramen Pescado)
            (tipoP Sopa_de_fideos Pescado)
            (tipoS Fideos_con_verduras Pescado)
            (tipoP Fetuccini_a_la_putanesca Pescado)
            (tipoS Ravioli_a_la_genovesa Pescado)
            (tipoP Lasaña Pescado)
            (tipoS Tallarines_con_verduras Pescado)

            (mustUse Miercoles Fetuccini_a_la_putanesca)
            (RestrictedPrimero Miercoles)

            (mustUse Lunes Costillitas_de_cordero)
            (RestrictedSegundo Lunes)
            (mustUse Miercoles Solomillo_de_cerdo)
            (RestrictedSegundo Miercoles)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atún_al_horno) 539)
            (= (Pcals Lubina_al_limon) 583)
            (= (Pcals Calamares_a_la_romana) 501)
            (= (Pcals Cazón) 669)
            (= (Pcals Anchoas) 630)
            (= (Pcals Pez_espada_y_cosas_pijas) 742)
            (= (Pcals Conejo_asado) 625)
            (= (Pcals Pato_a_la_naranja) 685)
            (= (Pcals Rabo_de_toro) 538)
            (= (Pcals Entrecot_al_roquefort) 799)
            (= (Pcals Galtas_de_cerdo) 761)
            (= (Pcals Hamburguesa_de_pollo) 594)
            (= (Pcals Arroz_a_la_cubana) 567)
            (= (Pcals Cuscús) 722)
            (= (Pcals Arroz_con_curry) 580)
            (= (Pcals Arroz_tres_delicias) 519)
            (= (Pcals Arroz_salteado_con_verduras) 697)
            (= (Pcals Arroz) 713)
            (= (Pcals Macarrones_a_la_bolognesa) 759)
            (= (Pcals Spaghetti_a_la_bolognesa) 539)
            (= (Pcals Spaghetti_a_la_carbonara) 645)
            (= (Pcals Sopa_de_fideos) 754)
            (= (Pcals Fetuccini_a_la_putanesca) 739)
            (= (Pcals Lasaña) 505)

            (= (Scals Bacalao_en_salsa_verde) 621)
            (= (Scals Bacalao_con_tomate) 683)
            (= (Scals Rabas_y_chocos) 794)
            (= (Scals Boquerones_al_vinagre) 635)
            (= (Scals Pulpo_a_la_feira) 800)
            (= (Scals Langosta_a_la_salsa) 648)
            (= (Scals Solomillo_de_cerdo) 529)
            (= (Scals Pollo_a_la_brasa) 750)
            (= (Scals Botifarra_del_pages) 767)
            (= (Scals Costillitas_de_cordero) 571)
            (= (Scals Callos) 661)
            (= (Scals Pechuga_de_pollo) 749)
            (= (Scals Ensalada_de_arroz) 557)
            (= (Scals Paella) 758)
            (= (Scals Arroz_con_setas) 792)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 694)
            (= (Scals Arroz_con_bogavantes) 725)
            (= (Scals Risotto_con_gambas) 663)
            (= (Scals Macarrones_a_la_carbonara) 624)
            (= (Scals Spaghetti_al_pesto) 758)
            (= (Scals Ramen) 525)
            (= (Scals Fideos_con_verduras) 585)
            (= (Scals Ravioli_a_la_genovesa) 519)
            (= (Scals Tallarines_con_verduras) 762)

            (= (Pprice Atún_al_horno) 14)
            (= (Pprice Lubina_al_limon) 15)
            (= (Pprice Calamares_a_la_romana) 15)
            (= (Pprice Cazón) 12)
            (= (Pprice Anchoas) 5)
            (= (Pprice Pez_espada_y_cosas_pijas) 6)
            (= (Pprice Conejo_asado) 5)
            (= (Pprice Pato_a_la_naranja) 11)
            (= (Pprice Rabo_de_toro) 13)
            (= (Pprice Entrecot_al_roquefort) 13)
            (= (Pprice Galtas_de_cerdo) 7)
            (= (Pprice Hamburguesa_de_pollo) 6)
            (= (Pprice Arroz_a_la_cubana) 6)
            (= (Pprice Cuscús) 8)
            (= (Pprice Arroz_con_curry) 6)
            (= (Pprice Arroz_tres_delicias) 6)
            (= (Pprice Arroz_salteado_con_verduras) 13)
            (= (Pprice Arroz) 5)
            (= (Pprice Macarrones_a_la_bolognesa) 13)
            (= (Pprice Spaghetti_a_la_bolognesa) 9)
            (= (Pprice Spaghetti_a_la_carbonara) 7)
            (= (Pprice Sopa_de_fideos) 9)
            (= (Pprice Fetuccini_a_la_putanesca) 6)
            (= (Pprice Lasaña) 15)

            (= (Sprice Bacalao_en_salsa_verde) 14)
            (= (Sprice Bacalao_con_tomate) 14)
            (= (Sprice Rabas_y_chocos) 8)
            (= (Sprice Boquerones_al_vinagre) 9)
            (= (Sprice Pulpo_a_la_feira) 14)
            (= (Sprice Langosta_a_la_salsa) 7)
            (= (Sprice Solomillo_de_cerdo) 10)
            (= (Sprice Pollo_a_la_brasa) 10)
            (= (Sprice Botifarra_del_pages) 9)
            (= (Sprice Costillitas_de_cordero) 10)
            (= (Sprice Callos) 15)
            (= (Sprice Pechuga_de_pollo) 5)
            (= (Sprice Ensalada_de_arroz) 5)
            (= (Sprice Paella) 12)
            (= (Sprice Arroz_con_setas) 5)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 14)
            (= (Sprice Arroz_con_bogavantes) 10)
            (= (Sprice Risotto_con_gambas) 13)
            (= (Sprice Macarrones_a_la_carbonara) 12)
            (= (Sprice Spaghetti_al_pesto) 9)
            (= (Sprice Ramen) 15)
            (= (Sprice Fideos_con_verduras) 7)
            (= (Sprice Ravioli_a_la_genovesa) 13)
            (= (Sprice Tallarines_con_verduras) 13)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)