(define (problem menus)
    (:domain catering)
    (:objects Atun_al_horno Lubina_al_limon Calamares_a_la_romana Cazon Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscus Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz_blanco Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasanya - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Otro Pasta - tipo
)
    (:init
        (primero Atun_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazon)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscus)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz_blanco)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasanya)

        (segundo Bacalao_en_salsa_verde)(segundo Bacalao_con_tomate)(segundo Rabas_y_chocos)(segundo Boquerones_al_vinagre)(segundo Pulpo_a_la_feira)(segundo Langosta_a_la_salsa)(segundo Solomillo_de_cerdo)(segundo Pollo_a_la_brasa)(segundo Botifarra_del_pages)(segundo Costillitas_de_cordero)(segundo Callos)(segundo Pechuga_de_pollo)(segundo Ensalada_de_arroz)(segundo Paella)(segundo Arroz_con_setas)(segundo Arroz_frito_con_salsa_de_cebolla)(segundo Arroz_con_bogavantes)(segundo Risotto_con_gambas)(segundo Macarrones_a_la_carbonara)(segundo Spaghetti_al_pesto)(segundo Ramen)(segundo Fideos_con_verduras)(segundo Ravioli_a_la_genovesa)(segundo Tallarines_con_verduras)

            (NoCompatible Conejo_asado Spaghetti_al_pesto)
            (NoCompatible Arroz_con_curry Pechuga_de_pollo)
            (NoCompatible Arroz_salteado_con_verduras Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_blanco Arroz_con_setas)
            (NoCompatible Conejo_asado Boquerones_al_vinagre)
            (NoCompatible Sopa_de_fideos Boquerones_al_vinagre)
            (NoCompatible Sopa_de_fideos Botifarra_del_pages)
            (NoCompatible Sopa_de_fideos Macarrones_a_la_carbonara)
            (NoCompatible Cazon Arroz_con_setas)
            (NoCompatible Lasanya Pechuga_de_pollo)
            (NoCompatible Entrecot_al_roquefort Paella)
            (NoCompatible Cuscus Ravioli_a_la_genovesa)
            (NoCompatible Anchoas Pulpo_a_la_feira)
            (NoCompatible Arroz_salteado_con_verduras Arroz_con_bogavantes)
            (NoCompatible Arroz_blanco Bacalao_en_salsa_verde)
            (NoCompatible Calamares_a_la_romana Costillitas_de_cordero)
            (NoCompatible Hamburguesa_de_pollo Spaghetti_al_pesto)
            (NoCompatible Arroz_con_curry Tallarines_con_verduras)
            (NoCompatible Lubina_al_limon Bacalao_con_tomate)
            (NoCompatible Pato_a_la_naranja Botifarra_del_pages)
            (NoCompatible Sopa_de_fideos Solomillo_de_cerdo)
            (NoCompatible Galtas_de_cerdo Pulpo_a_la_feira)
            (NoCompatible Pez_espada_y_cosas_pijas Tallarines_con_verduras)
            (NoCompatible Atun_al_horno Callos)
            (NoCompatible Galtas_de_cerdo Macarrones_a_la_carbonara)
            (NoCompatible Cazon Pulpo_a_la_feira)
            (NoCompatible Pato_a_la_naranja Callos)
            (NoCompatible Lubina_al_limon Ramen)
            (NoCompatible Fetuccini_a_la_putanesca Bacalao_en_salsa_verde)
            (NoCompatible Spaghetti_a_la_carbonara Risotto_con_gambas)
            (NoCompatible Pato_a_la_naranja Bacalao_en_salsa_verde)
            (NoCompatible Sopa_de_fideos Spaghetti_al_pesto)
            (NoCompatible Arroz_tres_delicias Fideos_con_verduras)
            (NoCompatible Macarrones_a_la_bolognesa Botifarra_del_pages)
            (NoCompatible Pez_espada_y_cosas_pijas Pechuga_de_pollo)
            (NoCompatible Lasanya Risotto_con_gambas)
            (NoCompatible Calamares_a_la_romana Tallarines_con_verduras)
            (NoCompatible Sopa_de_fideos Callos)
            (NoCompatible Hamburguesa_de_pollo Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Spaghetti_a_la_bolognesa Spaghetti_al_pesto)
            (NoCompatible Calamares_a_la_romana Langosta_a_la_salsa)
            (NoCompatible Arroz_tres_delicias Bacalao_con_tomate)
            (NoCompatible Spaghetti_a_la_carbonara Bacalao_en_salsa_verde)
            (NoCompatible Lubina_al_limon Botifarra_del_pages)
            (NoCompatible Arroz_tres_delicias Langosta_a_la_salsa)
            (NoCompatible Lasanya Costillitas_de_cordero)
            (NoCompatible Pez_espada_y_cosas_pijas Arroz_con_bogavantes)
            (NoCompatible Calamares_a_la_romana Boquerones_al_vinagre)

            (tipoP Atun_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazon Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Carne)
            (tipoS Solomillo_de_cerdo Carne)
            (tipoP Pato_a_la_naranja Carne)
            (tipoS Pollo_a_la_brasa Carne)
            (tipoP Rabo_de_toro Carne)
            (tipoS Botifarra_del_pages Carne)
            (tipoP Entrecot_al_roquefort Carne)
            (tipoS Costillitas_de_cordero Carne)
            (tipoP Galtas_de_cerdo Carne)
            (tipoS Callos Carne)
            (tipoP Hamburguesa_de_pollo Carne)
            (tipoS Pechuga_de_pollo Carne)

            (tipoP Arroz_a_la_cubana Otro)
            (tipoS Ensalada_de_arroz Otro)
            (tipoP Cuscus Otro)
            (tipoS Paella Otro)
            (tipoP Arroz_con_curry Otro)
            (tipoS Arroz_con_setas Otro)
            (tipoP Arroz_tres_delicias Otro)
            (tipoS Arroz_frito_con_salsa_de_cebolla Otro)
            (tipoP Arroz_salteado_con_verduras Otro)
            (tipoS Arroz_con_bogavantes Otro)
            (tipoP Arroz_blanco Otro)
            (tipoS Risotto_con_gambas Otro)

            (tipoP Macarrones_a_la_bolognesa Pasta)
            (tipoS Macarrones_a_la_carbonara Pasta)
            (tipoP Spaghetti_a_la_bolognesa Pasta)
            (tipoS Spaghetti_al_pesto Pasta)
            (tipoP Spaghetti_a_la_carbonara Pasta)
            (tipoS Ramen Pasta)
            (tipoP Sopa_de_fideos Pasta)
            (tipoS Fideos_con_verduras Pasta)
            (tipoP Fetuccini_a_la_putanesca Pasta)
            (tipoS Ravioli_a_la_genovesa Pasta)
            (tipoP Lasanya Pasta)
            (tipoS Tallarines_con_verduras Pasta)

            (mustUse Miercoles Entrecot_al_roquefort)
            (RestrictedPrimero Miercoles)
            (mustUse Lunes Conejo_asado)
            (RestrictedPrimero Lunes)

            (mustUse Lunes Paella)
            (RestrictedSegundo Lunes)
            (mustUse Miercoles Pechuga_de_pollo)
            (RestrictedSegundo Miercoles)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atun_al_horno) 522)
            (= (Pcals Lubina_al_limon) 526)
            (= (Pcals Calamares_a_la_romana) 773)
            (= (Pcals Cazon) 769)
            (= (Pcals Anchoas) 785)
            (= (Pcals Pez_espada_y_cosas_pijas) 756)
            (= (Pcals Conejo_asado) 538)
            (= (Pcals Pato_a_la_naranja) 796)
            (= (Pcals Rabo_de_toro) 565)
            (= (Pcals Entrecot_al_roquefort) 735)
            (= (Pcals Galtas_de_cerdo) 616)
            (= (Pcals Hamburguesa_de_pollo) 601)
            (= (Pcals Arroz_a_la_cubana) 677)
            (= (Pcals Cuscus) 582)
            (= (Pcals Arroz_con_curry) 532)
            (= (Pcals Arroz_tres_delicias) 564)
            (= (Pcals Arroz_salteado_con_verduras) 567)
            (= (Pcals Arroz_blanco) 620)
            (= (Pcals Macarrones_a_la_bolognesa) 718)
            (= (Pcals Spaghetti_a_la_bolognesa) 788)
            (= (Pcals Spaghetti_a_la_carbonara) 799)
            (= (Pcals Sopa_de_fideos) 726)
            (= (Pcals Fetuccini_a_la_putanesca) 608)
            (= (Pcals Lasanya) 765)

            (= (Scals Bacalao_en_salsa_verde) 668)
            (= (Scals Bacalao_con_tomate) 679)
            (= (Scals Rabas_y_chocos) 649)
            (= (Scals Boquerones_al_vinagre) 700)
            (= (Scals Pulpo_a_la_feira) 501)
            (= (Scals Langosta_a_la_salsa) 675)
            (= (Scals Solomillo_de_cerdo) 679)
            (= (Scals Pollo_a_la_brasa) 538)
            (= (Scals Botifarra_del_pages) 624)
            (= (Scals Costillitas_de_cordero) 752)
            (= (Scals Callos) 632)
            (= (Scals Pechuga_de_pollo) 662)
            (= (Scals Ensalada_de_arroz) 574)
            (= (Scals Paella) 699)
            (= (Scals Arroz_con_setas) 644)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 671)
            (= (Scals Arroz_con_bogavantes) 607)
            (= (Scals Risotto_con_gambas) 533)
            (= (Scals Macarrones_a_la_carbonara) 634)
            (= (Scals Spaghetti_al_pesto) 778)
            (= (Scals Ramen) 738)
            (= (Scals Fideos_con_verduras) 723)
            (= (Scals Ravioli_a_la_genovesa) 658)
            (= (Scals Tallarines_con_verduras) 776)

            (= (Pprice Atun_al_horno) 10)
            (= (Pprice Lubina_al_limon) 6)
            (= (Pprice Calamares_a_la_romana) 11)
            (= (Pprice Cazon) 5)
            (= (Pprice Anchoas) 11)
            (= (Pprice Pez_espada_y_cosas_pijas) 13)
            (= (Pprice Conejo_asado) 11)
            (= (Pprice Pato_a_la_naranja) 6)
            (= (Pprice Rabo_de_toro) 12)
            (= (Pprice Entrecot_al_roquefort) 9)
            (= (Pprice Galtas_de_cerdo) 6)
            (= (Pprice Hamburguesa_de_pollo) 13)
            (= (Pprice Arroz_a_la_cubana) 8)
            (= (Pprice Cuscus) 6)
            (= (Pprice Arroz_con_curry) 5)
            (= (Pprice Arroz_tres_delicias) 14)
            (= (Pprice Arroz_salteado_con_verduras) 9)
            (= (Pprice Arroz_blanco) 10)
            (= (Pprice Macarrones_a_la_bolognesa) 6)
            (= (Pprice Spaghetti_a_la_bolognesa) 15)
            (= (Pprice Spaghetti_a_la_carbonara) 13)
            (= (Pprice Sopa_de_fideos) 10)
            (= (Pprice Fetuccini_a_la_putanesca) 5)
            (= (Pprice Lasanya) 14)

            (= (Sprice Bacalao_en_salsa_verde) 8)
            (= (Sprice Bacalao_con_tomate) 11)
            (= (Sprice Rabas_y_chocos) 8)
            (= (Sprice Boquerones_al_vinagre) 12)
            (= (Sprice Pulpo_a_la_feira) 10)
            (= (Sprice Langosta_a_la_salsa) 7)
            (= (Sprice Solomillo_de_cerdo) 6)
            (= (Sprice Pollo_a_la_brasa) 14)
            (= (Sprice Botifarra_del_pages) 12)
            (= (Sprice Costillitas_de_cordero) 12)
            (= (Sprice Callos) 13)
            (= (Sprice Pechuga_de_pollo) 13)
            (= (Sprice Ensalada_de_arroz) 10)
            (= (Sprice Paella) 13)
            (= (Sprice Arroz_con_setas) 15)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 6)
            (= (Sprice Arroz_con_bogavantes) 11)
            (= (Sprice Risotto_con_gambas) 13)
            (= (Sprice Macarrones_a_la_carbonara) 12)
            (= (Sprice Spaghetti_al_pesto) 14)
            (= (Sprice Ramen) 6)
            (= (Sprice Fideos_con_verduras) 14)
            (= (Sprice Ravioli_a_la_genovesa) 9)
            (= (Sprice Tallarines_con_verduras) 7)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)