(define (problem menus)
    (:domain catering)
    (:objects Atun_al_horno Lubina_al_limon Calamares_a_la_romana Cazon Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscus Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz_blanco Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasanya - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Otro Pasta - tipo
)
    (:init
        (primero Atun_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazon)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscus)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz_blanco)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasanya)

        (segundo Bacalao_en_salsa_verde)(segundo Bacalao_con_tomate)(segundo Rabas_y_chocos)(segundo Boquerones_al_vinagre)(segundo Pulpo_a_la_feira)(segundo Langosta_a_la_salsa)(segundo Solomillo_de_cerdo)(segundo Pollo_a_la_brasa)(segundo Botifarra_del_pages)(segundo Costillitas_de_cordero)(segundo Callos)(segundo Pechuga_de_pollo)(segundo Ensalada_de_arroz)(segundo Paella)(segundo Arroz_con_setas)(segundo Arroz_frito_con_salsa_de_cebolla)(segundo Arroz_con_bogavantes)(segundo Risotto_con_gambas)(segundo Macarrones_a_la_carbonara)(segundo Spaghetti_al_pesto)(segundo Ramen)(segundo Fideos_con_verduras)(segundo Ravioli_a_la_genovesa)(segundo Tallarines_con_verduras)

            (NoCompatible Pez_espada_y_cosas_pijas Pollo_a_la_brasa)
            (NoCompatible Spaghetti_a_la_bolognesa Paella)
            (NoCompatible Pez_espada_y_cosas_pijas Tallarines_con_verduras)
            (NoCompatible Spaghetti_a_la_carbonara Pechuga_de_pollo)
            (NoCompatible Lasanya Ramen)
            (NoCompatible Anchoas Ravioli_a_la_genovesa)
            (NoCompatible Pez_espada_y_cosas_pijas Spaghetti_al_pesto)
            (NoCompatible Galtas_de_cerdo Costillitas_de_cordero)
            (NoCompatible Atun_al_horno Pollo_a_la_brasa)
            (NoCompatible Macarrones_a_la_bolognesa Risotto_con_gambas)
            (NoCompatible Lubina_al_limon Rabas_y_chocos)
            (NoCompatible Pez_espada_y_cosas_pijas Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_tres_delicias Arroz_con_setas)
            (NoCompatible Fetuccini_a_la_putanesca Botifarra_del_pages)
            (NoCompatible Hamburguesa_de_pollo Arroz_con_bogavantes)
            (NoCompatible Conejo_asado Bacalao_con_tomate)
            (NoCompatible Lasanya Callos)
            (NoCompatible Spaghetti_a_la_bolognesa Pollo_a_la_brasa)
            (NoCompatible Conejo_asado Solomillo_de_cerdo)
            (NoCompatible Pato_a_la_naranja Boquerones_al_vinagre)
            (NoCompatible Hamburguesa_de_pollo Bacalao_en_salsa_verde)
            (NoCompatible Arroz_blanco Arroz_con_setas)
            (NoCompatible Pato_a_la_naranja Costillitas_de_cordero)
            (NoCompatible Conejo_asado Spaghetti_al_pesto)
            (NoCompatible Cuscus Rabas_y_chocos)
            (NoCompatible Cazon Arroz_con_bogavantes)
            (NoCompatible Anchoas Ensalada_de_arroz)
            (NoCompatible Rabo_de_toro Macarrones_a_la_carbonara)
            (NoCompatible Arroz_a_la_cubana Tallarines_con_verduras)
            (NoCompatible Sopa_de_fideos Tallarines_con_verduras)
            (NoCompatible Arroz_con_curry Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Anchoas Boquerones_al_vinagre)
            (NoCompatible Arroz_salteado_con_verduras Ravioli_a_la_genovesa)
            (NoCompatible Cuscus Fideos_con_verduras)
            (NoCompatible Arroz_con_curry Callos)
            (NoCompatible Cuscus Tallarines_con_verduras)
            (NoCompatible Rabo_de_toro Solomillo_de_cerdo)
            (NoCompatible Arroz_con_curry Paella)
            (NoCompatible Calamares_a_la_romana Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Atun_al_horno Ravioli_a_la_genovesa)
            (NoCompatible Fetuccini_a_la_putanesca Arroz_con_bogavantes)
            (NoCompatible Pato_a_la_naranja Bacalao_en_salsa_verde)
            (NoCompatible Arroz_salteado_con_verduras Rabas_y_chocos)
            (NoCompatible Spaghetti_a_la_carbonara Botifarra_del_pages)
            (NoCompatible Pato_a_la_naranja Bacalao_con_tomate)
            (NoCompatible Cazon Arroz_con_setas)
            (NoCompatible Hamburguesa_de_pollo Pollo_a_la_brasa)
            (NoCompatible Pez_espada_y_cosas_pijas Bacalao_en_salsa_verde)

            (tipoP Atun_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazon Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Carne)
            (tipoS Solomillo_de_cerdo Carne)
            (tipoP Pato_a_la_naranja Carne)
            (tipoS Pollo_a_la_brasa Carne)
            (tipoP Rabo_de_toro Carne)
            (tipoS Botifarra_del_pages Carne)
            (tipoP Entrecot_al_roquefort Carne)
            (tipoS Costillitas_de_cordero Carne)
            (tipoP Galtas_de_cerdo Carne)
            (tipoS Callos Carne)
            (tipoP Hamburguesa_de_pollo Carne)
            (tipoS Pechuga_de_pollo Carne)

            (tipoP Arroz_a_la_cubana Otro)
            (tipoS Ensalada_de_arroz Otro)
            (tipoP Cuscus Otro)
            (tipoS Paella Otro)
            (tipoP Arroz_con_curry Otro)
            (tipoS Arroz_con_setas Otro)
            (tipoP Arroz_tres_delicias Otro)
            (tipoS Arroz_frito_con_salsa_de_cebolla Otro)
            (tipoP Arroz_salteado_con_verduras Otro)
            (tipoS Arroz_con_bogavantes Otro)
            (tipoP Arroz_blanco Otro)
            (tipoS Risotto_con_gambas Otro)

            (tipoP Macarrones_a_la_bolognesa Pasta)
            (tipoS Macarrones_a_la_carbonara Pasta)
            (tipoP Spaghetti_a_la_bolognesa Pasta)
            (tipoS Spaghetti_al_pesto Pasta)
            (tipoP Spaghetti_a_la_carbonara Pasta)
            (tipoS Ramen Pasta)
            (tipoP Sopa_de_fideos Pasta)
            (tipoS Fideos_con_verduras Pasta)
            (tipoP Fetuccini_a_la_putanesca Pasta)
            (tipoS Ravioli_a_la_genovesa Pasta)
            (tipoP Lasanya Pasta)
            (tipoS Tallarines_con_verduras Pasta)

            (mustUse Lunes Arroz_tres_delicias)
            (RestrictedPrimero Lunes)

            (mustUse Jueves Spaghetti_al_pesto)
            (RestrictedSegundo Jueves)
            (mustUse Lunes Boquerones_al_vinagre)
            (RestrictedSegundo Lunes)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atun_al_horno) 518)
            (= (Pcals Lubina_al_limon) 679)
            (= (Pcals Calamares_a_la_romana) 792)
            (= (Pcals Cazon) 507)
            (= (Pcals Anchoas) 766)
            (= (Pcals Pez_espada_y_cosas_pijas) 743)
            (= (Pcals Conejo_asado) 778)
            (= (Pcals Pato_a_la_naranja) 599)
            (= (Pcals Rabo_de_toro) 594)
            (= (Pcals Entrecot_al_roquefort) 657)
            (= (Pcals Galtas_de_cerdo) 586)
            (= (Pcals Hamburguesa_de_pollo) 590)
            (= (Pcals Arroz_a_la_cubana) 579)
            (= (Pcals Cuscus) 744)
            (= (Pcals Arroz_con_curry) 697)
            (= (Pcals Arroz_tres_delicias) 797)
            (= (Pcals Arroz_salteado_con_verduras) 686)
            (= (Pcals Arroz_blanco) 785)
            (= (Pcals Macarrones_a_la_bolognesa) 786)
            (= (Pcals Spaghetti_a_la_bolognesa) 759)
            (= (Pcals Spaghetti_a_la_carbonara) 711)
            (= (Pcals Sopa_de_fideos) 613)
            (= (Pcals Fetuccini_a_la_putanesca) 554)
            (= (Pcals Lasanya) 510)

            (= (Scals Bacalao_en_salsa_verde) 712)
            (= (Scals Bacalao_con_tomate) 778)
            (= (Scals Rabas_y_chocos) 644)
            (= (Scals Boquerones_al_vinagre) 599)
            (= (Scals Pulpo_a_la_feira) 620)
            (= (Scals Langosta_a_la_salsa) 618)
            (= (Scals Solomillo_de_cerdo) 729)
            (= (Scals Pollo_a_la_brasa) 674)
            (= (Scals Botifarra_del_pages) 727)
            (= (Scals Costillitas_de_cordero) 736)
            (= (Scals Callos) 762)
            (= (Scals Pechuga_de_pollo) 682)
            (= (Scals Ensalada_de_arroz) 545)
            (= (Scals Paella) 597)
            (= (Scals Arroz_con_setas) 583)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 566)
            (= (Scals Arroz_con_bogavantes) 578)
            (= (Scals Risotto_con_gambas) 506)
            (= (Scals Macarrones_a_la_carbonara) 611)
            (= (Scals Spaghetti_al_pesto) 754)
            (= (Scals Ramen) 699)
            (= (Scals Fideos_con_verduras) 759)
            (= (Scals Ravioli_a_la_genovesa) 720)
            (= (Scals Tallarines_con_verduras) 638)

            (= (Pprice Atun_al_horno) 14)
            (= (Pprice Lubina_al_limon) 14)
            (= (Pprice Calamares_a_la_romana) 7)
            (= (Pprice Cazon) 10)
            (= (Pprice Anchoas) 13)
            (= (Pprice Pez_espada_y_cosas_pijas) 15)
            (= (Pprice Conejo_asado) 7)
            (= (Pprice Pato_a_la_naranja) 13)
            (= (Pprice Rabo_de_toro) 15)
            (= (Pprice Entrecot_al_roquefort) 8)
            (= (Pprice Galtas_de_cerdo) 6)
            (= (Pprice Hamburguesa_de_pollo) 5)
            (= (Pprice Arroz_a_la_cubana) 11)
            (= (Pprice Cuscus) 8)
            (= (Pprice Arroz_con_curry) 14)
            (= (Pprice Arroz_tres_delicias) 6)
            (= (Pprice Arroz_salteado_con_verduras) 12)
            (= (Pprice Arroz_blanco) 7)
            (= (Pprice Macarrones_a_la_bolognesa) 10)
            (= (Pprice Spaghetti_a_la_bolognesa) 9)
            (= (Pprice Spaghetti_a_la_carbonara) 6)
            (= (Pprice Sopa_de_fideos) 6)
            (= (Pprice Fetuccini_a_la_putanesca) 15)
            (= (Pprice Lasanya) 6)

            (= (Sprice Bacalao_en_salsa_verde) 12)
            (= (Sprice Bacalao_con_tomate) 14)
            (= (Sprice Rabas_y_chocos) 13)
            (= (Sprice Boquerones_al_vinagre) 7)
            (= (Sprice Pulpo_a_la_feira) 15)
            (= (Sprice Langosta_a_la_salsa) 15)
            (= (Sprice Solomillo_de_cerdo) 6)
            (= (Sprice Pollo_a_la_brasa) 15)
            (= (Sprice Botifarra_del_pages) 13)
            (= (Sprice Costillitas_de_cordero) 6)
            (= (Sprice Callos) 5)
            (= (Sprice Pechuga_de_pollo) 13)
            (= (Sprice Ensalada_de_arroz) 10)
            (= (Sprice Paella) 14)
            (= (Sprice Arroz_con_setas) 12)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 7)
            (= (Sprice Arroz_con_bogavantes) 10)
            (= (Sprice Risotto_con_gambas) 13)
            (= (Sprice Macarrones_a_la_carbonara) 10)
            (= (Sprice Spaghetti_al_pesto) 15)
            (= (Sprice Ramen) 6)
            (= (Sprice Fideos_con_verduras) 6)
            (= (Sprice Ravioli_a_la_genovesa) 6)
            (= (Sprice Tallarines_con_verduras) 14)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)