(define (problem menus)
    (:domain catering)
    (:objects Atún_al_horno Lubina_al_limon Calamares_a_la_romana Cazón Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscús Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasaña - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Arroz Pasta - tipo
)
    (:init
        (primero Atún_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazón)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscús)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasaña)

        (Segundo Bacalao_en_salsa_verde)(Segundo Bacalao_con_tomate)(Segundo Rabas_y_chocos)(Segundo Boquerones_al_vinagre)(Segundo Pulpo_a_la_feira)(Segundo Langosta_a_la_salsa)(Segundo Solomillo_de_cerdo)(Segundo Pollo_a_la_brasa)(Segundo Botifarra_del_pages)(Segundo Costillitas_de_cordero)(Segundo Callos)(Segundo Pechuga_de_pollo)(Segundo Ensalada_de_arroz)(Segundo Paella)(Segundo Arroz_con_setas)(Segundo Arroz_frito_con_salsa_de_cebolla)(Segundo Arroz_con_bogavantes)(Segundo Risotto_con_gambas)(Segundo Macarrones_a_la_carbonara)(Segundo Spaghetti_al_pesto)(Segundo Ramen)(Segundo Fideos_con_verduras)(Segundo Ravioli_a_la_genovesa)(Segundo Tallarines_con_verduras)

            (NoCompatible Spaghetti_a_la_bolognesa Arroz_con_setas)
            (NoCompatible Spaghetti_a_la_carbonara Botifarra_del_pages)
            (NoCompatible Cazón Spaghetti_al_pesto)
            (NoCompatible Spaghetti_a_la_carbonara Pulpo_a_la_feira)
            (NoCompatible Cuscús Spaghetti_al_pesto)
            (NoCompatible Spaghetti_a_la_carbonara Ravioli_a_la_genovesa)
            (NoCompatible Fetuccini_a_la_putanesca Callos)
            (NoCompatible Arroz_con_curry Bacalao_con_tomate)
            (NoCompatible Fetuccini_a_la_putanesca Ramen)
            (NoCompatible Calamares_a_la_romana Costillitas_de_cordero)
            (NoCompatible Fetuccini_a_la_putanesca Pechuga_de_pollo)
            (NoCompatible Macarrones_a_la_bolognesa Costillitas_de_cordero)
            (NoCompatible Arroz_a_la_cubana Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Cuscús Bacalao_en_salsa_verde)
            (NoCompatible Arroz_con_curry Ravioli_a_la_genovesa)
            (NoCompatible Macarrones_a_la_bolognesa Risotto_con_gambas)
            (NoCompatible Lubina_al_limon Rabas_y_chocos)
            (NoCompatible Galtas_de_cerdo Ravioli_a_la_genovesa)
            (NoCompatible Lubina_al_limon Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Entrecot_al_roquefort Botifarra_del_pages)
            (NoCompatible Fetuccini_a_la_putanesca Botifarra_del_pages)
            (NoCompatible Arroz_salteado_con_verduras Arroz_con_bogavantes)
            (NoCompatible Calamares_a_la_romana Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Calamares_a_la_romana Callos)
            (NoCompatible Anchoas Tallarines_con_verduras)
            (NoCompatible Atún_al_horno Costillitas_de_cordero)
            (NoCompatible Entrecot_al_roquefort Langosta_a_la_salsa)
            (NoCompatible Pato_a_la_naranja Spaghetti_al_pesto)
            (NoCompatible Arroz_a_la_cubana Ramen)
            (NoCompatible Spaghetti_a_la_bolognesa Macarrones_a_la_carbonara)
            (NoCompatible Lubina_al_limon Spaghetti_al_pesto)
            (NoCompatible Arroz_salteado_con_verduras Fideos_con_verduras)
            (NoCompatible Hamburguesa_de_pollo Spaghetti_al_pesto)
            (NoCompatible Pato_a_la_naranja Macarrones_a_la_carbonara)
            (NoCompatible Macarrones_a_la_bolognesa Callos)
            (NoCompatible Entrecot_al_roquefort Ensalada_de_arroz)
            (NoCompatible Lubina_al_limon Pechuga_de_pollo)
            (NoCompatible Hamburguesa_de_pollo Pechuga_de_pollo)
            (NoCompatible Conejo_asado Callos)
            (NoCompatible Macarrones_a_la_bolognesa Bacalao_en_salsa_verde)
            (NoCompatible Spaghetti_a_la_carbonara Ensalada_de_arroz)
            (NoCompatible Sopa_de_fideos Arroz_con_setas)
            (NoCompatible Arroz_tres_delicias Callos)
            (NoCompatible Fetuccini_a_la_putanesca Rabas_y_chocos)
            (NoCompatible Hamburguesa_de_pollo Solomillo_de_cerdo)
            (NoCompatible Entrecot_al_roquefort Ramen)
            (NoCompatible Spaghetti_a_la_carbonara Arroz_con_setas)
            (NoCompatible Galtas_de_cerdo Botifarra_del_pages)

            (tipoP Atún_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazón Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Pescado)
            (tipoS Solomillo_de_cerdo Pescado)
            (tipoP Pato_a_la_naranja Pescado)
            (tipoS Pollo_a_la_brasa Pescado)
            (tipoP Rabo_de_toro Pescado)
            (tipoS Botifarra_del_pages Pescado)
            (tipoP Entrecot_al_roquefort Pescado)
            (tipoS Costillitas_de_cordero Pescado)
            (tipoP Galtas_de_cerdo Pescado)
            (tipoS Callos Pescado)
            (tipoP Hamburguesa_de_pollo Pescado)
            (tipoS Pechuga_de_pollo Pescado)

            (tipoP Arroz_a_la_cubana Pescado)
            (tipoS Ensalada_de_arroz Pescado)
            (tipoP Cuscús Pescado)
            (tipoS Paella Pescado)
            (tipoP Arroz_con_curry Pescado)
            (tipoS Arroz_con_setas Pescado)
            (tipoP Arroz_tres_delicias Pescado)
            (tipoS Arroz_frito_con_salsa_de_cebolla Pescado)
            (tipoP Arroz_salteado_con_verduras Pescado)
            (tipoS Arroz_con_bogavantes Pescado)
            (tipoP Arroz Pescado)
            (tipoS Risotto_con_gambas Pescado)

            (tipoP Macarrones_a_la_bolognesa Pescado)
            (tipoS Macarrones_a_la_carbonara Pescado)
            (tipoP Spaghetti_a_la_bolognesa Pescado)
            (tipoS Spaghetti_al_pesto Pescado)
            (tipoP Spaghetti_a_la_carbonara Pescado)
            (tipoS Ramen Pescado)
            (tipoP Sopa_de_fideos Pescado)
            (tipoS Fideos_con_verduras Pescado)
            (tipoP Fetuccini_a_la_putanesca Pescado)
            (tipoS Ravioli_a_la_genovesa Pescado)
            (tipoP Lasaña Pescado)
            (tipoS Tallarines_con_verduras Pescado)

            (mustUse Viernes Sopa_de_fideos)
            (RestrictedPrimero Viernes)
            (mustUse Jueves Spaghetti_a_la_carbonara)
            (RestrictedPrimero Jueves)

            (mustUse Miercoles Ravioli_a_la_genovesa)
            (RestrictedSegundo Miercoles)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atún_al_horno) 715)
            (= (Pcals Lubina_al_limon) 661)
            (= (Pcals Calamares_a_la_romana) 742)
            (= (Pcals Cazón) 702)
            (= (Pcals Anchoas) 694)
            (= (Pcals Pez_espada_y_cosas_pijas) 780)
            (= (Pcals Conejo_asado) 565)
            (= (Pcals Pato_a_la_naranja) 612)
            (= (Pcals Rabo_de_toro) 607)
            (= (Pcals Entrecot_al_roquefort) 529)
            (= (Pcals Galtas_de_cerdo) 721)
            (= (Pcals Hamburguesa_de_pollo) 757)
            (= (Pcals Arroz_a_la_cubana) 674)
            (= (Pcals Cuscús) 759)
            (= (Pcals Arroz_con_curry) 699)
            (= (Pcals Arroz_tres_delicias) 615)
            (= (Pcals Arroz_salteado_con_verduras) 551)
            (= (Pcals Arroz) 641)
            (= (Pcals Macarrones_a_la_bolognesa) 690)
            (= (Pcals Spaghetti_a_la_bolognesa) 707)
            (= (Pcals Spaghetti_a_la_carbonara) 638)
            (= (Pcals Sopa_de_fideos) 626)
            (= (Pcals Fetuccini_a_la_putanesca) 662)
            (= (Pcals Lasaña) 513)

            (= (Scals Bacalao_en_salsa_verde) 649)
            (= (Scals Bacalao_con_tomate) 652)
            (= (Scals Rabas_y_chocos) 709)
            (= (Scals Boquerones_al_vinagre) 662)
            (= (Scals Pulpo_a_la_feira) 579)
            (= (Scals Langosta_a_la_salsa) 551)
            (= (Scals Solomillo_de_cerdo) 759)
            (= (Scals Pollo_a_la_brasa) 633)
            (= (Scals Botifarra_del_pages) 603)
            (= (Scals Costillitas_de_cordero) 617)
            (= (Scals Callos) 535)
            (= (Scals Pechuga_de_pollo) 795)
            (= (Scals Ensalada_de_arroz) 574)
            (= (Scals Paella) 588)
            (= (Scals Arroz_con_setas) 568)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 655)
            (= (Scals Arroz_con_bogavantes) 656)
            (= (Scals Risotto_con_gambas) 595)
            (= (Scals Macarrones_a_la_carbonara) 591)
            (= (Scals Spaghetti_al_pesto) 657)
            (= (Scals Ramen) 601)
            (= (Scals Fideos_con_verduras) 769)
            (= (Scals Ravioli_a_la_genovesa) 721)
            (= (Scals Tallarines_con_verduras) 668)

            (= (Pprice Atún_al_horno) 14)
            (= (Pprice Lubina_al_limon) 12)
            (= (Pprice Calamares_a_la_romana) 14)
            (= (Pprice Cazón) 10)
            (= (Pprice Anchoas) 6)
            (= (Pprice Pez_espada_y_cosas_pijas) 10)
            (= (Pprice Conejo_asado) 9)
            (= (Pprice Pato_a_la_naranja) 12)
            (= (Pprice Rabo_de_toro) 12)
            (= (Pprice Entrecot_al_roquefort) 6)
            (= (Pprice Galtas_de_cerdo) 9)
            (= (Pprice Hamburguesa_de_pollo) 11)
            (= (Pprice Arroz_a_la_cubana) 8)
            (= (Pprice Cuscús) 14)
            (= (Pprice Arroz_con_curry) 5)
            (= (Pprice Arroz_tres_delicias) 7)
            (= (Pprice Arroz_salteado_con_verduras) 10)
            (= (Pprice Arroz) 7)
            (= (Pprice Macarrones_a_la_bolognesa) 10)
            (= (Pprice Spaghetti_a_la_bolognesa) 7)
            (= (Pprice Spaghetti_a_la_carbonara) 12)
            (= (Pprice Sopa_de_fideos) 5)
            (= (Pprice Fetuccini_a_la_putanesca) 15)
            (= (Pprice Lasaña) 15)

            (= (Sprice Bacalao_en_salsa_verde) 12)
            (= (Sprice Bacalao_con_tomate) 7)
            (= (Sprice Rabas_y_chocos) 14)
            (= (Sprice Boquerones_al_vinagre) 13)
            (= (Sprice Pulpo_a_la_feira) 9)
            (= (Sprice Langosta_a_la_salsa) 14)
            (= (Sprice Solomillo_de_cerdo) 6)
            (= (Sprice Pollo_a_la_brasa) 9)
            (= (Sprice Botifarra_del_pages) 6)
            (= (Sprice Costillitas_de_cordero) 7)
            (= (Sprice Callos) 9)
            (= (Sprice Pechuga_de_pollo) 15)
            (= (Sprice Ensalada_de_arroz) 8)
            (= (Sprice Paella) 10)
            (= (Sprice Arroz_con_setas) 7)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 13)
            (= (Sprice Arroz_con_bogavantes) 13)
            (= (Sprice Risotto_con_gambas) 7)
            (= (Sprice Macarrones_a_la_carbonara) 14)
            (= (Sprice Spaghetti_al_pesto) 7)
            (= (Sprice Ramen) 7)
            (= (Sprice Fideos_con_verduras) 5)
            (= (Sprice Ravioli_a_la_genovesa) 13)
            (= (Sprice Tallarines_con_verduras) 15)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)