(define (problem menus)
    (:domain catering)
    (:objects Atún_al_horno Lubina_al_limon Calamares_a_la_romana Cazón Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscús Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasaña - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Arroz Pasta - tipo
)
    (:init
        (primero Atún_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazón)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscús)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasaña)

        (Segundo Bacalao_en_salsa_verde)(Segundo Bacalao_con_tomate)(Segundo Rabas_y_chocos)(Segundo Boquerones_al_vinagre)(Segundo Pulpo_a_la_feira)(Segundo Langosta_a_la_salsa)(Segundo Solomillo_de_cerdo)(Segundo Pollo_a_la_brasa)(Segundo Botifarra_del_pages)(Segundo Costillitas_de_cordero)(Segundo Callos)(Segundo Pechuga_de_pollo)(Segundo Ensalada_de_arroz)(Segundo Paella)(Segundo Arroz_con_setas)(Segundo Arroz_frito_con_salsa_de_cebolla)(Segundo Arroz_con_bogavantes)(Segundo Risotto_con_gambas)(Segundo Macarrones_a_la_carbonara)(Segundo Spaghetti_al_pesto)(Segundo Ramen)(Segundo Fideos_con_verduras)(Segundo Ravioli_a_la_genovesa)(Segundo Tallarines_con_verduras)

            (NoCompatible Spaghetti_a_la_bolognesa Ensalada_de_arroz)
            (NoCompatible Anchoas Callos)
            (NoCompatible Anchoas Boquerones_al_vinagre)
            (NoCompatible Galtas_de_cerdo Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Atún_al_horno Risotto_con_gambas)
            (NoCompatible Pato_a_la_naranja Pollo_a_la_brasa)
            (NoCompatible Sopa_de_fideos Pollo_a_la_brasa)
            (NoCompatible Pez_espada_y_cosas_pijas Rabas_y_chocos)
            (NoCompatible Sopa_de_fideos Callos)
            (NoCompatible Calamares_a_la_romana Pulpo_a_la_feira)
            (NoCompatible Lasaña Arroz_con_setas)
            (NoCompatible Calamares_a_la_romana Pechuga_de_pollo)
            (NoCompatible Spaghetti_a_la_bolognesa Paella)
            (NoCompatible Pez_espada_y_cosas_pijas Ravioli_a_la_genovesa)
            (NoCompatible Arroz Ensalada_de_arroz)
            (NoCompatible Sopa_de_fideos Tallarines_con_verduras)
            (NoCompatible Rabo_de_toro Boquerones_al_vinagre)
            (NoCompatible Rabo_de_toro Ravioli_a_la_genovesa)
            (NoCompatible Anchoas Macarrones_a_la_carbonara)
            (NoCompatible Spaghetti_a_la_bolognesa Arroz_con_bogavantes)
            (NoCompatible Galtas_de_cerdo Bacalao_con_tomate)
            (NoCompatible Spaghetti_a_la_carbonara Arroz_con_setas)
            (NoCompatible Lasaña Boquerones_al_vinagre)
            (NoCompatible Fetuccini_a_la_putanesca Bacalao_con_tomate)
            (NoCompatible Cuscús Costillitas_de_cordero)
            (NoCompatible Anchoas Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Entrecot_al_roquefort Macarrones_a_la_carbonara)
            (NoCompatible Cazón Paella)
            (NoCompatible Arroz_a_la_cubana Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz Callos)
            (NoCompatible Arroz_a_la_cubana Ravioli_a_la_genovesa)
            (NoCompatible Spaghetti_a_la_carbonara Ravioli_a_la_genovesa)
            (NoCompatible Rabo_de_toro Fideos_con_verduras)
            (NoCompatible Entrecot_al_roquefort Pulpo_a_la_feira)
            (NoCompatible Hamburguesa_de_pollo Pechuga_de_pollo)
            (NoCompatible Galtas_de_cerdo Fideos_con_verduras)
            (NoCompatible Rabo_de_toro Arroz_con_setas)
            (NoCompatible Rabo_de_toro Pollo_a_la_brasa)
            (NoCompatible Macarrones_a_la_bolognesa Botifarra_del_pages)
            (NoCompatible Pez_espada_y_cosas_pijas Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Galtas_de_cerdo Ensalada_de_arroz)
            (NoCompatible Lasaña Bacalao_con_tomate)
            (NoCompatible Galtas_de_cerdo Bacalao_en_salsa_verde)
            (NoCompatible Calamares_a_la_romana Bacalao_con_tomate)
            (NoCompatible Arroz_con_curry Pechuga_de_pollo)
            (NoCompatible Entrecot_al_roquefort Arroz_con_bogavantes)
            (NoCompatible Conejo_asado Bacalao_con_tomate)
            (NoCompatible Pez_espada_y_cosas_pijas Solomillo_de_cerdo)

            (tipoP Atún_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazón Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Pescado)
            (tipoS Solomillo_de_cerdo Pescado)
            (tipoP Pato_a_la_naranja Pescado)
            (tipoS Pollo_a_la_brasa Pescado)
            (tipoP Rabo_de_toro Pescado)
            (tipoS Botifarra_del_pages Pescado)
            (tipoP Entrecot_al_roquefort Pescado)
            (tipoS Costillitas_de_cordero Pescado)
            (tipoP Galtas_de_cerdo Pescado)
            (tipoS Callos Pescado)
            (tipoP Hamburguesa_de_pollo Pescado)
            (tipoS Pechuga_de_pollo Pescado)

            (tipoP Arroz_a_la_cubana Pescado)
            (tipoS Ensalada_de_arroz Pescado)
            (tipoP Cuscús Pescado)
            (tipoS Paella Pescado)
            (tipoP Arroz_con_curry Pescado)
            (tipoS Arroz_con_setas Pescado)
            (tipoP Arroz_tres_delicias Pescado)
            (tipoS Arroz_frito_con_salsa_de_cebolla Pescado)
            (tipoP Arroz_salteado_con_verduras Pescado)
            (tipoS Arroz_con_bogavantes Pescado)
            (tipoP Arroz Pescado)
            (tipoS Risotto_con_gambas Pescado)

            (tipoP Macarrones_a_la_bolognesa Pescado)
            (tipoS Macarrones_a_la_carbonara Pescado)
            (tipoP Spaghetti_a_la_bolognesa Pescado)
            (tipoS Spaghetti_al_pesto Pescado)
            (tipoP Spaghetti_a_la_carbonara Pescado)
            (tipoS Ramen Pescado)
            (tipoP Sopa_de_fideos Pescado)
            (tipoS Fideos_con_verduras Pescado)
            (tipoP Fetuccini_a_la_putanesca Pescado)
            (tipoS Ravioli_a_la_genovesa Pescado)
            (tipoP Lasaña Pescado)
            (tipoS Tallarines_con_verduras Pescado)

            (mustUse Jueves Pato_a_la_naranja)
            (RestrictedPrimero Jueves)
            (mustUse Miercoles Anchoas)
            (RestrictedPrimero Miercoles)

            (mustUse Lunes Ravioli_a_la_genovesa)
            (RestrictedSegundo Lunes)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atún_al_horno) 799)
            (= (Pcals Lubina_al_limon) 792)
            (= (Pcals Calamares_a_la_romana) 585)
            (= (Pcals Cazón) 756)
            (= (Pcals Anchoas) 727)
            (= (Pcals Pez_espada_y_cosas_pijas) 758)
            (= (Pcals Conejo_asado) 531)
            (= (Pcals Pato_a_la_naranja) 748)
            (= (Pcals Rabo_de_toro) 649)
            (= (Pcals Entrecot_al_roquefort) 709)
            (= (Pcals Galtas_de_cerdo) 652)
            (= (Pcals Hamburguesa_de_pollo) 532)
            (= (Pcals Arroz_a_la_cubana) 677)
            (= (Pcals Cuscús) 556)
            (= (Pcals Arroz_con_curry) 762)
            (= (Pcals Arroz_tres_delicias) 697)
            (= (Pcals Arroz_salteado_con_verduras) 679)
            (= (Pcals Arroz) 666)
            (= (Pcals Macarrones_a_la_bolognesa) 721)
            (= (Pcals Spaghetti_a_la_bolognesa) 785)
            (= (Pcals Spaghetti_a_la_carbonara) 753)
            (= (Pcals Sopa_de_fideos) 693)
            (= (Pcals Fetuccini_a_la_putanesca) 673)
            (= (Pcals Lasaña) 694)

            (= (Scals Bacalao_en_salsa_verde) 700)
            (= (Scals Bacalao_con_tomate) 775)
            (= (Scals Rabas_y_chocos) 769)
            (= (Scals Boquerones_al_vinagre) 612)
            (= (Scals Pulpo_a_la_feira) 521)
            (= (Scals Langosta_a_la_salsa) 520)
            (= (Scals Solomillo_de_cerdo) 592)
            (= (Scals Pollo_a_la_brasa) 793)
            (= (Scals Botifarra_del_pages) 659)
            (= (Scals Costillitas_de_cordero) 547)
            (= (Scals Callos) 644)
            (= (Scals Pechuga_de_pollo) 747)
            (= (Scals Ensalada_de_arroz) 716)
            (= (Scals Paella) 708)
            (= (Scals Arroz_con_setas) 624)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 645)
            (= (Scals Arroz_con_bogavantes) 565)
            (= (Scals Risotto_con_gambas) 665)
            (= (Scals Macarrones_a_la_carbonara) 728)
            (= (Scals Spaghetti_al_pesto) 625)
            (= (Scals Ramen) 510)
            (= (Scals Fideos_con_verduras) 746)
            (= (Scals Ravioli_a_la_genovesa) 764)
            (= (Scals Tallarines_con_verduras) 513)

            (= (Pprice Atún_al_horno) 13)
            (= (Pprice Lubina_al_limon) 15)
            (= (Pprice Calamares_a_la_romana) 11)
            (= (Pprice Cazón) 7)
            (= (Pprice Anchoas) 9)
            (= (Pprice Pez_espada_y_cosas_pijas) 13)
            (= (Pprice Conejo_asado) 9)
            (= (Pprice Pato_a_la_naranja) 8)
            (= (Pprice Rabo_de_toro) 13)
            (= (Pprice Entrecot_al_roquefort) 14)
            (= (Pprice Galtas_de_cerdo) 10)
            (= (Pprice Hamburguesa_de_pollo) 14)
            (= (Pprice Arroz_a_la_cubana) 10)
            (= (Pprice Cuscús) 11)
            (= (Pprice Arroz_con_curry) 6)
            (= (Pprice Arroz_tres_delicias) 8)
            (= (Pprice Arroz_salteado_con_verduras) 8)
            (= (Pprice Arroz) 9)
            (= (Pprice Macarrones_a_la_bolognesa) 8)
            (= (Pprice Spaghetti_a_la_bolognesa) 14)
            (= (Pprice Spaghetti_a_la_carbonara) 13)
            (= (Pprice Sopa_de_fideos) 6)
            (= (Pprice Fetuccini_a_la_putanesca) 12)
            (= (Pprice Lasaña) 12)

            (= (Sprice Bacalao_en_salsa_verde) 10)
            (= (Sprice Bacalao_con_tomate) 12)
            (= (Sprice Rabas_y_chocos) 13)
            (= (Sprice Boquerones_al_vinagre) 7)
            (= (Sprice Pulpo_a_la_feira) 14)
            (= (Sprice Langosta_a_la_salsa) 14)
            (= (Sprice Solomillo_de_cerdo) 12)
            (= (Sprice Pollo_a_la_brasa) 13)
            (= (Sprice Botifarra_del_pages) 7)
            (= (Sprice Costillitas_de_cordero) 6)
            (= (Sprice Callos) 6)
            (= (Sprice Pechuga_de_pollo) 14)
            (= (Sprice Ensalada_de_arroz) 6)
            (= (Sprice Paella) 10)
            (= (Sprice Arroz_con_setas) 6)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 15)
            (= (Sprice Arroz_con_bogavantes) 12)
            (= (Sprice Risotto_con_gambas) 15)
            (= (Sprice Macarrones_a_la_carbonara) 13)
            (= (Sprice Spaghetti_al_pesto) 15)
            (= (Sprice Ramen) 7)
            (= (Sprice Fideos_con_verduras) 14)
            (= (Sprice Ravioli_a_la_genovesa) 9)
            (= (Sprice Tallarines_con_verduras) 14)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)