(define (problem menus)
    (:domain catering)
    (:objects Atun_al_horno Lubina_al_limon Calamares_a_la_romana Cazon Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscus Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz_blanco Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasanya - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Otro Pasta - tipo
)
    (:init
        (primero Atun_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazon)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscus)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz_blanco)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasanya)

        (segundo Bacalao_en_salsa_verde)(segundo Bacalao_con_tomate)(segundo Rabas_y_chocos)(segundo Boquerones_al_vinagre)(segundo Pulpo_a_la_feira)(segundo Langosta_a_la_salsa)(segundo Solomillo_de_cerdo)(segundo Pollo_a_la_brasa)(segundo Botifarra_del_pages)(segundo Costillitas_de_cordero)(segundo Callos)(segundo Pechuga_de_pollo)(segundo Ensalada_de_arroz)(segundo Paella)(segundo Arroz_con_setas)(segundo Arroz_frito_con_salsa_de_cebolla)(segundo Arroz_con_bogavantes)(segundo Risotto_con_gambas)(segundo Macarrones_a_la_carbonara)(segundo Spaghetti_al_pesto)(segundo Ramen)(segundo Fideos_con_verduras)(segundo Ravioli_a_la_genovesa)(segundo Tallarines_con_verduras)

            (NoCompatible Arroz_salteado_con_verduras Pechuga_de_pollo)
            (NoCompatible Cuscus Spaghetti_al_pesto)
            (NoCompatible Cuscus Boquerones_al_vinagre)
            (NoCompatible Hamburguesa_de_pollo Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Lasanya Bacalao_en_salsa_verde)
            (NoCompatible Arroz_salteado_con_verduras Callos)
            (NoCompatible Macarrones_a_la_bolognesa Pollo_a_la_brasa)
            (NoCompatible Lubina_al_limon Bacalao_con_tomate)
            (NoCompatible Spaghetti_a_la_carbonara Arroz_con_bogavantes)
            (NoCompatible Entrecot_al_roquefort Botifarra_del_pages)
            (NoCompatible Pato_a_la_naranja Rabas_y_chocos)
            (NoCompatible Conejo_asado Pulpo_a_la_feira)
            (NoCompatible Fetuccini_a_la_putanesca Pechuga_de_pollo)
            (NoCompatible Spaghetti_a_la_bolognesa Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_salteado_con_verduras Bacalao_con_tomate)
            (NoCompatible Entrecot_al_roquefort Ramen)
            (NoCompatible Atun_al_horno Pollo_a_la_brasa)
            (NoCompatible Conejo_asado Bacalao_con_tomate)
            (NoCompatible Calamares_a_la_romana Pechuga_de_pollo)
            (NoCompatible Atun_al_horno Tallarines_con_verduras)
            (NoCompatible Arroz_a_la_cubana Langosta_a_la_salsa)
            (NoCompatible Pez_espada_y_cosas_pijas Arroz_con_bogavantes)
            (NoCompatible Atun_al_horno Costillitas_de_cordero)
            (NoCompatible Sopa_de_fideos Ravioli_a_la_genovesa)
            (NoCompatible Fetuccini_a_la_putanesca Macarrones_a_la_carbonara)
            (NoCompatible Sopa_de_fideos Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Anchoas Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Anchoas Tallarines_con_verduras)
            (NoCompatible Cazon Arroz_con_setas)
            (NoCompatible Lubina_al_limon Paella)
            (NoCompatible Pez_espada_y_cosas_pijas Solomillo_de_cerdo)
            (NoCompatible Spaghetti_a_la_carbonara Callos)
            (NoCompatible Arroz_con_curry Bacalao_con_tomate)
            (NoCompatible Atun_al_horno Pechuga_de_pollo)
            (NoCompatible Cazon Ramen)
            (NoCompatible Calamares_a_la_romana Arroz_con_setas)
            (NoCompatible Conejo_asado Botifarra_del_pages)
            (NoCompatible Pez_espada_y_cosas_pijas Ensalada_de_arroz)
            (NoCompatible Rabo_de_toro Callos)
            (NoCompatible Arroz_tres_delicias Risotto_con_gambas)
            (NoCompatible Rabo_de_toro Ramen)
            (NoCompatible Spaghetti_a_la_carbonara Macarrones_a_la_carbonara)
            (NoCompatible Fetuccini_a_la_putanesca Langosta_a_la_salsa)
            (NoCompatible Arroz_con_curry Ramen)
            (NoCompatible Galtas_de_cerdo Costillitas_de_cordero)
            (NoCompatible Arroz_con_curry Callos)
            (NoCompatible Lubina_al_limon Solomillo_de_cerdo)
            (NoCompatible Arroz_blanco Pechuga_de_pollo)

            (tipoP Atun_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazon Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Carne)
            (tipoS Solomillo_de_cerdo Carne)
            (tipoP Pato_a_la_naranja Carne)
            (tipoS Pollo_a_la_brasa Carne)
            (tipoP Rabo_de_toro Carne)
            (tipoS Botifarra_del_pages Carne)
            (tipoP Entrecot_al_roquefort Carne)
            (tipoS Costillitas_de_cordero Carne)
            (tipoP Galtas_de_cerdo Carne)
            (tipoS Callos Carne)
            (tipoP Hamburguesa_de_pollo Carne)
            (tipoS Pechuga_de_pollo Carne)

            (tipoP Arroz_a_la_cubana Otro)
            (tipoS Ensalada_de_arroz Otro)
            (tipoP Cuscus Otro)
            (tipoS Paella Otro)
            (tipoP Arroz_con_curry Otro)
            (tipoS Arroz_con_setas Otro)
            (tipoP Arroz_tres_delicias Otro)
            (tipoS Arroz_frito_con_salsa_de_cebolla Otro)
            (tipoP Arroz_salteado_con_verduras Otro)
            (tipoS Arroz_con_bogavantes Otro)
            (tipoP Arroz_blanco Otro)
            (tipoS Risotto_con_gambas Otro)

            (tipoP Macarrones_a_la_bolognesa Pasta)
            (tipoS Macarrones_a_la_carbonara Pasta)
            (tipoP Spaghetti_a_la_bolognesa Pasta)
            (tipoS Spaghetti_al_pesto Pasta)
            (tipoP Spaghetti_a_la_carbonara Pasta)
            (tipoS Ramen Pasta)
            (tipoP Sopa_de_fideos Pasta)
            (tipoS Fideos_con_verduras Pasta)
            (tipoP Fetuccini_a_la_putanesca Pasta)
            (tipoS Ravioli_a_la_genovesa Pasta)
            (tipoP Lasanya Pasta)
            (tipoS Tallarines_con_verduras Pasta)

            (mustUse Jueves Arroz_con_curry)
            (RestrictedPrimero Jueves)
            (mustUse Viernes Cuscus)
            (RestrictedPrimero Viernes)

            (mustUse Jueves Arroz_con_setas)
            (RestrictedSegundo Jueves)
            (mustUse Viernes Tallarines_con_verduras)
            (RestrictedSegundo Viernes)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atun_al_horno) 531)
            (= (Pcals Lubina_al_limon) 764)
            (= (Pcals Calamares_a_la_romana) 551)
            (= (Pcals Cazon) 532)
            (= (Pcals Anchoas) 665)
            (= (Pcals Pez_espada_y_cosas_pijas) 668)
            (= (Pcals Conejo_asado) 516)
            (= (Pcals Pato_a_la_naranja) 549)
            (= (Pcals Rabo_de_toro) 618)
            (= (Pcals Entrecot_al_roquefort) 621)
            (= (Pcals Galtas_de_cerdo) 677)
            (= (Pcals Hamburguesa_de_pollo) 639)
            (= (Pcals Arroz_a_la_cubana) 634)
            (= (Pcals Cuscus) 759)
            (= (Pcals Arroz_con_curry) 774)
            (= (Pcals Arroz_tres_delicias) 563)
            (= (Pcals Arroz_salteado_con_verduras) 540)
            (= (Pcals Arroz_blanco) 700)
            (= (Pcals Macarrones_a_la_bolognesa) 598)
            (= (Pcals Spaghetti_a_la_bolognesa) 799)
            (= (Pcals Spaghetti_a_la_carbonara) 502)
            (= (Pcals Sopa_de_fideos) 624)
            (= (Pcals Fetuccini_a_la_putanesca) 547)
            (= (Pcals Lasanya) 622)

            (= (Scals Bacalao_en_salsa_verde) 691)
            (= (Scals Bacalao_con_tomate) 712)
            (= (Scals Rabas_y_chocos) 555)
            (= (Scals Boquerones_al_vinagre) 770)
            (= (Scals Pulpo_a_la_feira) 686)
            (= (Scals Langosta_a_la_salsa) 544)
            (= (Scals Solomillo_de_cerdo) 708)
            (= (Scals Pollo_a_la_brasa) 633)
            (= (Scals Botifarra_del_pages) 696)
            (= (Scals Costillitas_de_cordero) 731)
            (= (Scals Callos) 555)
            (= (Scals Pechuga_de_pollo) 782)
            (= (Scals Ensalada_de_arroz) 784)
            (= (Scals Paella) 632)
            (= (Scals Arroz_con_setas) 634)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 509)
            (= (Scals Arroz_con_bogavantes) 690)
            (= (Scals Risotto_con_gambas) 655)
            (= (Scals Macarrones_a_la_carbonara) 704)
            (= (Scals Spaghetti_al_pesto) 672)
            (= (Scals Ramen) 747)
            (= (Scals Fideos_con_verduras) 638)
            (= (Scals Ravioli_a_la_genovesa) 752)
            (= (Scals Tallarines_con_verduras) 759)

            (= (Pprice Atun_al_horno) 8)
            (= (Pprice Lubina_al_limon) 11)
            (= (Pprice Calamares_a_la_romana) 14)
            (= (Pprice Cazon) 14)
            (= (Pprice Anchoas) 6)
            (= (Pprice Pez_espada_y_cosas_pijas) 14)
            (= (Pprice Conejo_asado) 7)
            (= (Pprice Pato_a_la_naranja) 14)
            (= (Pprice Rabo_de_toro) 13)
            (= (Pprice Entrecot_al_roquefort) 10)
            (= (Pprice Galtas_de_cerdo) 14)
            (= (Pprice Hamburguesa_de_pollo) 9)
            (= (Pprice Arroz_a_la_cubana) 8)
            (= (Pprice Cuscus) 6)
            (= (Pprice Arroz_con_curry) 6)
            (= (Pprice Arroz_tres_delicias) 5)
            (= (Pprice Arroz_salteado_con_verduras) 5)
            (= (Pprice Arroz_blanco) 7)
            (= (Pprice Macarrones_a_la_bolognesa) 9)
            (= (Pprice Spaghetti_a_la_bolognesa) 7)
            (= (Pprice Spaghetti_a_la_carbonara) 5)
            (= (Pprice Sopa_de_fideos) 9)
            (= (Pprice Fetuccini_a_la_putanesca) 5)
            (= (Pprice Lasanya) 14)

            (= (Sprice Bacalao_en_salsa_verde) 7)
            (= (Sprice Bacalao_con_tomate) 11)
            (= (Sprice Rabas_y_chocos) 11)
            (= (Sprice Boquerones_al_vinagre) 12)
            (= (Sprice Pulpo_a_la_feira) 5)
            (= (Sprice Langosta_a_la_salsa) 13)
            (= (Sprice Solomillo_de_cerdo) 8)
            (= (Sprice Pollo_a_la_brasa) 5)
            (= (Sprice Botifarra_del_pages) 8)
            (= (Sprice Costillitas_de_cordero) 15)
            (= (Sprice Callos) 13)
            (= (Sprice Pechuga_de_pollo) 8)
            (= (Sprice Ensalada_de_arroz) 14)
            (= (Sprice Paella) 12)
            (= (Sprice Arroz_con_setas) 11)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 8)
            (= (Sprice Arroz_con_bogavantes) 11)
            (= (Sprice Risotto_con_gambas) 5)
            (= (Sprice Macarrones_a_la_carbonara) 12)
            (= (Sprice Spaghetti_al_pesto) 6)
            (= (Sprice Ramen) 8)
            (= (Sprice Fideos_con_verduras) 14)
            (= (Sprice Ravioli_a_la_genovesa) 12)
            (= (Sprice Tallarines_con_verduras) 6)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)