(define (problem menus)
    (:domain catering)
    (:objects Atún_al_horno Lubina_al_limon Calamares_a_la_romana Cazón Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscús Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasaña - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Arroz Pasta - tipo
)
    (:init
        (primero Atún_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazón)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscús)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasaña)

        (Segundo Bacalao_en_salsa_verde)(Segundo Bacalao_con_tomate)(Segundo Rabas_y_chocos)(Segundo Boquerones_al_vinagre)(Segundo Pulpo_a_la_feira)(Segundo Langosta_a_la_salsa)(Segundo Solomillo_de_cerdo)(Segundo Pollo_a_la_brasa)(Segundo Botifarra_del_pages)(Segundo Costillitas_de_cordero)(Segundo Callos)(Segundo Pechuga_de_pollo)(Segundo Ensalada_de_arroz)(Segundo Paella)(Segundo Arroz_con_setas)(Segundo Arroz_frito_con_salsa_de_cebolla)(Segundo Arroz_con_bogavantes)(Segundo Risotto_con_gambas)(Segundo Macarrones_a_la_carbonara)(Segundo Spaghetti_al_pesto)(Segundo Ramen)(Segundo Fideos_con_verduras)(Segundo Ravioli_a_la_genovesa)(Segundo Tallarines_con_verduras)

            (NoCompatible Entrecot_al_roquefort Tallarines_con_verduras)
            (NoCompatible Arroz_con_curry Paella)
            (NoCompatible Atún_al_horno Ramen)
            (NoCompatible Sopa_de_fideos Ensalada_de_arroz)
            (NoCompatible Spaghetti_a_la_carbonara Rabas_y_chocos)
            (NoCompatible Lubina_al_limon Costillitas_de_cordero)
            (NoCompatible Lasaña Rabas_y_chocos)
            (NoCompatible Rabo_de_toro Pechuga_de_pollo)
            (NoCompatible Anchoas Tallarines_con_verduras)
            (NoCompatible Calamares_a_la_romana Arroz_con_bogavantes)
            (NoCompatible Cuscús Ensalada_de_arroz)
            (NoCompatible Spaghetti_a_la_bolognesa Macarrones_a_la_carbonara)
            (NoCompatible Sopa_de_fideos Pechuga_de_pollo)
            (NoCompatible Spaghetti_a_la_bolognesa Tallarines_con_verduras)
            (NoCompatible Arroz_a_la_cubana Ensalada_de_arroz)
            (NoCompatible Pato_a_la_naranja Pulpo_a_la_feira)
            (NoCompatible Arroz_a_la_cubana Callos)
            (NoCompatible Conejo_asado Ensalada_de_arroz)
            (NoCompatible Arroz_salteado_con_verduras Pollo_a_la_brasa)
            (NoCompatible Arroz_tres_delicias Arroz_con_setas)
            (NoCompatible Anchoas Fideos_con_verduras)
            (NoCompatible Arroz_salteado_con_verduras Paella)
            (NoCompatible Lubina_al_limon Arroz_con_bogavantes)
            (NoCompatible Conejo_asado Pulpo_a_la_feira)
            (NoCompatible Cazón Tallarines_con_verduras)
            (NoCompatible Spaghetti_a_la_carbonara Callos)
            (NoCompatible Arroz Langosta_a_la_salsa)
            (NoCompatible Calamares_a_la_romana Solomillo_de_cerdo)
            (NoCompatible Atún_al_horno Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Rabo_de_toro Ensalada_de_arroz)
            (NoCompatible Spaghetti_a_la_bolognesa Langosta_a_la_salsa)
            (NoCompatible Arroz_tres_delicias Pollo_a_la_brasa)
            (NoCompatible Lasaña Bacalao_con_tomate)
            (NoCompatible Pato_a_la_naranja Rabas_y_chocos)
            (NoCompatible Rabo_de_toro Risotto_con_gambas)
            (NoCompatible Rabo_de_toro Botifarra_del_pages)
            (NoCompatible Entrecot_al_roquefort Paella)
            (NoCompatible Hamburguesa_de_pollo Arroz_con_bogavantes)
            (NoCompatible Pato_a_la_naranja Macarrones_a_la_carbonara)
            (NoCompatible Lubina_al_limon Arroz_con_setas)
            (NoCompatible Cazón Botifarra_del_pages)
            (NoCompatible Cazón Callos)
            (NoCompatible Calamares_a_la_romana Costillitas_de_cordero)
            (NoCompatible Atún_al_horno Fideos_con_verduras)
            (NoCompatible Cuscús Langosta_a_la_salsa)
            (NoCompatible Pez_espada_y_cosas_pijas Spaghetti_al_pesto)
            (NoCompatible Arroz_tres_delicias Fideos_con_verduras)
            (NoCompatible Pez_espada_y_cosas_pijas Rabas_y_chocos)

            (tipoP Atún_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazón Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Pescado)
            (tipoS Solomillo_de_cerdo Pescado)
            (tipoP Pato_a_la_naranja Pescado)
            (tipoS Pollo_a_la_brasa Pescado)
            (tipoP Rabo_de_toro Pescado)
            (tipoS Botifarra_del_pages Pescado)
            (tipoP Entrecot_al_roquefort Pescado)
            (tipoS Costillitas_de_cordero Pescado)
            (tipoP Galtas_de_cerdo Pescado)
            (tipoS Callos Pescado)
            (tipoP Hamburguesa_de_pollo Pescado)
            (tipoS Pechuga_de_pollo Pescado)

            (tipoP Arroz_a_la_cubana Pescado)
            (tipoS Ensalada_de_arroz Pescado)
            (tipoP Cuscús Pescado)
            (tipoS Paella Pescado)
            (tipoP Arroz_con_curry Pescado)
            (tipoS Arroz_con_setas Pescado)
            (tipoP Arroz_tres_delicias Pescado)
            (tipoS Arroz_frito_con_salsa_de_cebolla Pescado)
            (tipoP Arroz_salteado_con_verduras Pescado)
            (tipoS Arroz_con_bogavantes Pescado)
            (tipoP Arroz Pescado)
            (tipoS Risotto_con_gambas Pescado)

            (tipoP Macarrones_a_la_bolognesa Pescado)
            (tipoS Macarrones_a_la_carbonara Pescado)
            (tipoP Spaghetti_a_la_bolognesa Pescado)
            (tipoS Spaghetti_al_pesto Pescado)
            (tipoP Spaghetti_a_la_carbonara Pescado)
            (tipoS Ramen Pescado)
            (tipoP Sopa_de_fideos Pescado)
            (tipoS Fideos_con_verduras Pescado)
            (tipoP Fetuccini_a_la_putanesca Pescado)
            (tipoS Ravioli_a_la_genovesa Pescado)
            (tipoP Lasaña Pescado)
            (tipoS Tallarines_con_verduras Pescado)

            (mustUse Lunes Atún_al_horno)
            (RestrictedPrimero Lunes)
            (mustUse Viernes Calamares_a_la_romana)
            (RestrictedPrimero Viernes)

            (mustUse Lunes Macarrones_a_la_carbonara)
            (RestrictedSegundo Lunes)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atún_al_horno) 727)
            (= (Pcals Lubina_al_limon) 537)
            (= (Pcals Calamares_a_la_romana) 748)
            (= (Pcals Cazón) 718)
            (= (Pcals Anchoas) 596)
            (= (Pcals Pez_espada_y_cosas_pijas) 507)
            (= (Pcals Conejo_asado) 609)
            (= (Pcals Pato_a_la_naranja) 602)
            (= (Pcals Rabo_de_toro) 778)
            (= (Pcals Entrecot_al_roquefort) 638)
            (= (Pcals Galtas_de_cerdo) 764)
            (= (Pcals Hamburguesa_de_pollo) 572)
            (= (Pcals Arroz_a_la_cubana) 597)
            (= (Pcals Cuscús) 644)
            (= (Pcals Arroz_con_curry) 507)
            (= (Pcals Arroz_tres_delicias) 688)
            (= (Pcals Arroz_salteado_con_verduras) 623)
            (= (Pcals Arroz) 724)
            (= (Pcals Macarrones_a_la_bolognesa) 600)
            (= (Pcals Spaghetti_a_la_bolognesa) 511)
            (= (Pcals Spaghetti_a_la_carbonara) 635)
            (= (Pcals Sopa_de_fideos) 564)
            (= (Pcals Fetuccini_a_la_putanesca) 608)
            (= (Pcals Lasaña) 769)

            (= (Scals Bacalao_en_salsa_verde) 572)
            (= (Scals Bacalao_con_tomate) 539)
            (= (Scals Rabas_y_chocos) 734)
            (= (Scals Boquerones_al_vinagre) 689)
            (= (Scals Pulpo_a_la_feira) 668)
            (= (Scals Langosta_a_la_salsa) 800)
            (= (Scals Solomillo_de_cerdo) 767)
            (= (Scals Pollo_a_la_brasa) 519)
            (= (Scals Botifarra_del_pages) 650)
            (= (Scals Costillitas_de_cordero) 662)
            (= (Scals Callos) 741)
            (= (Scals Pechuga_de_pollo) 597)
            (= (Scals Ensalada_de_arroz) 667)
            (= (Scals Paella) 583)
            (= (Scals Arroz_con_setas) 709)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 659)
            (= (Scals Arroz_con_bogavantes) 689)
            (= (Scals Risotto_con_gambas) 669)
            (= (Scals Macarrones_a_la_carbonara) 623)
            (= (Scals Spaghetti_al_pesto) 598)
            (= (Scals Ramen) 774)
            (= (Scals Fideos_con_verduras) 544)
            (= (Scals Ravioli_a_la_genovesa) 705)
            (= (Scals Tallarines_con_verduras) 681)

            (= (Pprice Atún_al_horno) 10)
            (= (Pprice Lubina_al_limon) 14)
            (= (Pprice Calamares_a_la_romana) 8)
            (= (Pprice Cazón) 9)
            (= (Pprice Anchoas) 13)
            (= (Pprice Pez_espada_y_cosas_pijas) 5)
            (= (Pprice Conejo_asado) 9)
            (= (Pprice Pato_a_la_naranja) 8)
            (= (Pprice Rabo_de_toro) 15)
            (= (Pprice Entrecot_al_roquefort) 8)
            (= (Pprice Galtas_de_cerdo) 10)
            (= (Pprice Hamburguesa_de_pollo) 15)
            (= (Pprice Arroz_a_la_cubana) 8)
            (= (Pprice Cuscús) 15)
            (= (Pprice Arroz_con_curry) 15)
            (= (Pprice Arroz_tres_delicias) 8)
            (= (Pprice Arroz_salteado_con_verduras) 15)
            (= (Pprice Arroz) 15)
            (= (Pprice Macarrones_a_la_bolognesa) 13)
            (= (Pprice Spaghetti_a_la_bolognesa) 14)
            (= (Pprice Spaghetti_a_la_carbonara) 10)
            (= (Pprice Sopa_de_fideos) 11)
            (= (Pprice Fetuccini_a_la_putanesca) 12)
            (= (Pprice Lasaña) 9)

            (= (Sprice Bacalao_en_salsa_verde) 13)
            (= (Sprice Bacalao_con_tomate) 5)
            (= (Sprice Rabas_y_chocos) 12)
            (= (Sprice Boquerones_al_vinagre) 6)
            (= (Sprice Pulpo_a_la_feira) 9)
            (= (Sprice Langosta_a_la_salsa) 12)
            (= (Sprice Solomillo_de_cerdo) 11)
            (= (Sprice Pollo_a_la_brasa) 10)
            (= (Sprice Botifarra_del_pages) 15)
            (= (Sprice Costillitas_de_cordero) 15)
            (= (Sprice Callos) 7)
            (= (Sprice Pechuga_de_pollo) 6)
            (= (Sprice Ensalada_de_arroz) 12)
            (= (Sprice Paella) 13)
            (= (Sprice Arroz_con_setas) 10)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 12)
            (= (Sprice Arroz_con_bogavantes) 11)
            (= (Sprice Risotto_con_gambas) 11)
            (= (Sprice Macarrones_a_la_carbonara) 14)
            (= (Sprice Spaghetti_al_pesto) 12)
            (= (Sprice Ramen) 12)
            (= (Sprice Fideos_con_verduras) 7)
            (= (Sprice Ravioli_a_la_genovesa) 7)
            (= (Sprice Tallarines_con_verduras) 15)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)