(define (problem menus)
    (:domain catering)
    (:objects Atún_al_horno Lubina_al_limon Calamares_a_la_romana Cazón Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscús Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasaña - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Arroz Pasta - tipo
)
    (:init
        (primero Atún_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazón)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscús)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasaña)

        (Segundo Bacalao_en_salsa_verde)(Segundo Bacalao_con_tomate)(Segundo Rabas_y_chocos)(Segundo Boquerones_al_vinagre)(Segundo Pulpo_a_la_feira)(Segundo Langosta_a_la_salsa)(Segundo Solomillo_de_cerdo)(Segundo Pollo_a_la_brasa)(Segundo Botifarra_del_pages)(Segundo Costillitas_de_cordero)(Segundo Callos)(Segundo Pechuga_de_pollo)(Segundo Ensalada_de_arroz)(Segundo Paella)(Segundo Arroz_con_setas)(Segundo Arroz_frito_con_salsa_de_cebolla)(Segundo Arroz_con_bogavantes)(Segundo Risotto_con_gambas)(Segundo Macarrones_a_la_carbonara)(Segundo Spaghetti_al_pesto)(Segundo Ramen)(Segundo Fideos_con_verduras)(Segundo Ravioli_a_la_genovesa)(Segundo Tallarines_con_verduras)

            (NoCompatible Fetuccini_a_la_putanesca Langosta_a_la_salsa)
            (NoCompatible Arroz_tres_delicias Fideos_con_verduras)
            (NoCompatible Entrecot_al_roquefort Pulpo_a_la_feira)
            (NoCompatible Cuscús Paella)
            (NoCompatible Galtas_de_cerdo Spaghetti_al_pesto)
            (NoCompatible Arroz_con_curry Botifarra_del_pages)
            (NoCompatible Pez_espada_y_cosas_pijas Boquerones_al_vinagre)
            (NoCompatible Arroz_tres_delicias Pollo_a_la_brasa)
            (NoCompatible Sopa_de_fideos Risotto_con_gambas)
            (NoCompatible Spaghetti_a_la_bolognesa Risotto_con_gambas)
            (NoCompatible Pez_espada_y_cosas_pijas Arroz_con_setas)
            (NoCompatible Spaghetti_a_la_carbonara Ravioli_a_la_genovesa)
            (NoCompatible Spaghetti_a_la_bolognesa Ramen)
            (NoCompatible Lasaña Paella)
            (NoCompatible Hamburguesa_de_pollo Ramen)
            (NoCompatible Galtas_de_cerdo Pechuga_de_pollo)
            (NoCompatible Arroz_a_la_cubana Fideos_con_verduras)
            (NoCompatible Arroz Bacalao_con_tomate)
            (NoCompatible Galtas_de_cerdo Arroz_con_setas)
            (NoCompatible Conejo_asado Spaghetti_al_pesto)
            (NoCompatible Arroz_salteado_con_verduras Paella)
            (NoCompatible Spaghetti_a_la_carbonara Macarrones_a_la_carbonara)
            (NoCompatible Rabo_de_toro Fideos_con_verduras)
            (NoCompatible Atún_al_horno Ravioli_a_la_genovesa)
            (NoCompatible Arroz_salteado_con_verduras Rabas_y_chocos)
            (NoCompatible Lubina_al_limon Arroz_con_setas)
            (NoCompatible Conejo_asado Pulpo_a_la_feira)
            (NoCompatible Arroz Arroz_con_setas)
            (NoCompatible Arroz_con_curry Tallarines_con_verduras)
            (NoCompatible Atún_al_horno Paella)
            (NoCompatible Lasaña Callos)
            (NoCompatible Calamares_a_la_romana Macarrones_a_la_carbonara)
            (NoCompatible Conejo_asado Callos)
            (NoCompatible Arroz_tres_delicias Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Galtas_de_cerdo Callos)
            (NoCompatible Lubina_al_limon Ensalada_de_arroz)
            (NoCompatible Spaghetti_a_la_carbonara Paella)
            (NoCompatible Cazón Tallarines_con_verduras)
            (NoCompatible Galtas_de_cerdo Fideos_con_verduras)
            (NoCompatible Galtas_de_cerdo Tallarines_con_verduras)
            (NoCompatible Conejo_asado Ensalada_de_arroz)
            (NoCompatible Pez_espada_y_cosas_pijas Bacalao_con_tomate)
            (NoCompatible Calamares_a_la_romana Bacalao_con_tomate)
            (NoCompatible Arroz_tres_delicias Risotto_con_gambas)
            (NoCompatible Pato_a_la_naranja Pulpo_a_la_feira)
            (NoCompatible Galtas_de_cerdo Ravioli_a_la_genovesa)
            (NoCompatible Rabo_de_toro Boquerones_al_vinagre)
            (NoCompatible Arroz_con_curry Costillitas_de_cordero)

            (tipoP Atún_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazón Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Pescado)
            (tipoS Solomillo_de_cerdo Pescado)
            (tipoP Pato_a_la_naranja Pescado)
            (tipoS Pollo_a_la_brasa Pescado)
            (tipoP Rabo_de_toro Pescado)
            (tipoS Botifarra_del_pages Pescado)
            (tipoP Entrecot_al_roquefort Pescado)
            (tipoS Costillitas_de_cordero Pescado)
            (tipoP Galtas_de_cerdo Pescado)
            (tipoS Callos Pescado)
            (tipoP Hamburguesa_de_pollo Pescado)
            (tipoS Pechuga_de_pollo Pescado)

            (tipoP Arroz_a_la_cubana Pescado)
            (tipoS Ensalada_de_arroz Pescado)
            (tipoP Cuscús Pescado)
            (tipoS Paella Pescado)
            (tipoP Arroz_con_curry Pescado)
            (tipoS Arroz_con_setas Pescado)
            (tipoP Arroz_tres_delicias Pescado)
            (tipoS Arroz_frito_con_salsa_de_cebolla Pescado)
            (tipoP Arroz_salteado_con_verduras Pescado)
            (tipoS Arroz_con_bogavantes Pescado)
            (tipoP Arroz Pescado)
            (tipoS Risotto_con_gambas Pescado)

            (tipoP Macarrones_a_la_bolognesa Pescado)
            (tipoS Macarrones_a_la_carbonara Pescado)
            (tipoP Spaghetti_a_la_bolognesa Pescado)
            (tipoS Spaghetti_al_pesto Pescado)
            (tipoP Spaghetti_a_la_carbonara Pescado)
            (tipoS Ramen Pescado)
            (tipoP Sopa_de_fideos Pescado)
            (tipoS Fideos_con_verduras Pescado)
            (tipoP Fetuccini_a_la_putanesca Pescado)
            (tipoS Ravioli_a_la_genovesa Pescado)
            (tipoP Lasaña Pescado)
            (tipoS Tallarines_con_verduras Pescado)

            (mustUse Martes Macarrones_a_la_bolognesa)
            (RestrictedPrimero Martes)
            (mustUse Jueves Entrecot_al_roquefort)
            (RestrictedPrimero Jueves)

            (mustUse Miercoles Rabas_y_chocos)
            (RestrictedSegundo Miercoles)
            (mustUse Martes Solomillo_de_cerdo)
            (RestrictedSegundo Martes)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atún_al_horno) 574)
            (= (Pcals Lubina_al_limon) 595)
            (= (Pcals Calamares_a_la_romana) 631)
            (= (Pcals Cazón) 561)
            (= (Pcals Anchoas) 676)
            (= (Pcals Pez_espada_y_cosas_pijas) 757)
            (= (Pcals Conejo_asado) 717)
            (= (Pcals Pato_a_la_naranja) 559)
            (= (Pcals Rabo_de_toro) 739)
            (= (Pcals Entrecot_al_roquefort) 609)
            (= (Pcals Galtas_de_cerdo) 609)
            (= (Pcals Hamburguesa_de_pollo) 785)
            (= (Pcals Arroz_a_la_cubana) 739)
            (= (Pcals Cuscús) 580)
            (= (Pcals Arroz_con_curry) 657)
            (= (Pcals Arroz_tres_delicias) 534)
            (= (Pcals Arroz_salteado_con_verduras) 684)
            (= (Pcals Arroz) 559)
            (= (Pcals Macarrones_a_la_bolognesa) 591)
            (= (Pcals Spaghetti_a_la_bolognesa) 528)
            (= (Pcals Spaghetti_a_la_carbonara) 649)
            (= (Pcals Sopa_de_fideos) 639)
            (= (Pcals Fetuccini_a_la_putanesca) 698)
            (= (Pcals Lasaña) 703)

            (= (Scals Bacalao_en_salsa_verde) 743)
            (= (Scals Bacalao_con_tomate) 732)
            (= (Scals Rabas_y_chocos) 599)
            (= (Scals Boquerones_al_vinagre) 677)
            (= (Scals Pulpo_a_la_feira) 506)
            (= (Scals Langosta_a_la_salsa) 582)
            (= (Scals Solomillo_de_cerdo) 543)
            (= (Scals Pollo_a_la_brasa) 532)
            (= (Scals Botifarra_del_pages) 721)
            (= (Scals Costillitas_de_cordero) 698)
            (= (Scals Callos) 534)
            (= (Scals Pechuga_de_pollo) 708)
            (= (Scals Ensalada_de_arroz) 629)
            (= (Scals Paella) 541)
            (= (Scals Arroz_con_setas) 521)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 610)
            (= (Scals Arroz_con_bogavantes) 787)
            (= (Scals Risotto_con_gambas) 528)
            (= (Scals Macarrones_a_la_carbonara) 663)
            (= (Scals Spaghetti_al_pesto) 556)
            (= (Scals Ramen) 674)
            (= (Scals Fideos_con_verduras) 800)
            (= (Scals Ravioli_a_la_genovesa) 659)
            (= (Scals Tallarines_con_verduras) 661)

            (= (Pprice Atún_al_horno) 6)
            (= (Pprice Lubina_al_limon) 10)
            (= (Pprice Calamares_a_la_romana) 7)
            (= (Pprice Cazón) 5)
            (= (Pprice Anchoas) 12)
            (= (Pprice Pez_espada_y_cosas_pijas) 10)
            (= (Pprice Conejo_asado) 14)
            (= (Pprice Pato_a_la_naranja) 9)
            (= (Pprice Rabo_de_toro) 15)
            (= (Pprice Entrecot_al_roquefort) 13)
            (= (Pprice Galtas_de_cerdo) 7)
            (= (Pprice Hamburguesa_de_pollo) 9)
            (= (Pprice Arroz_a_la_cubana) 13)
            (= (Pprice Cuscús) 14)
            (= (Pprice Arroz_con_curry) 15)
            (= (Pprice Arroz_tres_delicias) 8)
            (= (Pprice Arroz_salteado_con_verduras) 7)
            (= (Pprice Arroz) 10)
            (= (Pprice Macarrones_a_la_bolognesa) 6)
            (= (Pprice Spaghetti_a_la_bolognesa) 6)
            (= (Pprice Spaghetti_a_la_carbonara) 14)
            (= (Pprice Sopa_de_fideos) 12)
            (= (Pprice Fetuccini_a_la_putanesca) 9)
            (= (Pprice Lasaña) 13)

            (= (Sprice Bacalao_en_salsa_verde) 10)
            (= (Sprice Bacalao_con_tomate) 5)
            (= (Sprice Rabas_y_chocos) 6)
            (= (Sprice Boquerones_al_vinagre) 12)
            (= (Sprice Pulpo_a_la_feira) 10)
            (= (Sprice Langosta_a_la_salsa) 5)
            (= (Sprice Solomillo_de_cerdo) 11)
            (= (Sprice Pollo_a_la_brasa) 11)
            (= (Sprice Botifarra_del_pages) 15)
            (= (Sprice Costillitas_de_cordero) 7)
            (= (Sprice Callos) 5)
            (= (Sprice Pechuga_de_pollo) 11)
            (= (Sprice Ensalada_de_arroz) 6)
            (= (Sprice Paella) 6)
            (= (Sprice Arroz_con_setas) 12)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 11)
            (= (Sprice Arroz_con_bogavantes) 5)
            (= (Sprice Risotto_con_gambas) 5)
            (= (Sprice Macarrones_a_la_carbonara) 9)
            (= (Sprice Spaghetti_al_pesto) 11)
            (= (Sprice Ramen) 14)
            (= (Sprice Fideos_con_verduras) 12)
            (= (Sprice Ravioli_a_la_genovesa) 8)
            (= (Sprice Tallarines_con_verduras) 15)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)