(define (problem menus)
    (:domain catering)
    (:objects Atun_al_horno Lubina_al_limon Calamares_a_la_romana Cazon Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscus Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz_blanco Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasanya - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Otro Pasta - tipo
)
    (:init
        (primero Atun_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazon)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscus)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz_blanco)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasanya)

        (segundo Bacalao_en_salsa_verde)(segundo Bacalao_con_tomate)(segundo Rabas_y_chocos)(segundo Boquerones_al_vinagre)(segundo Pulpo_a_la_feira)(segundo Langosta_a_la_salsa)(segundo Solomillo_de_cerdo)(segundo Pollo_a_la_brasa)(segundo Botifarra_del_pages)(segundo Costillitas_de_cordero)(segundo Callos)(segundo Pechuga_de_pollo)(segundo Ensalada_de_arroz)(segundo Paella)(segundo Arroz_con_setas)(segundo Arroz_frito_con_salsa_de_cebolla)(segundo Arroz_con_bogavantes)(segundo Risotto_con_gambas)(segundo Macarrones_a_la_carbonara)(segundo Spaghetti_al_pesto)(segundo Ramen)(segundo Fideos_con_verduras)(segundo Ravioli_a_la_genovesa)(segundo Tallarines_con_verduras)

            (NoCompatible Pez_espada_y_cosas_pijas Ravioli_a_la_genovesa)
            (NoCompatible Pato_a_la_naranja Spaghetti_al_pesto)
            (NoCompatible Entrecot_al_roquefort Spaghetti_al_pesto)
            (NoCompatible Sopa_de_fideos Pollo_a_la_brasa)
            (NoCompatible Entrecot_al_roquefort Ensalada_de_arroz)
            (NoCompatible Macarrones_a_la_bolognesa Langosta_a_la_salsa)
            (NoCompatible Conejo_asado Boquerones_al_vinagre)
            (NoCompatible Calamares_a_la_romana Ravioli_a_la_genovesa)
            (NoCompatible Calamares_a_la_romana Arroz_con_bogavantes)
            (NoCompatible Fetuccini_a_la_putanesca Costillitas_de_cordero)
            (NoCompatible Entrecot_al_roquefort Bacalao_con_tomate)
            (NoCompatible Arroz_salteado_con_verduras Macarrones_a_la_carbonara)
            (NoCompatible Lubina_al_limon Paella)
            (NoCompatible Hamburguesa_de_pollo Paella)
            (NoCompatible Arroz_salteado_con_verduras Costillitas_de_cordero)
            (NoCompatible Arroz_salteado_con_verduras Arroz_con_setas)
            (NoCompatible Galtas_de_cerdo Langosta_a_la_salsa)
            (NoCompatible Cazon Ravioli_a_la_genovesa)
            (NoCompatible Hamburguesa_de_pollo Tallarines_con_verduras)
            (NoCompatible Arroz_tres_delicias Callos)
            (NoCompatible Galtas_de_cerdo Bacalao_en_salsa_verde)
            (NoCompatible Arroz_a_la_cubana Pulpo_a_la_feira)
            (NoCompatible Sopa_de_fideos Callos)
            (NoCompatible Arroz_a_la_cubana Ensalada_de_arroz)
            (NoCompatible Pato_a_la_naranja Ravioli_a_la_genovesa)
            (NoCompatible Spaghetti_a_la_bolognesa Langosta_a_la_salsa)
            (NoCompatible Galtas_de_cerdo Spaghetti_al_pesto)
            (NoCompatible Spaghetti_a_la_carbonara Callos)
            (NoCompatible Fetuccini_a_la_putanesca Solomillo_de_cerdo)
            (NoCompatible Conejo_asado Ensalada_de_arroz)
            (NoCompatible Pato_a_la_naranja Bacalao_en_salsa_verde)
            (NoCompatible Arroz_salteado_con_verduras Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Rabo_de_toro Paella)
            (NoCompatible Pez_espada_y_cosas_pijas Costillitas_de_cordero)
            (NoCompatible Lubina_al_limon Arroz_con_setas)
            (NoCompatible Arroz_salteado_con_verduras Ensalada_de_arroz)
            (NoCompatible Entrecot_al_roquefort Boquerones_al_vinagre)
            (NoCompatible Conejo_asado Bacalao_en_salsa_verde)
            (NoCompatible Arroz_a_la_cubana Bacalao_en_salsa_verde)
            (NoCompatible Macarrones_a_la_bolognesa Macarrones_a_la_carbonara)
            (NoCompatible Sopa_de_fideos Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Lasanya Tallarines_con_verduras)
            (NoCompatible Calamares_a_la_romana Arroz_con_setas)
            (NoCompatible Macarrones_a_la_bolognesa Spaghetti_al_pesto)
            (NoCompatible Cuscus Solomillo_de_cerdo)
            (NoCompatible Arroz_a_la_cubana Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_a_la_cubana Langosta_a_la_salsa)
            (NoCompatible Cazon Pulpo_a_la_feira)

            (tipoP Atun_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazon Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Carne)
            (tipoS Solomillo_de_cerdo Carne)
            (tipoP Pato_a_la_naranja Carne)
            (tipoS Pollo_a_la_brasa Carne)
            (tipoP Rabo_de_toro Carne)
            (tipoS Botifarra_del_pages Carne)
            (tipoP Entrecot_al_roquefort Carne)
            (tipoS Costillitas_de_cordero Carne)
            (tipoP Galtas_de_cerdo Carne)
            (tipoS Callos Carne)
            (tipoP Hamburguesa_de_pollo Carne)
            (tipoS Pechuga_de_pollo Carne)

            (tipoP Arroz_a_la_cubana Otro)
            (tipoS Ensalada_de_arroz Otro)
            (tipoP Cuscus Otro)
            (tipoS Paella Otro)
            (tipoP Arroz_con_curry Otro)
            (tipoS Arroz_con_setas Otro)
            (tipoP Arroz_tres_delicias Otro)
            (tipoS Arroz_frito_con_salsa_de_cebolla Otro)
            (tipoP Arroz_salteado_con_verduras Otro)
            (tipoS Arroz_con_bogavantes Otro)
            (tipoP Arroz_blanco Otro)
            (tipoS Risotto_con_gambas Otro)

            (tipoP Macarrones_a_la_bolognesa Pasta)
            (tipoS Macarrones_a_la_carbonara Pasta)
            (tipoP Spaghetti_a_la_bolognesa Pasta)
            (tipoS Spaghetti_al_pesto Pasta)
            (tipoP Spaghetti_a_la_carbonara Pasta)
            (tipoS Ramen Pasta)
            (tipoP Sopa_de_fideos Pasta)
            (tipoS Fideos_con_verduras Pasta)
            (tipoP Fetuccini_a_la_putanesca Pasta)
            (tipoS Ravioli_a_la_genovesa Pasta)
            (tipoP Lasanya Pasta)
            (tipoS Tallarines_con_verduras Pasta)

            (mustUse Martes Conejo_asado)
            (RestrictedPrimero Martes)
            (mustUse Lunes Arroz_tres_delicias)
            (RestrictedPrimero Lunes)

            (mustUse Miercoles Ensalada_de_arroz)
            (RestrictedSegundo Miercoles)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atun_al_horno) 614)
            (= (Pcals Lubina_al_limon) 706)
            (= (Pcals Calamares_a_la_romana) 614)
            (= (Pcals Cazon) 550)
            (= (Pcals Anchoas) 654)
            (= (Pcals Pez_espada_y_cosas_pijas) 711)
            (= (Pcals Conejo_asado) 653)
            (= (Pcals Pato_a_la_naranja) 613)
            (= (Pcals Rabo_de_toro) 569)
            (= (Pcals Entrecot_al_roquefort) 791)
            (= (Pcals Galtas_de_cerdo) 528)
            (= (Pcals Hamburguesa_de_pollo) 643)
            (= (Pcals Arroz_a_la_cubana) 583)
            (= (Pcals Cuscus) 745)
            (= (Pcals Arroz_con_curry) 742)
            (= (Pcals Arroz_tres_delicias) 795)
            (= (Pcals Arroz_salteado_con_verduras) 576)
            (= (Pcals Arroz_blanco) 530)
            (= (Pcals Macarrones_a_la_bolognesa) 572)
            (= (Pcals Spaghetti_a_la_bolognesa) 505)
            (= (Pcals Spaghetti_a_la_carbonara) 797)
            (= (Pcals Sopa_de_fideos) 504)
            (= (Pcals Fetuccini_a_la_putanesca) 685)
            (= (Pcals Lasanya) 611)

            (= (Scals Bacalao_en_salsa_verde) 594)
            (= (Scals Bacalao_con_tomate) 527)
            (= (Scals Rabas_y_chocos) 679)
            (= (Scals Boquerones_al_vinagre) 774)
            (= (Scals Pulpo_a_la_feira) 629)
            (= (Scals Langosta_a_la_salsa) 676)
            (= (Scals Solomillo_de_cerdo) 693)
            (= (Scals Pollo_a_la_brasa) 611)
            (= (Scals Botifarra_del_pages) 580)
            (= (Scals Costillitas_de_cordero) 665)
            (= (Scals Callos) 647)
            (= (Scals Pechuga_de_pollo) 766)
            (= (Scals Ensalada_de_arroz) 702)
            (= (Scals Paella) 737)
            (= (Scals Arroz_con_setas) 511)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 708)
            (= (Scals Arroz_con_bogavantes) 545)
            (= (Scals Risotto_con_gambas) 674)
            (= (Scals Macarrones_a_la_carbonara) 776)
            (= (Scals Spaghetti_al_pesto) 699)
            (= (Scals Ramen) 589)
            (= (Scals Fideos_con_verduras) 602)
            (= (Scals Ravioli_a_la_genovesa) 735)
            (= (Scals Tallarines_con_verduras) 645)

            (= (Pprice Atun_al_horno) 9)
            (= (Pprice Lubina_al_limon) 7)
            (= (Pprice Calamares_a_la_romana) 9)
            (= (Pprice Cazon) 11)
            (= (Pprice Anchoas) 12)
            (= (Pprice Pez_espada_y_cosas_pijas) 9)
            (= (Pprice Conejo_asado) 6)
            (= (Pprice Pato_a_la_naranja) 9)
            (= (Pprice Rabo_de_toro) 13)
            (= (Pprice Entrecot_al_roquefort) 9)
            (= (Pprice Galtas_de_cerdo) 11)
            (= (Pprice Hamburguesa_de_pollo) 10)
            (= (Pprice Arroz_a_la_cubana) 6)
            (= (Pprice Cuscus) 7)
            (= (Pprice Arroz_con_curry) 6)
            (= (Pprice Arroz_tres_delicias) 7)
            (= (Pprice Arroz_salteado_con_verduras) 15)
            (= (Pprice Arroz_blanco) 9)
            (= (Pprice Macarrones_a_la_bolognesa) 14)
            (= (Pprice Spaghetti_a_la_bolognesa) 9)
            (= (Pprice Spaghetti_a_la_carbonara) 9)
            (= (Pprice Sopa_de_fideos) 6)
            (= (Pprice Fetuccini_a_la_putanesca) 10)
            (= (Pprice Lasanya) 12)

            (= (Sprice Bacalao_en_salsa_verde) 5)
            (= (Sprice Bacalao_con_tomate) 13)
            (= (Sprice Rabas_y_chocos) 12)
            (= (Sprice Boquerones_al_vinagre) 15)
            (= (Sprice Pulpo_a_la_feira) 11)
            (= (Sprice Langosta_a_la_salsa) 11)
            (= (Sprice Solomillo_de_cerdo) 5)
            (= (Sprice Pollo_a_la_brasa) 12)
            (= (Sprice Botifarra_del_pages) 8)
            (= (Sprice Costillitas_de_cordero) 15)
            (= (Sprice Callos) 6)
            (= (Sprice Pechuga_de_pollo) 8)
            (= (Sprice Ensalada_de_arroz) 9)
            (= (Sprice Paella) 13)
            (= (Sprice Arroz_con_setas) 6)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 8)
            (= (Sprice Arroz_con_bogavantes) 6)
            (= (Sprice Risotto_con_gambas) 7)
            (= (Sprice Macarrones_a_la_carbonara) 8)
            (= (Sprice Spaghetti_al_pesto) 5)
            (= (Sprice Ramen) 10)
            (= (Sprice Fideos_con_verduras) 14)
            (= (Sprice Ravioli_a_la_genovesa) 5)
            (= (Sprice Tallarines_con_verduras) 13)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)