(define (problem menus)
    (:domain catering)
    (:objects Atun_al_horno Lubina_al_limon Calamares_a_la_romana Cazon Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscus Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz_blanco Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasanya - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Otro Pasta - tipo
)
    (:init
        (primero Atun_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazon)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscus)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz_blanco)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasanya)

        (segundo Bacalao_en_salsa_verde)(segundo Bacalao_con_tomate)(segundo Rabas_y_chocos)(segundo Boquerones_al_vinagre)(segundo Pulpo_a_la_feira)(segundo Langosta_a_la_salsa)(segundo Solomillo_de_cerdo)(segundo Pollo_a_la_brasa)(segundo Botifarra_del_pages)(segundo Costillitas_de_cordero)(segundo Callos)(segundo Pechuga_de_pollo)(segundo Ensalada_de_arroz)(segundo Paella)(segundo Arroz_con_setas)(segundo Arroz_frito_con_salsa_de_cebolla)(segundo Arroz_con_bogavantes)(segundo Risotto_con_gambas)(segundo Macarrones_a_la_carbonara)(segundo Spaghetti_al_pesto)(segundo Ramen)(segundo Fideos_con_verduras)(segundo Ravioli_a_la_genovesa)(segundo Tallarines_con_verduras)

            (NoCompatible Fetuccini_a_la_putanesca Macarrones_a_la_carbonara)
            (NoCompatible Arroz_con_curry Langosta_a_la_salsa)
            (NoCompatible Sopa_de_fideos Pulpo_a_la_feira)
            (NoCompatible Lasanya Bacalao_en_salsa_verde)
            (NoCompatible Pato_a_la_naranja Ramen)
            (NoCompatible Rabo_de_toro Pechuga_de_pollo)
            (NoCompatible Spaghetti_a_la_carbonara Ensalada_de_arroz)
            (NoCompatible Cazon Arroz_con_bogavantes)
            (NoCompatible Anchoas Ravioli_a_la_genovesa)
            (NoCompatible Spaghetti_a_la_carbonara Bacalao_con_tomate)
            (NoCompatible Spaghetti_a_la_bolognesa Paella)
            (NoCompatible Conejo_asado Ramen)
            (NoCompatible Lasanya Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Anchoas Tallarines_con_verduras)
            (NoCompatible Lasanya Arroz_con_setas)
            (NoCompatible Conejo_asado Fideos_con_verduras)
            (NoCompatible Anchoas Pulpo_a_la_feira)
            (NoCompatible Galtas_de_cerdo Pechuga_de_pollo)
            (NoCompatible Hamburguesa_de_pollo Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Fetuccini_a_la_putanesca Langosta_a_la_salsa)
            (NoCompatible Pato_a_la_naranja Botifarra_del_pages)
            (NoCompatible Sopa_de_fideos Pechuga_de_pollo)
            (NoCompatible Pez_espada_y_cosas_pijas Risotto_con_gambas)
            (NoCompatible Arroz_tres_delicias Boquerones_al_vinagre)
            (NoCompatible Arroz_a_la_cubana Arroz_con_setas)
            (NoCompatible Entrecot_al_roquefort Fideos_con_verduras)
            (NoCompatible Macarrones_a_la_bolognesa Paella)
            (NoCompatible Pez_espada_y_cosas_pijas Pollo_a_la_brasa)
            (NoCompatible Galtas_de_cerdo Macarrones_a_la_carbonara)
            (NoCompatible Lubina_al_limon Pechuga_de_pollo)
            (NoCompatible Atun_al_horno Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_blanco Pechuga_de_pollo)
            (NoCompatible Arroz_blanco Tallarines_con_verduras)
            (NoCompatible Spaghetti_a_la_bolognesa Pollo_a_la_brasa)
            (NoCompatible Hamburguesa_de_pollo Pulpo_a_la_feira)
            (NoCompatible Galtas_de_cerdo Bacalao_en_salsa_verde)
            (NoCompatible Spaghetti_a_la_carbonara Boquerones_al_vinagre)
            (NoCompatible Rabo_de_toro Callos)
            (NoCompatible Cazon Pechuga_de_pollo)
            (NoCompatible Conejo_asado Arroz_con_setas)
            (NoCompatible Galtas_de_cerdo Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Rabo_de_toro Botifarra_del_pages)
            (NoCompatible Lubina_al_limon Tallarines_con_verduras)
            (NoCompatible Rabo_de_toro Fideos_con_verduras)
            (NoCompatible Cuscus Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Sopa_de_fideos Spaghetti_al_pesto)
            (NoCompatible Arroz_tres_delicias Tallarines_con_verduras)
            (NoCompatible Macarrones_a_la_bolognesa Pollo_a_la_brasa)

            (tipoP Atun_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazon Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Carne)
            (tipoS Solomillo_de_cerdo Carne)
            (tipoP Pato_a_la_naranja Carne)
            (tipoS Pollo_a_la_brasa Carne)
            (tipoP Rabo_de_toro Carne)
            (tipoS Botifarra_del_pages Carne)
            (tipoP Entrecot_al_roquefort Carne)
            (tipoS Costillitas_de_cordero Carne)
            (tipoP Galtas_de_cerdo Carne)
            (tipoS Callos Carne)
            (tipoP Hamburguesa_de_pollo Carne)
            (tipoS Pechuga_de_pollo Carne)

            (tipoP Arroz_a_la_cubana Otro)
            (tipoS Ensalada_de_arroz Otro)
            (tipoP Cuscus Otro)
            (tipoS Paella Otro)
            (tipoP Arroz_con_curry Otro)
            (tipoS Arroz_con_setas Otro)
            (tipoP Arroz_tres_delicias Otro)
            (tipoS Arroz_frito_con_salsa_de_cebolla Otro)
            (tipoP Arroz_salteado_con_verduras Otro)
            (tipoS Arroz_con_bogavantes Otro)
            (tipoP Arroz_blanco Otro)
            (tipoS Risotto_con_gambas Otro)

            (tipoP Macarrones_a_la_bolognesa Pasta)
            (tipoS Macarrones_a_la_carbonara Pasta)
            (tipoP Spaghetti_a_la_bolognesa Pasta)
            (tipoS Spaghetti_al_pesto Pasta)
            (tipoP Spaghetti_a_la_carbonara Pasta)
            (tipoS Ramen Pasta)
            (tipoP Sopa_de_fideos Pasta)
            (tipoS Fideos_con_verduras Pasta)
            (tipoP Fetuccini_a_la_putanesca Pasta)
            (tipoS Ravioli_a_la_genovesa Pasta)
            (tipoP Lasanya Pasta)
            (tipoS Tallarines_con_verduras Pasta)

            (mustUse Jueves Anchoas)
            (RestrictedPrimero Jueves)

            (mustUse Miercoles Ramen)
            (RestrictedSegundo Miercoles)
            (mustUse Lunes Costillitas_de_cordero)
            (RestrictedSegundo Lunes)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atun_al_horno) 639)
            (= (Pcals Lubina_al_limon) 604)
            (= (Pcals Calamares_a_la_romana) 739)
            (= (Pcals Cazon) 675)
            (= (Pcals Anchoas) 653)
            (= (Pcals Pez_espada_y_cosas_pijas) 727)
            (= (Pcals Conejo_asado) 542)
            (= (Pcals Pato_a_la_naranja) 545)
            (= (Pcals Rabo_de_toro) 627)
            (= (Pcals Entrecot_al_roquefort) 728)
            (= (Pcals Galtas_de_cerdo) 734)
            (= (Pcals Hamburguesa_de_pollo) 606)
            (= (Pcals Arroz_a_la_cubana) 629)
            (= (Pcals Cuscus) 670)
            (= (Pcals Arroz_con_curry) 646)
            (= (Pcals Arroz_tres_delicias) 785)
            (= (Pcals Arroz_salteado_con_verduras) 748)
            (= (Pcals Arroz_blanco) 726)
            (= (Pcals Macarrones_a_la_bolognesa) 519)
            (= (Pcals Spaghetti_a_la_bolognesa) 567)
            (= (Pcals Spaghetti_a_la_carbonara) 749)
            (= (Pcals Sopa_de_fideos) 762)
            (= (Pcals Fetuccini_a_la_putanesca) 576)
            (= (Pcals Lasanya) 646)

            (= (Scals Bacalao_en_salsa_verde) 544)
            (= (Scals Bacalao_con_tomate) 562)
            (= (Scals Rabas_y_chocos) 646)
            (= (Scals Boquerones_al_vinagre) 703)
            (= (Scals Pulpo_a_la_feira) 649)
            (= (Scals Langosta_a_la_salsa) 570)
            (= (Scals Solomillo_de_cerdo) 551)
            (= (Scals Pollo_a_la_brasa) 751)
            (= (Scals Botifarra_del_pages) 558)
            (= (Scals Costillitas_de_cordero) 632)
            (= (Scals Callos) 728)
            (= (Scals Pechuga_de_pollo) 580)
            (= (Scals Ensalada_de_arroz) 772)
            (= (Scals Paella) 728)
            (= (Scals Arroz_con_setas) 658)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 694)
            (= (Scals Arroz_con_bogavantes) 546)
            (= (Scals Risotto_con_gambas) 509)
            (= (Scals Macarrones_a_la_carbonara) 599)
            (= (Scals Spaghetti_al_pesto) 545)
            (= (Scals Ramen) 711)
            (= (Scals Fideos_con_verduras) 691)
            (= (Scals Ravioli_a_la_genovesa) 617)
            (= (Scals Tallarines_con_verduras) 782)

            (= (Pprice Atun_al_horno) 11)
            (= (Pprice Lubina_al_limon) 14)
            (= (Pprice Calamares_a_la_romana) 7)
            (= (Pprice Cazon) 9)
            (= (Pprice Anchoas) 11)
            (= (Pprice Pez_espada_y_cosas_pijas) 12)
            (= (Pprice Conejo_asado) 11)
            (= (Pprice Pato_a_la_naranja) 7)
            (= (Pprice Rabo_de_toro) 10)
            (= (Pprice Entrecot_al_roquefort) 9)
            (= (Pprice Galtas_de_cerdo) 9)
            (= (Pprice Hamburguesa_de_pollo) 6)
            (= (Pprice Arroz_a_la_cubana) 9)
            (= (Pprice Cuscus) 6)
            (= (Pprice Arroz_con_curry) 10)
            (= (Pprice Arroz_tres_delicias) 12)
            (= (Pprice Arroz_salteado_con_verduras) 7)
            (= (Pprice Arroz_blanco) 7)
            (= (Pprice Macarrones_a_la_bolognesa) 6)
            (= (Pprice Spaghetti_a_la_bolognesa) 6)
            (= (Pprice Spaghetti_a_la_carbonara) 6)
            (= (Pprice Sopa_de_fideos) 11)
            (= (Pprice Fetuccini_a_la_putanesca) 7)
            (= (Pprice Lasanya) 7)

            (= (Sprice Bacalao_en_salsa_verde) 12)
            (= (Sprice Bacalao_con_tomate) 15)
            (= (Sprice Rabas_y_chocos) 9)
            (= (Sprice Boquerones_al_vinagre) 10)
            (= (Sprice Pulpo_a_la_feira) 6)
            (= (Sprice Langosta_a_la_salsa) 8)
            (= (Sprice Solomillo_de_cerdo) 12)
            (= (Sprice Pollo_a_la_brasa) 5)
            (= (Sprice Botifarra_del_pages) 7)
            (= (Sprice Costillitas_de_cordero) 7)
            (= (Sprice Callos) 9)
            (= (Sprice Pechuga_de_pollo) 12)
            (= (Sprice Ensalada_de_arroz) 5)
            (= (Sprice Paella) 7)
            (= (Sprice Arroz_con_setas) 11)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 10)
            (= (Sprice Arroz_con_bogavantes) 8)
            (= (Sprice Risotto_con_gambas) 6)
            (= (Sprice Macarrones_a_la_carbonara) 14)
            (= (Sprice Spaghetti_al_pesto) 11)
            (= (Sprice Ramen) 15)
            (= (Sprice Fideos_con_verduras) 7)
            (= (Sprice Ravioli_a_la_genovesa) 8)
            (= (Sprice Tallarines_con_verduras) 11)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)