(define (problem menus)
    (:domain catering)
    (:objects Atún_al_horno Lubina_al_limon Calamares_a_la_romana Cazón Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscús Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasaña - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Arroz Pasta - tipo
)
    (:init
        (primero Atún_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazón)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscús)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasaña)

        (Segundo Bacalao_en_salsa_verde)(Segundo Bacalao_con_tomate)(Segundo Rabas_y_chocos)(Segundo Boquerones_al_vinagre)(Segundo Pulpo_a_la_feira)(Segundo Langosta_a_la_salsa)(Segundo Solomillo_de_cerdo)(Segundo Pollo_a_la_brasa)(Segundo Botifarra_del_pages)(Segundo Costillitas_de_cordero)(Segundo Callos)(Segundo Pechuga_de_pollo)(Segundo Ensalada_de_arroz)(Segundo Paella)(Segundo Arroz_con_setas)(Segundo Arroz_frito_con_salsa_de_cebolla)(Segundo Arroz_con_bogavantes)(Segundo Risotto_con_gambas)(Segundo Macarrones_a_la_carbonara)(Segundo Spaghetti_al_pesto)(Segundo Ramen)(Segundo Fideos_con_verduras)(Segundo Ravioli_a_la_genovesa)(Segundo Tallarines_con_verduras)

            (NoCompatible Atún_al_horno Pollo_a_la_brasa)
            (NoCompatible Lasaña Tallarines_con_verduras)
            (NoCompatible Lubina_al_limon Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Pez_espada_y_cosas_pijas Ensalada_de_arroz)
            (NoCompatible Arroz Tallarines_con_verduras)
            (NoCompatible Anchoas Bacalao_en_salsa_verde)
            (NoCompatible Sopa_de_fideos Ravioli_a_la_genovesa)
            (NoCompatible Rabo_de_toro Pechuga_de_pollo)
            (NoCompatible Cazón Spaghetti_al_pesto)
            (NoCompatible Arroz Fideos_con_verduras)
            (NoCompatible Arroz_a_la_cubana Langosta_a_la_salsa)
            (NoCompatible Spaghetti_a_la_bolognesa Ensalada_de_arroz)
            (NoCompatible Macarrones_a_la_bolognesa Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_tres_delicias Boquerones_al_vinagre)
            (NoCompatible Lasaña Pulpo_a_la_feira)
            (NoCompatible Arroz_salteado_con_verduras Pechuga_de_pollo)
            (NoCompatible Fetuccini_a_la_putanesca Bacalao_en_salsa_verde)
            (NoCompatible Arroz Ensalada_de_arroz)
            (NoCompatible Sopa_de_fideos Boquerones_al_vinagre)
            (NoCompatible Fetuccini_a_la_putanesca Arroz_con_bogavantes)
            (NoCompatible Pez_espada_y_cosas_pijas Fideos_con_verduras)
            (NoCompatible Entrecot_al_roquefort Ensalada_de_arroz)
            (NoCompatible Hamburguesa_de_pollo Macarrones_a_la_carbonara)
            (NoCompatible Atún_al_horno Ramen)
            (NoCompatible Hamburguesa_de_pollo Spaghetti_al_pesto)
            (NoCompatible Fetuccini_a_la_putanesca Costillitas_de_cordero)
            (NoCompatible Rabo_de_toro Arroz_con_setas)
            (NoCompatible Fetuccini_a_la_putanesca Paella)
            (NoCompatible Calamares_a_la_romana Langosta_a_la_salsa)
            (NoCompatible Cuscús Botifarra_del_pages)
            (NoCompatible Spaghetti_a_la_carbonara Solomillo_de_cerdo)
            (NoCompatible Fetuccini_a_la_putanesca Solomillo_de_cerdo)
            (NoCompatible Entrecot_al_roquefort Langosta_a_la_salsa)
            (NoCompatible Arroz_tres_delicias Ensalada_de_arroz)
            (NoCompatible Pez_espada_y_cosas_pijas Spaghetti_al_pesto)
            (NoCompatible Anchoas Langosta_a_la_salsa)
            (NoCompatible Conejo_asado Arroz_con_setas)
            (NoCompatible Arroz Rabas_y_chocos)
            (NoCompatible Arroz Pechuga_de_pollo)
            (NoCompatible Spaghetti_a_la_bolognesa Arroz_con_setas)
            (NoCompatible Galtas_de_cerdo Fideos_con_verduras)
            (NoCompatible Rabo_de_toro Bacalao_con_tomate)
            (NoCompatible Arroz_salteado_con_verduras Pulpo_a_la_feira)
            (NoCompatible Entrecot_al_roquefort Pollo_a_la_brasa)
            (NoCompatible Entrecot_al_roquefort Spaghetti_al_pesto)
            (NoCompatible Spaghetti_a_la_bolognesa Boquerones_al_vinagre)
            (NoCompatible Rabo_de_toro Macarrones_a_la_carbonara)
            (NoCompatible Cuscús Ramen)

            (tipoP Atún_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazón Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Pescado)
            (tipoS Solomillo_de_cerdo Pescado)
            (tipoP Pato_a_la_naranja Pescado)
            (tipoS Pollo_a_la_brasa Pescado)
            (tipoP Rabo_de_toro Pescado)
            (tipoS Botifarra_del_pages Pescado)
            (tipoP Entrecot_al_roquefort Pescado)
            (tipoS Costillitas_de_cordero Pescado)
            (tipoP Galtas_de_cerdo Pescado)
            (tipoS Callos Pescado)
            (tipoP Hamburguesa_de_pollo Pescado)
            (tipoS Pechuga_de_pollo Pescado)

            (tipoP Arroz_a_la_cubana Pescado)
            (tipoS Ensalada_de_arroz Pescado)
            (tipoP Cuscús Pescado)
            (tipoS Paella Pescado)
            (tipoP Arroz_con_curry Pescado)
            (tipoS Arroz_con_setas Pescado)
            (tipoP Arroz_tres_delicias Pescado)
            (tipoS Arroz_frito_con_salsa_de_cebolla Pescado)
            (tipoP Arroz_salteado_con_verduras Pescado)
            (tipoS Arroz_con_bogavantes Pescado)
            (tipoP Arroz Pescado)
            (tipoS Risotto_con_gambas Pescado)

            (tipoP Macarrones_a_la_bolognesa Pescado)
            (tipoS Macarrones_a_la_carbonara Pescado)
            (tipoP Spaghetti_a_la_bolognesa Pescado)
            (tipoS Spaghetti_al_pesto Pescado)
            (tipoP Spaghetti_a_la_carbonara Pescado)
            (tipoS Ramen Pescado)
            (tipoP Sopa_de_fideos Pescado)
            (tipoS Fideos_con_verduras Pescado)
            (tipoP Fetuccini_a_la_putanesca Pescado)
            (tipoS Ravioli_a_la_genovesa Pescado)
            (tipoP Lasaña Pescado)
            (tipoS Tallarines_con_verduras Pescado)

            (mustUse Lunes Atún_al_horno)
            (RestrictedPrimero Lunes)

            (mustUse Viernes Ramen)
            (RestrictedSegundo Viernes)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atún_al_horno) 725)
            (= (Pcals Lubina_al_limon) 506)
            (= (Pcals Calamares_a_la_romana) 706)
            (= (Pcals Cazón) 587)
            (= (Pcals Anchoas) 731)
            (= (Pcals Pez_espada_y_cosas_pijas) 780)
            (= (Pcals Conejo_asado) 645)
            (= (Pcals Pato_a_la_naranja) 742)
            (= (Pcals Rabo_de_toro) 727)
            (= (Pcals Entrecot_al_roquefort) 654)
            (= (Pcals Galtas_de_cerdo) 764)
            (= (Pcals Hamburguesa_de_pollo) 772)
            (= (Pcals Arroz_a_la_cubana) 664)
            (= (Pcals Cuscús) 524)
            (= (Pcals Arroz_con_curry) 799)
            (= (Pcals Arroz_tres_delicias) 737)
            (= (Pcals Arroz_salteado_con_verduras) 791)
            (= (Pcals Arroz) 550)
            (= (Pcals Macarrones_a_la_bolognesa) 571)
            (= (Pcals Spaghetti_a_la_bolognesa) 674)
            (= (Pcals Spaghetti_a_la_carbonara) 511)
            (= (Pcals Sopa_de_fideos) 745)
            (= (Pcals Fetuccini_a_la_putanesca) 638)
            (= (Pcals Lasaña) 668)

            (= (Scals Bacalao_en_salsa_verde) 599)
            (= (Scals Bacalao_con_tomate) 669)
            (= (Scals Rabas_y_chocos) 766)
            (= (Scals Boquerones_al_vinagre) 507)
            (= (Scals Pulpo_a_la_feira) 621)
            (= (Scals Langosta_a_la_salsa) 724)
            (= (Scals Solomillo_de_cerdo) 773)
            (= (Scals Pollo_a_la_brasa) 660)
            (= (Scals Botifarra_del_pages) 597)
            (= (Scals Costillitas_de_cordero) 728)
            (= (Scals Callos) 616)
            (= (Scals Pechuga_de_pollo) 798)
            (= (Scals Ensalada_de_arroz) 778)
            (= (Scals Paella) 505)
            (= (Scals Arroz_con_setas) 651)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 654)
            (= (Scals Arroz_con_bogavantes) 745)
            (= (Scals Risotto_con_gambas) 616)
            (= (Scals Macarrones_a_la_carbonara) 529)
            (= (Scals Spaghetti_al_pesto) 697)
            (= (Scals Ramen) 577)
            (= (Scals Fideos_con_verduras) 800)
            (= (Scals Ravioli_a_la_genovesa) 547)
            (= (Scals Tallarines_con_verduras) 586)

            (= (Pprice Atún_al_horno) 10)
            (= (Pprice Lubina_al_limon) 13)
            (= (Pprice Calamares_a_la_romana) 6)
            (= (Pprice Cazón) 10)
            (= (Pprice Anchoas) 7)
            (= (Pprice Pez_espada_y_cosas_pijas) 5)
            (= (Pprice Conejo_asado) 9)
            (= (Pprice Pato_a_la_naranja) 10)
            (= (Pprice Rabo_de_toro) 15)
            (= (Pprice Entrecot_al_roquefort) 14)
            (= (Pprice Galtas_de_cerdo) 13)
            (= (Pprice Hamburguesa_de_pollo) 8)
            (= (Pprice Arroz_a_la_cubana) 11)
            (= (Pprice Cuscús) 13)
            (= (Pprice Arroz_con_curry) 15)
            (= (Pprice Arroz_tres_delicias) 6)
            (= (Pprice Arroz_salteado_con_verduras) 5)
            (= (Pprice Arroz) 5)
            (= (Pprice Macarrones_a_la_bolognesa) 9)
            (= (Pprice Spaghetti_a_la_bolognesa) 9)
            (= (Pprice Spaghetti_a_la_carbonara) 13)
            (= (Pprice Sopa_de_fideos) 14)
            (= (Pprice Fetuccini_a_la_putanesca) 9)
            (= (Pprice Lasaña) 11)

            (= (Sprice Bacalao_en_salsa_verde) 14)
            (= (Sprice Bacalao_con_tomate) 14)
            (= (Sprice Rabas_y_chocos) 5)
            (= (Sprice Boquerones_al_vinagre) 5)
            (= (Sprice Pulpo_a_la_feira) 7)
            (= (Sprice Langosta_a_la_salsa) 5)
            (= (Sprice Solomillo_de_cerdo) 15)
            (= (Sprice Pollo_a_la_brasa) 10)
            (= (Sprice Botifarra_del_pages) 13)
            (= (Sprice Costillitas_de_cordero) 11)
            (= (Sprice Callos) 14)
            (= (Sprice Pechuga_de_pollo) 8)
            (= (Sprice Ensalada_de_arroz) 8)
            (= (Sprice Paella) 14)
            (= (Sprice Arroz_con_setas) 6)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 8)
            (= (Sprice Arroz_con_bogavantes) 14)
            (= (Sprice Risotto_con_gambas) 5)
            (= (Sprice Macarrones_a_la_carbonara) 14)
            (= (Sprice Spaghetti_al_pesto) 14)
            (= (Sprice Ramen) 5)
            (= (Sprice Fideos_con_verduras) 13)
            (= (Sprice Ravioli_a_la_genovesa) 10)
            (= (Sprice Tallarines_con_verduras) 9)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)