(define (problem menus)
    (:domain catering)
    (:objects Atun_al_horno Lubina_al_limon Calamares_a_la_romana Cazon Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscus Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz_blanco Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasanya - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Otro Pasta - tipo
)
    (:init
        (primero Atun_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazon)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscus)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz_blanco)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasanya)

        (segundo Bacalao_en_salsa_verde)(segundo Bacalao_con_tomate)(segundo Rabas_y_chocos)(segundo Boquerones_al_vinagre)(segundo Pulpo_a_la_feira)(segundo Langosta_a_la_salsa)(segundo Solomillo_de_cerdo)(segundo Pollo_a_la_brasa)(segundo Botifarra_del_pages)(segundo Costillitas_de_cordero)(segundo Callos)(segundo Pechuga_de_pollo)(segundo Ensalada_de_arroz)(segundo Paella)(segundo Arroz_con_setas)(segundo Arroz_frito_con_salsa_de_cebolla)(segundo Arroz_con_bogavantes)(segundo Risotto_con_gambas)(segundo Macarrones_a_la_carbonara)(segundo Spaghetti_al_pesto)(segundo Ramen)(segundo Fideos_con_verduras)(segundo Ravioli_a_la_genovesa)(segundo Tallarines_con_verduras)

            (NoCompatible Arroz_a_la_cubana Solomillo_de_cerdo)
            (NoCompatible Entrecot_al_roquefort Risotto_con_gambas)
            (NoCompatible Cuscus Ramen)
            (NoCompatible Entrecot_al_roquefort Langosta_a_la_salsa)
            (NoCompatible Arroz_salteado_con_verduras Arroz_con_bogavantes)
            (NoCompatible Spaghetti_a_la_bolognesa Bacalao_con_tomate)
            (NoCompatible Arroz_blanco Macarrones_a_la_carbonara)
            (NoCompatible Fetuccini_a_la_putanesca Arroz_con_setas)
            (NoCompatible Cuscus Botifarra_del_pages)
            (NoCompatible Rabo_de_toro Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Pez_espada_y_cosas_pijas Macarrones_a_la_carbonara)
            (NoCompatible Macarrones_a_la_bolognesa Callos)
            (NoCompatible Arroz_a_la_cubana Pechuga_de_pollo)
            (NoCompatible Lubina_al_limon Solomillo_de_cerdo)
            (NoCompatible Lasanya Paella)
            (NoCompatible Pato_a_la_naranja Pollo_a_la_brasa)
            (NoCompatible Lubina_al_limon Arroz_con_bogavantes)
            (NoCompatible Lubina_al_limon Ensalada_de_arroz)
            (NoCompatible Atun_al_horno Spaghetti_al_pesto)
            (NoCompatible Spaghetti_a_la_bolognesa Fideos_con_verduras)
            (NoCompatible Cuscus Arroz_con_bogavantes)
            (NoCompatible Fetuccini_a_la_putanesca Spaghetti_al_pesto)
            (NoCompatible Lasanya Callos)
            (NoCompatible Sopa_de_fideos Pechuga_de_pollo)
            (NoCompatible Conejo_asado Pulpo_a_la_feira)
            (NoCompatible Anchoas Botifarra_del_pages)
            (NoCompatible Spaghetti_a_la_bolognesa Paella)
            (NoCompatible Rabo_de_toro Spaghetti_al_pesto)
            (NoCompatible Cuscus Spaghetti_al_pesto)
            (NoCompatible Lasanya Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Calamares_a_la_romana Macarrones_a_la_carbonara)
            (NoCompatible Lubina_al_limon Boquerones_al_vinagre)
            (NoCompatible Macarrones_a_la_bolognesa Ravioli_a_la_genovesa)
            (NoCompatible Arroz_blanco Risotto_con_gambas)
            (NoCompatible Fetuccini_a_la_putanesca Fideos_con_verduras)
            (NoCompatible Arroz_con_curry Langosta_a_la_salsa)
            (NoCompatible Atun_al_horno Pulpo_a_la_feira)
            (NoCompatible Arroz_con_curry Risotto_con_gambas)
            (NoCompatible Cuscus Pulpo_a_la_feira)
            (NoCompatible Spaghetti_a_la_bolognesa Ensalada_de_arroz)
            (NoCompatible Atun_al_horno Callos)
            (NoCompatible Arroz_blanco Pollo_a_la_brasa)
            (NoCompatible Atun_al_horno Arroz_con_setas)
            (NoCompatible Macarrones_a_la_bolognesa Tallarines_con_verduras)
            (NoCompatible Macarrones_a_la_bolognesa Spaghetti_al_pesto)
            (NoCompatible Sopa_de_fideos Ramen)
            (NoCompatible Conejo_asado Botifarra_del_pages)
            (NoCompatible Arroz_con_curry Bacalao_en_salsa_verde)

            (tipoP Atun_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazon Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Carne)
            (tipoS Solomillo_de_cerdo Carne)
            (tipoP Pato_a_la_naranja Carne)
            (tipoS Pollo_a_la_brasa Carne)
            (tipoP Rabo_de_toro Carne)
            (tipoS Botifarra_del_pages Carne)
            (tipoP Entrecot_al_roquefort Carne)
            (tipoS Costillitas_de_cordero Carne)
            (tipoP Galtas_de_cerdo Carne)
            (tipoS Callos Carne)
            (tipoP Hamburguesa_de_pollo Carne)
            (tipoS Pechuga_de_pollo Carne)

            (tipoP Arroz_a_la_cubana Otro)
            (tipoS Ensalada_de_arroz Otro)
            (tipoP Cuscus Otro)
            (tipoS Paella Otro)
            (tipoP Arroz_con_curry Otro)
            (tipoS Arroz_con_setas Otro)
            (tipoP Arroz_tres_delicias Otro)
            (tipoS Arroz_frito_con_salsa_de_cebolla Otro)
            (tipoP Arroz_salteado_con_verduras Otro)
            (tipoS Arroz_con_bogavantes Otro)
            (tipoP Arroz_blanco Otro)
            (tipoS Risotto_con_gambas Otro)

            (tipoP Macarrones_a_la_bolognesa Pasta)
            (tipoS Macarrones_a_la_carbonara Pasta)
            (tipoP Spaghetti_a_la_bolognesa Pasta)
            (tipoS Spaghetti_al_pesto Pasta)
            (tipoP Spaghetti_a_la_carbonara Pasta)
            (tipoS Ramen Pasta)
            (tipoP Sopa_de_fideos Pasta)
            (tipoS Fideos_con_verduras Pasta)
            (tipoP Fetuccini_a_la_putanesca Pasta)
            (tipoS Ravioli_a_la_genovesa Pasta)
            (tipoP Lasanya Pasta)
            (tipoS Tallarines_con_verduras Pasta)

            (mustUse Miercoles Macarrones_a_la_bolognesa)
            (RestrictedPrimero Miercoles)

            (mustUse Viernes Solomillo_de_cerdo)
            (RestrictedSegundo Viernes)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atun_al_horno) 719)
            (= (Pcals Lubina_al_limon) 721)
            (= (Pcals Calamares_a_la_romana) 711)
            (= (Pcals Cazon) 587)
            (= (Pcals Anchoas) 544)
            (= (Pcals Pez_espada_y_cosas_pijas) 682)
            (= (Pcals Conejo_asado) 685)
            (= (Pcals Pato_a_la_naranja) 772)
            (= (Pcals Rabo_de_toro) 649)
            (= (Pcals Entrecot_al_roquefort) 703)
            (= (Pcals Galtas_de_cerdo) 638)
            (= (Pcals Hamburguesa_de_pollo) 512)
            (= (Pcals Arroz_a_la_cubana) 715)
            (= (Pcals Cuscus) 618)
            (= (Pcals Arroz_con_curry) 736)
            (= (Pcals Arroz_tres_delicias) 797)
            (= (Pcals Arroz_salteado_con_verduras) 788)
            (= (Pcals Arroz_blanco) 571)
            (= (Pcals Macarrones_a_la_bolognesa) 718)
            (= (Pcals Spaghetti_a_la_bolognesa) 659)
            (= (Pcals Spaghetti_a_la_carbonara) 558)
            (= (Pcals Sopa_de_fideos) 501)
            (= (Pcals Fetuccini_a_la_putanesca) 686)
            (= (Pcals Lasanya) 526)

            (= (Scals Bacalao_en_salsa_verde) 666)
            (= (Scals Bacalao_con_tomate) 704)
            (= (Scals Rabas_y_chocos) 512)
            (= (Scals Boquerones_al_vinagre) 585)
            (= (Scals Pulpo_a_la_feira) 797)
            (= (Scals Langosta_a_la_salsa) 689)
            (= (Scals Solomillo_de_cerdo) 529)
            (= (Scals Pollo_a_la_brasa) 638)
            (= (Scals Botifarra_del_pages) 614)
            (= (Scals Costillitas_de_cordero) 578)
            (= (Scals Callos) 664)
            (= (Scals Pechuga_de_pollo) 624)
            (= (Scals Ensalada_de_arroz) 774)
            (= (Scals Paella) 633)
            (= (Scals Arroz_con_setas) 511)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 620)
            (= (Scals Arroz_con_bogavantes) 628)
            (= (Scals Risotto_con_gambas) 577)
            (= (Scals Macarrones_a_la_carbonara) 571)
            (= (Scals Spaghetti_al_pesto) 689)
            (= (Scals Ramen) 588)
            (= (Scals Fideos_con_verduras) 507)
            (= (Scals Ravioli_a_la_genovesa) 603)
            (= (Scals Tallarines_con_verduras) 750)

            (= (Pprice Atun_al_horno) 10)
            (= (Pprice Lubina_al_limon) 10)
            (= (Pprice Calamares_a_la_romana) 7)
            (= (Pprice Cazon) 7)
            (= (Pprice Anchoas) 15)
            (= (Pprice Pez_espada_y_cosas_pijas) 11)
            (= (Pprice Conejo_asado) 12)
            (= (Pprice Pato_a_la_naranja) 12)
            (= (Pprice Rabo_de_toro) 7)
            (= (Pprice Entrecot_al_roquefort) 10)
            (= (Pprice Galtas_de_cerdo) 11)
            (= (Pprice Hamburguesa_de_pollo) 8)
            (= (Pprice Arroz_a_la_cubana) 11)
            (= (Pprice Cuscus) 8)
            (= (Pprice Arroz_con_curry) 13)
            (= (Pprice Arroz_tres_delicias) 15)
            (= (Pprice Arroz_salteado_con_verduras) 9)
            (= (Pprice Arroz_blanco) 9)
            (= (Pprice Macarrones_a_la_bolognesa) 14)
            (= (Pprice Spaghetti_a_la_bolognesa) 13)
            (= (Pprice Spaghetti_a_la_carbonara) 5)
            (= (Pprice Sopa_de_fideos) 15)
            (= (Pprice Fetuccini_a_la_putanesca) 8)
            (= (Pprice Lasanya) 6)

            (= (Sprice Bacalao_en_salsa_verde) 14)
            (= (Sprice Bacalao_con_tomate) 13)
            (= (Sprice Rabas_y_chocos) 7)
            (= (Sprice Boquerones_al_vinagre) 10)
            (= (Sprice Pulpo_a_la_feira) 14)
            (= (Sprice Langosta_a_la_salsa) 9)
            (= (Sprice Solomillo_de_cerdo) 11)
            (= (Sprice Pollo_a_la_brasa) 9)
            (= (Sprice Botifarra_del_pages) 15)
            (= (Sprice Costillitas_de_cordero) 14)
            (= (Sprice Callos) 6)
            (= (Sprice Pechuga_de_pollo) 10)
            (= (Sprice Ensalada_de_arroz) 11)
            (= (Sprice Paella) 12)
            (= (Sprice Arroz_con_setas) 5)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 9)
            (= (Sprice Arroz_con_bogavantes) 5)
            (= (Sprice Risotto_con_gambas) 13)
            (= (Sprice Macarrones_a_la_carbonara) 7)
            (= (Sprice Spaghetti_al_pesto) 10)
            (= (Sprice Ramen) 7)
            (= (Sprice Fideos_con_verduras) 11)
            (= (Sprice Ravioli_a_la_genovesa) 11)
            (= (Sprice Tallarines_con_verduras) 5)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)