(define (problem menus)
    (:domain catering)
    (:objects Atún_al_horno Lubina_al_limon Calamares_a_la_romana Cazón Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscús Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasaña - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Arroz Pasta - tipo
)
    (:init
        (primero Atún_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazón)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscús)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasaña)

        (Segundo Bacalao_en_salsa_verde)(Segundo Bacalao_con_tomate)(Segundo Rabas_y_chocos)(Segundo Boquerones_al_vinagre)(Segundo Pulpo_a_la_feira)(Segundo Langosta_a_la_salsa)(Segundo Solomillo_de_cerdo)(Segundo Pollo_a_la_brasa)(Segundo Botifarra_del_pages)(Segundo Costillitas_de_cordero)(Segundo Callos)(Segundo Pechuga_de_pollo)(Segundo Ensalada_de_arroz)(Segundo Paella)(Segundo Arroz_con_setas)(Segundo Arroz_frito_con_salsa_de_cebolla)(Segundo Arroz_con_bogavantes)(Segundo Risotto_con_gambas)(Segundo Macarrones_a_la_carbonara)(Segundo Spaghetti_al_pesto)(Segundo Ramen)(Segundo Fideos_con_verduras)(Segundo Ravioli_a_la_genovesa)(Segundo Tallarines_con_verduras)

            (NoCompatible Fetuccini_a_la_putanesca Arroz_con_setas)
            (NoCompatible Atún_al_horno Tallarines_con_verduras)
            (NoCompatible Entrecot_al_roquefort Boquerones_al_vinagre)
            (NoCompatible Cuscús Macarrones_a_la_carbonara)
            (NoCompatible Pez_espada_y_cosas_pijas Arroz_con_bogavantes)
            (NoCompatible Lubina_al_limon Pechuga_de_pollo)
            (NoCompatible Atún_al_horno Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Spaghetti_a_la_bolognesa Solomillo_de_cerdo)
            (NoCompatible Arroz_tres_delicias Arroz_con_bogavantes)
            (NoCompatible Rabo_de_toro Boquerones_al_vinagre)
            (NoCompatible Hamburguesa_de_pollo Costillitas_de_cordero)
            (NoCompatible Macarrones_a_la_bolognesa Risotto_con_gambas)
            (NoCompatible Arroz_tres_delicias Pechuga_de_pollo)
            (NoCompatible Anchoas Costillitas_de_cordero)
            (NoCompatible Arroz_a_la_cubana Costillitas_de_cordero)
            (NoCompatible Pato_a_la_naranja Macarrones_a_la_carbonara)
            (NoCompatible Galtas_de_cerdo Bacalao_en_salsa_verde)
            (NoCompatible Sopa_de_fideos Spaghetti_al_pesto)
            (NoCompatible Arroz_tres_delicias Callos)
            (NoCompatible Sopa_de_fideos Paella)
            (NoCompatible Anchoas Solomillo_de_cerdo)
            (NoCompatible Macarrones_a_la_bolognesa Botifarra_del_pages)
            (NoCompatible Spaghetti_a_la_carbonara Rabas_y_chocos)
            (NoCompatible Arroz_salteado_con_verduras Paella)
            (NoCompatible Cazón Bacalao_en_salsa_verde)
            (NoCompatible Calamares_a_la_romana Risotto_con_gambas)
            (NoCompatible Atún_al_horno Paella)
            (NoCompatible Arroz_con_curry Botifarra_del_pages)
            (NoCompatible Spaghetti_a_la_carbonara Costillitas_de_cordero)
            (NoCompatible Pato_a_la_naranja Rabas_y_chocos)
            (NoCompatible Sopa_de_fideos Langosta_a_la_salsa)
            (NoCompatible Arroz Ensalada_de_arroz)
            (NoCompatible Pez_espada_y_cosas_pijas Botifarra_del_pages)
            (NoCompatible Atún_al_horno Spaghetti_al_pesto)
            (NoCompatible Arroz_salteado_con_verduras Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Spaghetti_a_la_carbonara Callos)
            (NoCompatible Cuscús Botifarra_del_pages)
            (NoCompatible Fetuccini_a_la_putanesca Boquerones_al_vinagre)
            (NoCompatible Arroz_a_la_cubana Tallarines_con_verduras)
            (NoCompatible Fetuccini_a_la_putanesca Solomillo_de_cerdo)
            (NoCompatible Conejo_asado Tallarines_con_verduras)
            (NoCompatible Galtas_de_cerdo Langosta_a_la_salsa)
            (NoCompatible Arroz_con_curry Tallarines_con_verduras)
            (NoCompatible Arroz_tres_delicias Costillitas_de_cordero)
            (NoCompatible Conejo_asado Costillitas_de_cordero)
            (NoCompatible Arroz_salteado_con_verduras Bacalao_con_tomate)
            (NoCompatible Pez_espada_y_cosas_pijas Ramen)
            (NoCompatible Spaghetti_a_la_bolognesa Ensalada_de_arroz)

            (tipoP Atún_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazón Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Pescado)
            (tipoS Solomillo_de_cerdo Pescado)
            (tipoP Pato_a_la_naranja Pescado)
            (tipoS Pollo_a_la_brasa Pescado)
            (tipoP Rabo_de_toro Pescado)
            (tipoS Botifarra_del_pages Pescado)
            (tipoP Entrecot_al_roquefort Pescado)
            (tipoS Costillitas_de_cordero Pescado)
            (tipoP Galtas_de_cerdo Pescado)
            (tipoS Callos Pescado)
            (tipoP Hamburguesa_de_pollo Pescado)
            (tipoS Pechuga_de_pollo Pescado)

            (tipoP Arroz_a_la_cubana Pescado)
            (tipoS Ensalada_de_arroz Pescado)
            (tipoP Cuscús Pescado)
            (tipoS Paella Pescado)
            (tipoP Arroz_con_curry Pescado)
            (tipoS Arroz_con_setas Pescado)
            (tipoP Arroz_tres_delicias Pescado)
            (tipoS Arroz_frito_con_salsa_de_cebolla Pescado)
            (tipoP Arroz_salteado_con_verduras Pescado)
            (tipoS Arroz_con_bogavantes Pescado)
            (tipoP Arroz Pescado)
            (tipoS Risotto_con_gambas Pescado)

            (tipoP Macarrones_a_la_bolognesa Pescado)
            (tipoS Macarrones_a_la_carbonara Pescado)
            (tipoP Spaghetti_a_la_bolognesa Pescado)
            (tipoS Spaghetti_al_pesto Pescado)
            (tipoP Spaghetti_a_la_carbonara Pescado)
            (tipoS Ramen Pescado)
            (tipoP Sopa_de_fideos Pescado)
            (tipoS Fideos_con_verduras Pescado)
            (tipoP Fetuccini_a_la_putanesca Pescado)
            (tipoS Ravioli_a_la_genovesa Pescado)
            (tipoP Lasaña Pescado)
            (tipoS Tallarines_con_verduras Pescado)

            (mustUse Jueves Arroz_salteado_con_verduras)
            (RestrictedPrimero Jueves)

            (mustUse Miercoles Boquerones_al_vinagre)
            (RestrictedSegundo Miercoles)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atún_al_horno) 543)
            (= (Pcals Lubina_al_limon) 663)
            (= (Pcals Calamares_a_la_romana) 557)
            (= (Pcals Cazón) 754)
            (= (Pcals Anchoas) 546)
            (= (Pcals Pez_espada_y_cosas_pijas) 541)
            (= (Pcals Conejo_asado) 707)
            (= (Pcals Pato_a_la_naranja) 769)
            (= (Pcals Rabo_de_toro) 590)
            (= (Pcals Entrecot_al_roquefort) 550)
            (= (Pcals Galtas_de_cerdo) 580)
            (= (Pcals Hamburguesa_de_pollo) 772)
            (= (Pcals Arroz_a_la_cubana) 797)
            (= (Pcals Cuscús) 609)
            (= (Pcals Arroz_con_curry) 518)
            (= (Pcals Arroz_tres_delicias) 669)
            (= (Pcals Arroz_salteado_con_verduras) 659)
            (= (Pcals Arroz) 747)
            (= (Pcals Macarrones_a_la_bolognesa) 566)
            (= (Pcals Spaghetti_a_la_bolognesa) 551)
            (= (Pcals Spaghetti_a_la_carbonara) 616)
            (= (Pcals Sopa_de_fideos) 573)
            (= (Pcals Fetuccini_a_la_putanesca) 621)
            (= (Pcals Lasaña) 506)

            (= (Scals Bacalao_en_salsa_verde) 731)
            (= (Scals Bacalao_con_tomate) 539)
            (= (Scals Rabas_y_chocos) 663)
            (= (Scals Boquerones_al_vinagre) 619)
            (= (Scals Pulpo_a_la_feira) 544)
            (= (Scals Langosta_a_la_salsa) 532)
            (= (Scals Solomillo_de_cerdo) 746)
            (= (Scals Pollo_a_la_brasa) 757)
            (= (Scals Botifarra_del_pages) 551)
            (= (Scals Costillitas_de_cordero) 525)
            (= (Scals Callos) 665)
            (= (Scals Pechuga_de_pollo) 667)
            (= (Scals Ensalada_de_arroz) 650)
            (= (Scals Paella) 759)
            (= (Scals Arroz_con_setas) 694)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 762)
            (= (Scals Arroz_con_bogavantes) 688)
            (= (Scals Risotto_con_gambas) 800)
            (= (Scals Macarrones_a_la_carbonara) 606)
            (= (Scals Spaghetti_al_pesto) 773)
            (= (Scals Ramen) 558)
            (= (Scals Fideos_con_verduras) 610)
            (= (Scals Ravioli_a_la_genovesa) 576)
            (= (Scals Tallarines_con_verduras) 707)

            (= (Pprice Atún_al_horno) 10)
            (= (Pprice Lubina_al_limon) 9)
            (= (Pprice Calamares_a_la_romana) 10)
            (= (Pprice Cazón) 14)
            (= (Pprice Anchoas) 11)
            (= (Pprice Pez_espada_y_cosas_pijas) 9)
            (= (Pprice Conejo_asado) 11)
            (= (Pprice Pato_a_la_naranja) 13)
            (= (Pprice Rabo_de_toro) 7)
            (= (Pprice Entrecot_al_roquefort) 7)
            (= (Pprice Galtas_de_cerdo) 13)
            (= (Pprice Hamburguesa_de_pollo) 13)
            (= (Pprice Arroz_a_la_cubana) 15)
            (= (Pprice Cuscús) 7)
            (= (Pprice Arroz_con_curry) 5)
            (= (Pprice Arroz_tres_delicias) 9)
            (= (Pprice Arroz_salteado_con_verduras) 7)
            (= (Pprice Arroz) 10)
            (= (Pprice Macarrones_a_la_bolognesa) 9)
            (= (Pprice Spaghetti_a_la_bolognesa) 6)
            (= (Pprice Spaghetti_a_la_carbonara) 5)
            (= (Pprice Sopa_de_fideos) 13)
            (= (Pprice Fetuccini_a_la_putanesca) 15)
            (= (Pprice Lasaña) 8)

            (= (Sprice Bacalao_en_salsa_verde) 14)
            (= (Sprice Bacalao_con_tomate) 13)
            (= (Sprice Rabas_y_chocos) 11)
            (= (Sprice Boquerones_al_vinagre) 15)
            (= (Sprice Pulpo_a_la_feira) 7)
            (= (Sprice Langosta_a_la_salsa) 15)
            (= (Sprice Solomillo_de_cerdo) 7)
            (= (Sprice Pollo_a_la_brasa) 13)
            (= (Sprice Botifarra_del_pages) 7)
            (= (Sprice Costillitas_de_cordero) 14)
            (= (Sprice Callos) 12)
            (= (Sprice Pechuga_de_pollo) 9)
            (= (Sprice Ensalada_de_arroz) 12)
            (= (Sprice Paella) 5)
            (= (Sprice Arroz_con_setas) 11)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 15)
            (= (Sprice Arroz_con_bogavantes) 7)
            (= (Sprice Risotto_con_gambas) 13)
            (= (Sprice Macarrones_a_la_carbonara) 8)
            (= (Sprice Spaghetti_al_pesto) 7)
            (= (Sprice Ramen) 7)
            (= (Sprice Fideos_con_verduras) 5)
            (= (Sprice Ravioli_a_la_genovesa) 6)
            (= (Sprice Tallarines_con_verduras) 7)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)