(define (problem menus)
    (:domain catering)
    (:objects Atún_al_horno Lubina_al_limon Calamares_a_la_romana Cazón Anchoas Pez_espada_y_cosas_pijas Conejo_asado Pato_a_la_naranja Rabo_de_toro Entrecot_al_roquefort Galtas_de_cerdo Hamburguesa_de_pollo Arroz_a_la_cubana Cuscús Arroz_con_curry Arroz_tres_delicias Arroz_salteado_con_verduras Arroz Macarrones_a_la_bolognesa Spaghetti_a_la_bolognesa Spaghetti_a_la_carbonara Sopa_de_fideos Fetuccini_a_la_putanesca Lasaña - primero
            Bacalao_en_salsa_verde Bacalao_con_tomate Rabas_y_chocos Boquerones_al_vinagre Pulpo_a_la_feira Langosta_a_la_salsa Solomillo_de_cerdo Pollo_a_la_brasa Botifarra_del_pages Costillitas_de_cordero Callos Pechuga_de_pollo Ensalada_de_arroz Paella Arroz_con_setas Arroz_frito_con_salsa_de_cebolla Arroz_con_bogavantes Risotto_con_gambas Macarrones_a_la_carbonara Spaghetti_al_pesto Ramen Fideos_con_verduras Ravioli_a_la_genovesa Tallarines_con_verduras - segundo
            Lunes Martes Miercoles Jueves Viernes - dia
            Pescado Carne Arroz Pasta - tipo
)
    (:init
        (primero Atún_al_horno)(primero Lubina_al_limon)(primero Calamares_a_la_romana)(primero Cazón)(primero Anchoas)(primero Pez_espada_y_cosas_pijas)(primero Conejo_asado)(primero Pato_a_la_naranja)(primero Rabo_de_toro)(primero Entrecot_al_roquefort)(primero Galtas_de_cerdo)(primero Hamburguesa_de_pollo)(primero Arroz_a_la_cubana)(primero Cuscús)(primero Arroz_con_curry)(primero Arroz_tres_delicias)(primero Arroz_salteado_con_verduras)(primero Arroz)(primero Macarrones_a_la_bolognesa)(primero Spaghetti_a_la_bolognesa)(primero Spaghetti_a_la_carbonara)(primero Sopa_de_fideos)(primero Fetuccini_a_la_putanesca)(primero Lasaña)

        (Segundo Bacalao_en_salsa_verde)(Segundo Bacalao_con_tomate)(Segundo Rabas_y_chocos)(Segundo Boquerones_al_vinagre)(Segundo Pulpo_a_la_feira)(Segundo Langosta_a_la_salsa)(Segundo Solomillo_de_cerdo)(Segundo Pollo_a_la_brasa)(Segundo Botifarra_del_pages)(Segundo Costillitas_de_cordero)(Segundo Callos)(Segundo Pechuga_de_pollo)(Segundo Ensalada_de_arroz)(Segundo Paella)(Segundo Arroz_con_setas)(Segundo Arroz_frito_con_salsa_de_cebolla)(Segundo Arroz_con_bogavantes)(Segundo Risotto_con_gambas)(Segundo Macarrones_a_la_carbonara)(Segundo Spaghetti_al_pesto)(Segundo Ramen)(Segundo Fideos_con_verduras)(Segundo Ravioli_a_la_genovesa)(Segundo Tallarines_con_verduras)

            (NoCompatible Arroz_a_la_cubana Spaghetti_al_pesto)
            (NoCompatible Conejo_asado Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_con_curry Pollo_a_la_brasa)
            (NoCompatible Arroz_salteado_con_verduras Rabas_y_chocos)
            (NoCompatible Sopa_de_fideos Tallarines_con_verduras)
            (NoCompatible Arroz_salteado_con_verduras Solomillo_de_cerdo)
            (NoCompatible Pato_a_la_naranja Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Macarrones_a_la_bolognesa Risotto_con_gambas)
            (NoCompatible Arroz_a_la_cubana Solomillo_de_cerdo)
            (NoCompatible Fetuccini_a_la_putanesca Bacalao_en_salsa_verde)
            (NoCompatible Galtas_de_cerdo Macarrones_a_la_carbonara)
            (NoCompatible Lubina_al_limon Spaghetti_al_pesto)
            (NoCompatible Arroz_a_la_cubana Tallarines_con_verduras)
            (NoCompatible Sopa_de_fideos Bacalao_en_salsa_verde)
            (NoCompatible Hamburguesa_de_pollo Pollo_a_la_brasa)
            (NoCompatible Fetuccini_a_la_putanesca Ravioli_a_la_genovesa)
            (NoCompatible Pez_espada_y_cosas_pijas Paella)
            (NoCompatible Atún_al_horno Fideos_con_verduras)
            (NoCompatible Lubina_al_limon Bacalao_con_tomate)
            (NoCompatible Entrecot_al_roquefort Tallarines_con_verduras)
            (NoCompatible Arroz_con_curry Arroz_frito_con_salsa_de_cebolla)
            (NoCompatible Arroz_con_curry Spaghetti_al_pesto)
            (NoCompatible Atún_al_horno Risotto_con_gambas)
            (NoCompatible Galtas_de_cerdo Pulpo_a_la_feira)
            (NoCompatible Macarrones_a_la_bolognesa Fideos_con_verduras)
            (NoCompatible Macarrones_a_la_bolognesa Ensalada_de_arroz)
            (NoCompatible Arroz_con_curry Fideos_con_verduras)
            (NoCompatible Anchoas Pechuga_de_pollo)
            (NoCompatible Arroz Ramen)
            (NoCompatible Lasaña Fideos_con_verduras)
            (NoCompatible Lasaña Paella)
            (NoCompatible Cuscús Arroz_con_bogavantes)
            (NoCompatible Anchoas Ravioli_a_la_genovesa)
            (NoCompatible Pez_espada_y_cosas_pijas Ramen)
            (NoCompatible Spaghetti_a_la_carbonara Paella)
            (NoCompatible Anchoas Arroz_con_bogavantes)
            (NoCompatible Galtas_de_cerdo Pechuga_de_pollo)
            (NoCompatible Lubina_al_limon Macarrones_a_la_carbonara)
            (NoCompatible Anchoas Tallarines_con_verduras)
            (NoCompatible Pato_a_la_naranja Callos)
            (NoCompatible Arroz_con_curry Risotto_con_gambas)
            (NoCompatible Arroz_salteado_con_verduras Risotto_con_gambas)
            (NoCompatible Spaghetti_a_la_bolognesa Ravioli_a_la_genovesa)
            (NoCompatible Calamares_a_la_romana Risotto_con_gambas)
            (NoCompatible Pez_espada_y_cosas_pijas Costillitas_de_cordero)
            (NoCompatible Calamares_a_la_romana Arroz_con_setas)
            (NoCompatible Sopa_de_fideos Fideos_con_verduras)
            (NoCompatible Calamares_a_la_romana Bacalao_en_salsa_verde)

            (tipoP Atún_al_horno Pescado)
            (tipoS Bacalao_en_salsa_verde Pescado)
            (tipoP Lubina_al_limon Pescado)
            (tipoS Bacalao_con_tomate Pescado)
            (tipoP Calamares_a_la_romana Pescado)
            (tipoS Rabas_y_chocos Pescado)
            (tipoP Cazón Pescado)
            (tipoS Boquerones_al_vinagre Pescado)
            (tipoP Anchoas Pescado)
            (tipoS Pulpo_a_la_feira Pescado)
            (tipoP Pez_espada_y_cosas_pijas Pescado)
            (tipoS Langosta_a_la_salsa Pescado)

            (tipoP Conejo_asado Pescado)
            (tipoS Solomillo_de_cerdo Pescado)
            (tipoP Pato_a_la_naranja Pescado)
            (tipoS Pollo_a_la_brasa Pescado)
            (tipoP Rabo_de_toro Pescado)
            (tipoS Botifarra_del_pages Pescado)
            (tipoP Entrecot_al_roquefort Pescado)
            (tipoS Costillitas_de_cordero Pescado)
            (tipoP Galtas_de_cerdo Pescado)
            (tipoS Callos Pescado)
            (tipoP Hamburguesa_de_pollo Pescado)
            (tipoS Pechuga_de_pollo Pescado)

            (tipoP Arroz_a_la_cubana Pescado)
            (tipoS Ensalada_de_arroz Pescado)
            (tipoP Cuscús Pescado)
            (tipoS Paella Pescado)
            (tipoP Arroz_con_curry Pescado)
            (tipoS Arroz_con_setas Pescado)
            (tipoP Arroz_tres_delicias Pescado)
            (tipoS Arroz_frito_con_salsa_de_cebolla Pescado)
            (tipoP Arroz_salteado_con_verduras Pescado)
            (tipoS Arroz_con_bogavantes Pescado)
            (tipoP Arroz Pescado)
            (tipoS Risotto_con_gambas Pescado)

            (tipoP Macarrones_a_la_bolognesa Pescado)
            (tipoS Macarrones_a_la_carbonara Pescado)
            (tipoP Spaghetti_a_la_bolognesa Pescado)
            (tipoS Spaghetti_al_pesto Pescado)
            (tipoP Spaghetti_a_la_carbonara Pescado)
            (tipoS Ramen Pescado)
            (tipoP Sopa_de_fideos Pescado)
            (tipoS Fideos_con_verduras Pescado)
            (tipoP Fetuccini_a_la_putanesca Pescado)
            (tipoS Ravioli_a_la_genovesa Pescado)
            (tipoP Lasaña Pescado)
            (tipoS Tallarines_con_verduras Pescado)

            (mustUse Lunes Rabo_de_toro)
            (RestrictedPrimero Lunes)

            (mustUse Martes Ensalada_de_arroz)
            (RestrictedSegundo Martes)

            (diaAnterior Lunes Martes)
            (diaAnterior Martes Miercoles)
            (diaAnterior Miercoles Jueves)
            (diaAnterior Jueves Viernes)

            (firstDay Lunes)

            (= (Pcals Atún_al_horno) 505)
            (= (Pcals Lubina_al_limon) 549)
            (= (Pcals Calamares_a_la_romana) 702)
            (= (Pcals Cazón) 554)
            (= (Pcals Anchoas) 765)
            (= (Pcals Pez_espada_y_cosas_pijas) 546)
            (= (Pcals Conejo_asado) 749)
            (= (Pcals Pato_a_la_naranja) 733)
            (= (Pcals Rabo_de_toro) 510)
            (= (Pcals Entrecot_al_roquefort) 581)
            (= (Pcals Galtas_de_cerdo) 630)
            (= (Pcals Hamburguesa_de_pollo) 741)
            (= (Pcals Arroz_a_la_cubana) 536)
            (= (Pcals Cuscús) 583)
            (= (Pcals Arroz_con_curry) 583)
            (= (Pcals Arroz_tres_delicias) 615)
            (= (Pcals Arroz_salteado_con_verduras) 699)
            (= (Pcals Arroz) 670)
            (= (Pcals Macarrones_a_la_bolognesa) 686)
            (= (Pcals Spaghetti_a_la_bolognesa) 774)
            (= (Pcals Spaghetti_a_la_carbonara) 686)
            (= (Pcals Sopa_de_fideos) 585)
            (= (Pcals Fetuccini_a_la_putanesca) 642)
            (= (Pcals Lasaña) 733)

            (= (Scals Bacalao_en_salsa_verde) 645)
            (= (Scals Bacalao_con_tomate) 574)
            (= (Scals Rabas_y_chocos) 757)
            (= (Scals Boquerones_al_vinagre) 650)
            (= (Scals Pulpo_a_la_feira) 547)
            (= (Scals Langosta_a_la_salsa) 798)
            (= (Scals Solomillo_de_cerdo) 672)
            (= (Scals Pollo_a_la_brasa) 714)
            (= (Scals Botifarra_del_pages) 662)
            (= (Scals Costillitas_de_cordero) 688)
            (= (Scals Callos) 797)
            (= (Scals Pechuga_de_pollo) 752)
            (= (Scals Ensalada_de_arroz) 658)
            (= (Scals Paella) 709)
            (= (Scals Arroz_con_setas) 690)
            (= (Scals Arroz_frito_con_salsa_de_cebolla) 671)
            (= (Scals Arroz_con_bogavantes) 517)
            (= (Scals Risotto_con_gambas) 799)
            (= (Scals Macarrones_a_la_carbonara) 613)
            (= (Scals Spaghetti_al_pesto) 702)
            (= (Scals Ramen) 547)
            (= (Scals Fideos_con_verduras) 764)
            (= (Scals Ravioli_a_la_genovesa) 561)
            (= (Scals Tallarines_con_verduras) 756)

            (= (Pprice Atún_al_horno) 5)
            (= (Pprice Lubina_al_limon) 14)
            (= (Pprice Calamares_a_la_romana) 6)
            (= (Pprice Cazón) 8)
            (= (Pprice Anchoas) 9)
            (= (Pprice Pez_espada_y_cosas_pijas) 6)
            (= (Pprice Conejo_asado) 10)
            (= (Pprice Pato_a_la_naranja) 14)
            (= (Pprice Rabo_de_toro) 11)
            (= (Pprice Entrecot_al_roquefort) 15)
            (= (Pprice Galtas_de_cerdo) 7)
            (= (Pprice Hamburguesa_de_pollo) 7)
            (= (Pprice Arroz_a_la_cubana) 8)
            (= (Pprice Cuscús) 6)
            (= (Pprice Arroz_con_curry) 12)
            (= (Pprice Arroz_tres_delicias) 14)
            (= (Pprice Arroz_salteado_con_verduras) 7)
            (= (Pprice Arroz) 11)
            (= (Pprice Macarrones_a_la_bolognesa) 7)
            (= (Pprice Spaghetti_a_la_bolognesa) 14)
            (= (Pprice Spaghetti_a_la_carbonara) 9)
            (= (Pprice Sopa_de_fideos) 8)
            (= (Pprice Fetuccini_a_la_putanesca) 13)
            (= (Pprice Lasaña) 10)

            (= (Sprice Bacalao_en_salsa_verde) 6)
            (= (Sprice Bacalao_con_tomate) 7)
            (= (Sprice Rabas_y_chocos) 8)
            (= (Sprice Boquerones_al_vinagre) 14)
            (= (Sprice Pulpo_a_la_feira) 6)
            (= (Sprice Langosta_a_la_salsa) 15)
            (= (Sprice Solomillo_de_cerdo) 6)
            (= (Sprice Pollo_a_la_brasa) 11)
            (= (Sprice Botifarra_del_pages) 12)
            (= (Sprice Costillitas_de_cordero) 7)
            (= (Sprice Callos) 7)
            (= (Sprice Pechuga_de_pollo) 14)
            (= (Sprice Ensalada_de_arroz) 15)
            (= (Sprice Paella) 11)
            (= (Sprice Arroz_con_setas) 12)
            (= (Sprice Arroz_frito_con_salsa_de_cebolla) 11)
            (= (Sprice Arroz_con_bogavantes) 9)
            (= (Sprice Risotto_con_gambas) 13)
            (= (Sprice Macarrones_a_la_carbonara) 8)
            (= (Sprice Spaghetti_al_pesto) 13)
            (= (Sprice Ramen) 11)
            (= (Sprice Fideos_con_verduras) 14)
            (= (Sprice Ravioli_a_la_genovesa) 7)
            (= (Sprice Tallarines_con_verduras) 7)

            (= (coste-total) 0)

      )
    (:goal (forall (?d - dia) (hayMenu ?d)))
    (:metric minimize (coste-total))
)